import type { Difficulty } from '@/shared/types';

export interface TabooClassicCard {
  id: number;
  word: string;
  forbidden: string[];
  difficulty: Difficulty;
}

// ─── Easy ──────────────────────────────────────────────────────────────────────
// Простые слова, 4 запрещённых — самые очевидные синонимы и связанные слова
const EASY: TabooClassicCard[] = [
  { id: 1, difficulty: 'easy', word: 'КОШКА', forbidden: ['кот', 'животное', 'мяу', 'пушистый'] },
  { id: 2, difficulty: 'easy', word: 'СОБАКА', forbidden: ['пёс', 'животное', 'лаять', 'хвост'] },
  { id: 3, difficulty: 'easy', word: 'ЯБЛОКО', forbidden: ['фрукт', 'красный', 'дерево', 'сок'] },
  {
    id: 4,
    difficulty: 'easy',
    word: 'МАШИНА',
    forbidden: ['автомобиль', 'руль', 'ехать', 'колесо'],
  },
  { id: 5, difficulty: 'easy', word: 'СОЛНЦЕ', forbidden: ['светить', 'жаркий', 'небо', 'звезда'] },
  { id: 6, difficulty: 'easy', word: 'ДЕРЕВО', forbidden: ['ветка', 'листья', 'расти', 'лес'] },
  { id: 7, difficulty: 'easy', word: 'МЯЧ', forbidden: ['круглый', 'бросать', 'играть', 'футбол'] },
  { id: 8, difficulty: 'easy', word: 'РЫБА', forbidden: ['море', 'плавать', 'чешуя', 'ловить'] },
  { id: 9, difficulty: 'easy', word: 'ХЛЕБ', forbidden: ['мука', 'печь', 'есть', 'буханка'] },
  { id: 10, difficulty: 'easy', word: 'ВОДА', forbidden: ['пить', 'жидкость', 'мокрый', 'море'] },
  { id: 11, difficulty: 'easy', word: 'ТОРТ', forbidden: ['сладкий', 'праздник', 'свеча', 'крем'] },
  {
    id: 12,
    difficulty: 'easy',
    word: 'ТЕЛЕВИЗОР',
    forbidden: ['смотреть', 'экран', 'канал', 'пульт'],
  },
  { id: 13, difficulty: 'easy', word: 'ЗОНТ', forbidden: ['дождь', 'раскрыть', 'мокрый', 'ручка'] },
  {
    id: 14,
    difficulty: 'easy',
    word: 'ВЕЛОСИПЕД',
    forbidden: ['ехать', 'педаль', 'руль', 'колесо'],
  },
  { id: 15, difficulty: 'easy', word: 'КОФЕ', forbidden: ['горячий', 'чашка', 'напиток', 'утро'] },
  { id: 16, difficulty: 'easy', word: 'САМОЛЁТ', forbidden: ['лететь', 'крыло', 'небо', 'пилот'] },
  { id: 17, difficulty: 'easy', word: 'ЛУНА', forbidden: ['ночь', 'светить', 'круглый', 'небо'] },
  {
    id: 18,
    difficulty: 'easy',
    word: 'СНЕГОВИК',
    forbidden: ['снег', 'зима', 'морковь', 'лепить'],
  },
  {
    id: 19,
    difficulty: 'easy',
    word: 'КЛЮЧ',
    forbidden: ['открыть', 'дверь', 'замок', 'потерять'],
  },
  {
    id: 20,
    difficulty: 'easy',
    word: 'ТЕЛЕФОН',
    forbidden: ['звонить', 'экран', 'заряд', 'позвонить'],
  },
  {
    id: 21,
    difficulty: 'easy',
    word: 'КОМПЬЮТЕР',
    forbidden: ['клавиатура', 'мышь', 'экран', 'программа'],
  },
  {
    id: 22,
    difficulty: 'easy',
    word: 'СТОЛ',
    forbidden: ['стул', 'есть', 'поверхность', 'мебель'],
  },
  {
    id: 23,
    difficulty: 'easy',
    word: 'КРОВАТЬ',
    forbidden: ['спать', 'подушка', 'мебель', 'одеяло'],
  },
  {
    id: 24,
    difficulty: 'easy',
    word: 'БАНАН',
    forbidden: ['жёлтый', 'тропики', 'обезьяна', 'фрукт'],
  },
  { id: 25, difficulty: 'easy', word: 'ПИЦЦА', forbidden: ['тесто', 'сыр', 'Италия', 'томат'] },
  {
    id: 26,
    difficulty: 'easy',
    word: 'КОРОВА',
    forbidden: ['молоко', 'мычать', 'ферма', 'животное'],
  },
  {
    id: 27,
    difficulty: 'easy',
    word: 'ПОЕЗД',
    forbidden: ['рельсы', 'вагон', 'локомотив', 'станция'],
  },
  {
    id: 28,
    difficulty: 'easy',
    word: 'ГИТАРА',
    forbidden: ['струна', 'играть', 'музыка', 'инструмент'],
  },
  {
    id: 29,
    difficulty: 'easy',
    word: 'ВРАЧ',
    forbidden: ['больница', 'лечить', 'таблетка', 'доктор'],
  },
  { id: 30, difficulty: 'easy', word: 'ДОЖДЬ', forbidden: ['зонт', 'лужа', 'облако', 'капля'] },
];

// ─── Medium ────────────────────────────────────────────────────────────────────
// Умеренно сложные слова, 5 запрещённых
const MEDIUM: TabooClassicCard[] = [
  {
    id: 31,
    difficulty: 'medium',
    word: 'ВУЛКАН',
    forbidden: ['лава', 'гора', 'извержение', 'огонь', 'взрыв'],
  },
  {
    id: 32,
    difficulty: 'medium',
    word: 'АКУЛА',
    forbidden: ['рыба', 'зуб', 'море', 'кусать', 'плавник'],
  },
  {
    id: 33,
    difficulty: 'medium',
    word: 'МАЯК',
    forbidden: ['море', 'свет', 'берег', 'корабль', 'башня'],
  },
  {
    id: 34,
    difficulty: 'medium',
    word: 'СКРИПКА',
    forbidden: ['смычок', 'струны', 'оркестр', 'музыка', 'играть'],
  },
  {
    id: 35,
    difficulty: 'medium',
    word: 'КАКТУС',
    forbidden: ['пустыня', 'колючка', 'растение', 'засуха', 'игла'],
  },
  {
    id: 36,
    difficulty: 'medium',
    word: 'ДЕТЕКТИВ',
    forbidden: ['расследование', 'преступник', 'улика', 'полиция', 'следствие'],
  },
  {
    id: 37,
    difficulty: 'medium',
    word: 'АЭРОПОРТ',
    forbidden: ['самолёт', 'вылет', 'терминал', 'чемодан', 'рейс'],
  },
  {
    id: 38,
    difficulty: 'medium',
    word: 'ДЕЛЬФИН',
    forbidden: ['море', 'умный', 'прыжок', 'млекопитающее', 'плавать'],
  },
  {
    id: 39,
    difficulty: 'medium',
    word: 'ПИРАМИДА',
    forbidden: ['Египет', 'фараон', 'треугольник', 'строить', 'древний'],
  },
  {
    id: 40,
    difficulty: 'medium',
    word: 'ПАРАШЮТ',
    forbidden: ['прыжок', 'купол', 'самолёт', 'падать', 'небо'],
  },
  {
    id: 41,
    difficulty: 'medium',
    word: 'КАРНАВАЛ',
    forbidden: ['маска', 'костюм', 'праздник', 'танцевать', 'Венеция'],
  },
  {
    id: 42,
    difficulty: 'medium',
    word: 'ТЕРМОМЕТР',
    forbidden: ['температура', 'измерять', 'болезнь', 'градус', 'жара'],
  },
  {
    id: 43,
    difficulty: 'medium',
    word: 'ОЛЕНЬ',
    forbidden: ['рога', 'лес', 'животное', 'Новый год', 'Санта'],
  },
  {
    id: 44,
    difficulty: 'medium',
    word: 'ЛАБИРИНТ',
    forbidden: ['запутать', 'выход', 'стена', 'ход', 'заблудиться'],
  },
  {
    id: 45,
    difficulty: 'medium',
    word: 'ПАСПОРТ',
    forbidden: ['документ', 'граница', 'виза', 'фото', 'удостоверение'],
  },
  {
    id: 46,
    difficulty: 'medium',
    word: 'ДИРИЖЁР',
    forbidden: ['оркестр', 'палочка', 'музыка', 'концерт', 'управлять'],
  },
  {
    id: 47,
    difficulty: 'medium',
    word: 'ЭКВАТОР',
    forbidden: ['жара', 'линия', 'земля', 'Африка', 'тропик'],
  },
  {
    id: 48,
    difficulty: 'medium',
    word: 'ПЕЩЕРА',
    forbidden: ['тёмный', 'камень', 'подземный', 'вход', 'летучая мышь'],
  },
  {
    id: 49,
    difficulty: 'medium',
    word: 'ШТРАФ',
    forbidden: ['нарушение', 'платить', 'полиция', 'правило', 'наказание'],
  },
  {
    id: 50,
    difficulty: 'medium',
    word: 'АУКЦИОН',
    forbidden: ['торги', 'цена', 'ставка', 'продавать', 'молоток'],
  },
  {
    id: 51,
    difficulty: 'medium',
    word: 'ГЕЙЗЕР',
    forbidden: ['вода', 'горячий', 'фонтан', 'пар', 'Исландия'],
  },
  {
    id: 52,
    difficulty: 'medium',
    word: 'ПРИЛИВ',
    forbidden: ['море', 'волна', 'луна', 'вода', 'берег'],
  },
  {
    id: 53,
    difficulty: 'medium',
    word: 'ТЕЛЕСКОП',
    forbidden: ['смотреть', 'звезда', 'увеличить', 'астроном', 'небо'],
  },
  {
    id: 54,
    difficulty: 'medium',
    word: 'КАНИКУЛЫ',
    forbidden: ['отдых', 'школа', 'лето', 'свободный', 'отпуск'],
  },
  {
    id: 55,
    difficulty: 'medium',
    word: 'СИРЕНА',
    forbidden: ['звук', 'полиция', 'скорая', 'вой', 'сигнал'],
  },
  {
    id: 56,
    difficulty: 'medium',
    word: 'ЖЮРИ',
    forbidden: ['суд', 'решение', 'судить', 'конкурс', 'голосование'],
  },
  {
    id: 57,
    difficulty: 'medium',
    word: 'ЯКОРЬ',
    forbidden: ['корабль', 'море', 'держать', 'дно', 'цепь'],
  },
  {
    id: 58,
    difficulty: 'medium',
    word: 'ТРАМВАЙ',
    forbidden: ['рельсы', 'город', 'ехать', 'вагон', 'электричество'],
  },
  {
    id: 59,
    difficulty: 'medium',
    word: 'ЧЕМПИОН',
    forbidden: ['победить', 'первый', 'соревнование', 'приз', 'титул'],
  },
  {
    id: 60,
    difficulty: 'medium',
    word: 'КАРАНТИН',
    forbidden: ['болезнь', 'изоляция', 'запрет', 'вирус', 'сидеть дома'],
  },
  { id: 191, difficulty: 'medium', word: 'БУМЕРАНГ', forbidden: ['бросать', 'возвращается', 'Австралия', 'лететь', 'оружие'] },
  { id: 192, difficulty: 'medium', word: 'АЙСБЕРГ', forbidden: ['лёд', 'океан', 'Титаник', 'холод', 'плавать'] },
  { id: 193, difficulty: 'medium', word: 'КОМПАС', forbidden: ['север', 'стрелка', 'направление', 'карта', 'магнит'] },
  { id: 194, difficulty: 'medium', word: 'БИНОКЛЬ', forbidden: ['смотреть', 'увеличение', 'линза', 'далеко', 'глаза'] },
  { id: 195, difficulty: 'medium', word: 'КАМИН', forbidden: ['огонь', 'дрова', 'тепло', 'дым', 'дом'] },
  { id: 196, difficulty: 'medium', word: 'ШАХТА', forbidden: ['уголь', 'земля', 'рудник', 'шахтёр', 'подземный'] },
  { id: 197, difficulty: 'medium', word: 'ЭСКАЛАТОР', forbidden: ['лестница', 'движется', 'метро', 'ступеньки', 'подниматься'] },
  { id: 198, difficulty: 'medium', word: 'ТУННЕЛЬ', forbidden: ['подземный', 'проход', 'гора', 'дорога', 'поезд'] },
  { id: 199, difficulty: 'medium', word: 'ОАЗИС', forbidden: ['пустыня', 'вода', 'пальмы', 'песок', 'зелень'] },
  { id: 200, difficulty: 'medium', word: 'ФАКЕЛ', forbidden: ['огонь', 'нести', 'пламя', 'дерево', 'свет'] },

  { id: 201, difficulty: 'medium', word: 'КАПКАН', forbidden: ['ловушка', 'охота', 'животное', 'поймать', 'металл'] },
  { id: 202, difficulty: 'medium', word: 'КАЛЕНДАРЬ', forbidden: ['дата', 'месяц', 'год', 'день', 'число'] },
  { id: 203, difficulty: 'medium', word: 'ПИНГВИН', forbidden: ['Антарктида', 'птица', 'лёд', 'чёрный', 'не летает'] },
  { id: 204, difficulty: 'medium', word: 'МЕТЕОРИТ', forbidden: ['космос', 'камень', 'падать', 'земля', 'астероид'] },
  { id: 205, difficulty: 'medium', word: 'ФОНТАН', forbidden: ['вода', 'струя', 'парк', 'брызги', 'площадь'] },
  { id: 206, difficulty: 'medium', word: 'СВЕТОФОР', forbidden: ['дорога', 'красный', 'зелёный', 'машины', 'сигнал'] },
  { id: 207, difficulty: 'medium', word: 'БАТУТ', forbidden: ['прыгать', 'сетка', 'вверх', 'дети', 'резина'] },
  { id: 208, difficulty: 'medium', word: 'КАМУФЛЯЖ', forbidden: ['армия', 'маскировка', 'зелёный', 'форма', 'прятаться'] },
  { id: 209, difficulty: 'medium', word: 'МИКРОФОН', forbidden: ['звук', 'петь', 'голос', 'говорить', 'сцена'] },
  { id: 210, difficulty: 'medium', word: 'СКАФАНДР', forbidden: ['космос', 'астронавт', 'шлем', 'костюм', 'луна'] },

  { id: 211, difficulty: 'medium', word: 'ДИНОЗАВР', forbidden: ['древний', 'ящер', 'вымер', 'тираннозавр', 'палеонтология'] },
  { id: 213, difficulty: 'medium', word: 'ПАЛАТКА', forbidden: ['туризм', 'лес', 'ночёвка', 'лагерь', 'ткань'] },
  { id: 214, difficulty: 'medium', word: 'ГАМАК', forbidden: ['лежать', 'деревья', 'отдых', 'верёвка', 'качаться'] },
  { id: 215, difficulty: 'medium', word: 'МАЯТНИК', forbidden: ['часы', 'качаться', 'движение', 'груз', 'верёвка'] },
  { id: 216, difficulty: 'medium', word: 'КАТАПУЛЬТА', forbidden: ['бросать', 'камень', 'оружие', 'средневековье', 'осада'] },
  { id: 217, difficulty: 'medium', word: 'АРЕНА', forbidden: ['цирк', 'стадион', 'бой', 'зрители', 'выступление'] },
  { id: 218, difficulty: 'medium', word: 'КОКОН', forbidden: ['бабочка', 'гусеница', 'шелк', 'насекомое', 'превращение'] },
  { id: 219, difficulty: 'medium', word: 'МЕДУЗА', forbidden: ['море', 'щупальца', 'жалить', 'прозрачная', 'плавать'] },
  { id: 220, difficulty: 'medium', word: 'ПЕЛИКАН', forbidden: ['птица', 'клюв', 'рыба', 'мешок', 'летать'] },

  { id: 221, difficulty: 'medium', word: 'ПРОЖЕКТОР', forbidden: ['свет', 'яркий', 'сцена', 'лампа', 'луч'] },
  { id: 222, difficulty: 'medium', word: 'БАРОМЕТР', forbidden: ['давление', 'погода', 'измерять', 'воздух', 'прибор'] },
  { id: 223, difficulty: 'medium', word: 'БУДИЛЬНИК', forbidden: ['утро', 'проснуться', 'часы', 'звонок', 'сон'] },
  { id: 224, difficulty: 'medium', word: 'ФЕЙЕРВЕРК', forbidden: ['салют', 'взрыв', 'небо', 'огни', 'праздник'] },
  { id: 225, difficulty: 'medium', word: 'ГОНДОЛА', forbidden: ['Венеция', 'лодка', 'канал', 'вода', 'гондольер'] },
  { id: 226, difficulty: 'medium', word: 'ДЖУНГЛИ', forbidden: ['лес', 'тропики', 'лианы', 'обезьяны', 'густой'] },
  { id: 227, difficulty: 'medium', word: 'КОЛИБРИ', forbidden: ['птица', 'маленькая', 'цветок', 'крылья', 'нектар'] },
  { id: 228, difficulty: 'medium', word: 'РАДУГА', forbidden: ['цвета', 'дождь', 'небо', 'дуга', 'солнце'] },
  { id: 229, difficulty: 'medium', word: 'ПРИЗМА', forbidden: ['стекло', 'свет', 'цвета', 'треугольник', 'оптика'] },
  { id: 230, difficulty: 'medium', word: 'КАРУСЕЛЬ', forbidden: ['аттракцион', 'крутиться', 'лошадки', 'парк', 'дети'] },

  { id: 231, difficulty: 'medium', word: 'ЛАВИНА', forbidden: ['снег', 'гора', 'сходить', 'зима', 'опасность'] },
  { id: 232, difficulty: 'medium', word: 'МИРАЖ', forbidden: ['пустыня', 'иллюзия', 'видеть', 'жара', 'обман'] },
  { id: 233, difficulty: 'medium', word: 'РОБОТ', forbidden: ['машина', 'андроид', 'программа', 'железо', 'автомат'] },
  { id: 234, difficulty: 'medium', word: 'СЕКУНДОМЕР', forbidden: ['время', 'измерять', 'спорт', 'секунда', 'часы'] },
  { id: 235, difficulty: 'medium', word: 'ШЛЮПКА', forbidden: ['лодка', 'корабль', 'спасательная', 'вода', 'море'] },
  { id: 236, difficulty: 'medium', word: 'КОРОНА', forbidden: ['король', 'голова', 'золото', 'монарх', 'трон'] },
  { id: 237, difficulty: 'medium', word: 'МОЛНИЯ', forbidden: ['гроза', 'небо', 'электричество', 'гром', 'разряд'] },
  { id: 238, difficulty: 'medium', word: 'ШТОРМ', forbidden: ['море', 'ветер', 'волны', 'буря', 'корабль'] },
  { id: 239, difficulty: 'medium', word: 'ПЕСКИ', forbidden: ['пустыня', 'барханы', 'жёлтый', 'сыпучий', 'жара'] },
  { id: 240, difficulty: 'medium', word: 'ГЛОБУС', forbidden: ['земля', 'карта', 'шар', 'страны', 'география'] },

  { id: 241, difficulty: 'medium', word: 'ПАЗЛ', forbidden: ['картинка', 'кусочки', 'собирать', 'игра', 'деталь'] },
  { id: 242, difficulty: 'medium', word: 'ПЕСКОЧНЫЕ ЧАСЫ', forbidden: ['время', 'песок', 'перевернуть', 'колба', 'измерять'] },
  { id: 243, difficulty: 'medium', word: 'КЛАД', forbidden: ['сокровища', 'сундук', 'пираты', 'золото', 'копать'] },
  { id: 244, difficulty: 'medium', word: 'РУЛЕТКА', forbidden: ['измерять', 'лента', 'метр', 'строитель', 'длина'] },
  { id: 245, difficulty: 'medium', word: 'ШТАТИВ', forbidden: ['камера', 'фото', 'ножки', 'устойчивость', 'снимать'] },
  { id: 246, difficulty: 'medium', word: 'ПОДВОДНАЯ ЛОДКА', forbidden: ['море', 'погружаться', 'субмарина', 'военная', 'глубина'] },
  { id: 247, difficulty: 'medium', word: 'КОНВЕРТ', forbidden: ['письмо', 'почта', 'бумага', 'марка', 'отправить'] },
  { id: 248, difficulty: 'medium', word: 'ШИФР', forbidden: ['код', 'секрет', 'зашифровать', 'символы', 'сообщение'] },
  { id: 249, difficulty: 'medium', word: 'МАГНИТ', forbidden: ['железо', 'притягивать', 'металл', 'полюс', 'холодильник'] },
  { id: 250, difficulty: 'medium', word: 'ОПЕРА', forbidden: ['театр', 'петь', 'музыка', 'ария', 'сцена'] },

  { id: 251, difficulty: 'medium', word: 'ТАЙФУН', forbidden: ['ветер', 'буря', 'ураган', 'океан', 'шторм'] },
  { id: 252, difficulty: 'medium', word: 'КАНОЭ', forbidden: ['лодка', 'весло', 'река', 'спорт', 'вода'] },
  { id: 253, difficulty: 'medium', word: 'ЛИНКОР', forbidden: ['корабль', 'военный', 'пушка', 'флот', 'море'] },
  { id: 254, difficulty: 'medium', word: 'ПОРТАЛ', forbidden: ['дверь', 'переход', 'мир', 'пространство', 'телепортация'] },
  { id: 255, difficulty: 'medium', word: 'РИФ', forbidden: ['кораллы', 'море', 'корабль', 'подводный', 'океан'] },
  { id: 256, difficulty: 'medium', word: 'САЛЮТ', forbidden: ['фейерверк', 'праздник', 'огни', 'небо', 'взрыв'] },
  { id: 257, difficulty: 'medium', word: 'ТОРНАДО', forbidden: ['ветер', 'воронка', 'ураган', 'разрушение', 'смерч'] },
  { id: 258, difficulty: 'medium', word: 'ФЛАГ', forbidden: ['страна', 'полотно', 'цвета', 'символ', 'древко'] },
  { id: 259, difficulty: 'medium', word: 'ЧЕРНИЛА', forbidden: ['ручка', 'писать', 'жидкость', 'синий', 'перо'] },
  { id: 260, difficulty: 'medium', word: 'ЭМБЛЕМА', forbidden: ['логотип', 'символ', 'герб', 'значок', 'изображение'] },

  { id: 261, difficulty: 'medium', word: 'ЯХТА', forbidden: ['лодка', 'парус', 'море', 'богатый', 'корабль'] },
  { id: 262, difficulty: 'medium', word: 'ПАРУС', forbidden: ['ветер', 'лодка', 'корабль', 'мачта', 'море'] },
  { id: 263, difficulty: 'medium', word: 'БАЛКОН', forbidden: ['дом', 'окно', 'квартира', 'выход', 'этаж'] },
  { id: 264, difficulty: 'medium', word: 'КУПОЛ', forbidden: ['крыша', 'церковь', 'полусфера', 'здание', 'верх'] },
  { id: 265, difficulty: 'medium', word: 'ОБЕЛИСК', forbidden: ['памятник', 'камень', 'высокий', 'монумент', 'город'] },
  { id: 266, difficulty: 'medium', word: 'ВОДОПАД', forbidden: ['река', 'падать', 'вода', 'скала', 'поток'] },
  { id: 267, difficulty: 'medium', word: 'ДАМБА', forbidden: ['вода', 'река', 'плотина', 'перекрывать', 'строение'] },
  { id: 268, difficulty: 'medium', word: 'КОРИДОР', forbidden: ['проход', 'дверь', 'дом', 'длинный', 'комната'] },
  { id: 269, difficulty: 'medium', word: 'ТРАП', forbidden: ['самолёт', 'лестница', 'корабль', 'подниматься', 'вход'] },
  { id: 270, difficulty: 'medium', word: 'ЦУНАМИ', forbidden: ['волна', 'океан', 'землетрясение', 'вода', 'берег'] },

  { id: 271, difficulty: 'medium', word: 'ПОДЗОРНАЯ ТРУБА', forbidden: ['пират', 'смотреть', 'увеличение', 'корабль', 'далеко'] },
  { id: 272, difficulty: 'medium', word: 'АМФИТЕАТР', forbidden: ['театр', 'арена', 'античность', 'зрители', 'ступени'] },
  { id: 273, difficulty: 'medium', word: 'ГАРПУН', forbidden: ['копьё', 'кит', 'охота', 'море', 'бросать'] },
  { id: 274, difficulty: 'medium', word: 'КАЛЕЙДОСКОП', forbidden: ['узоры', 'цветной', 'трубка', 'стекло', 'смотреть'] },
  { id: 275, difficulty: 'medium', word: 'ЛАБОРАТОРИЯ', forbidden: ['опыты', 'учёный', 'наука', 'реактивы', 'исследование'] },
  { id: 276, difficulty: 'medium', word: 'МАНЕКЕН', forbidden: ['магазин', 'одежда', 'витрина', 'человек', 'пластик'] },
  { id: 277, difficulty: 'medium', word: 'НЕБОСКРЁБ', forbidden: ['высокий', 'здание', 'этаж', 'город', 'офис'] },
  { id: 278, difficulty: 'medium', word: 'ПАРОМ', forbidden: ['корабль', 'машины', 'переправа', 'река', 'море'] },
  { id: 279, difficulty: 'medium', word: 'СЕЙФ', forbidden: ['деньги', 'замок', 'ценности', 'металл', 'код'] },
  { id: 280, difficulty: 'medium', word: 'ТЕЛЕЖКА', forbidden: ['магазин', 'колёса', 'покупки', 'катить', 'корзина'] },

  { id: 281, difficulty: 'medium', word: 'УЛЕЙ', forbidden: ['пчёлы', 'мёд', 'соты', 'рой', 'насекомые'] },
  { id: 282, difficulty: 'medium', word: 'ФЬОРД', forbidden: ['Норвегия', 'залив', 'скалы', 'море', 'берег'] },
  { id: 283, difficulty: 'medium', word: 'ЦИРКУЛЬ', forbidden: ['круг', 'чертить', 'геометрия', 'карандаш', 'ножки'] },
  { id: 284, difficulty: 'medium', word: 'ШАТЁР', forbidden: ['палатка', 'цирк', 'ткань', 'купол', 'временный'] },
  { id: 285, difficulty: 'medium', word: 'ЭХО', forbidden: ['звук', 'горы', 'отражение', 'крик', 'повтор'] },
  { id: 286, difficulty: 'medium', word: 'ЯНТАРЬ', forbidden: ['смола', 'камень', 'жёлтый', 'украшение', 'ископаемое'] },
  { id: 287, difficulty: 'medium', word: 'ВЕРФЬ', forbidden: ['корабль', 'строить', 'порт', 'судно', 'док'] },
  { id: 288, difficulty: 'medium', word: 'ГИЛЬОТИНА', forbidden: ['казнь', 'Франция', 'лезвие', 'революция', 'голова'] },
  { id: 289, difficulty: 'medium', word: 'ДИРИЖАБЛЬ', forbidden: ['воздух', 'летать', 'аэростат', 'газ', 'небо'] },
  { id: 290, difficulty: 'medium', word: 'ЗАТМЕНИЕ', forbidden: ['луна', 'солнце', 'астрономия', 'небо', 'тень'] },
  { id: 291, difficulty: 'medium', word: 'АКВАРИУМ', forbidden: ['рыбы', 'вода', 'стекло', 'плавать', 'дом'] },
  { id: 292, difficulty: 'medium', word: 'АЛЬБОМ', forbidden: ['фото', 'страницы', 'книга', 'снимки', 'листать'] },
  { id: 293, difficulty: 'medium', word: 'АНТЕННА', forbidden: ['сигнал', 'телевизор', 'радио', 'ловить', 'вышка'] },
  { id: 294, difficulty: 'medium', word: 'АРБАЛЕТ', forbidden: ['стрела', 'оружие', 'тетива', 'стрелять', 'лук'] },
  { id: 295, difficulty: 'medium', word: 'АТЛАС', forbidden: ['карты', 'география', 'страны', 'книга', 'континенты'] },
  { id: 296, difficulty: 'medium', word: 'БАЯН', forbidden: ['гармошка', 'музыка', 'кнопки', 'играть', 'инструмент'] },
  { id: 297, difficulty: 'medium', word: 'БЕЛКА', forbidden: ['орех', 'дерево', 'хвост', 'лес', 'рыжая'] },
  { id: 298, difficulty: 'medium', word: 'БОБЁР', forbidden: ['плотина', 'дерево', 'река', 'грызть', 'животное'] },
  { id: 299, difficulty: 'medium', word: 'БУФЕТ', forbidden: ['шкаф', 'посуда', 'кухня', 'тарелки', 'мебель'] },
  { id: 300, difficulty: 'medium', word: 'ВАЗА', forbidden: ['цветы', 'стекло', 'букет', 'ставить', 'декор'] },

  { id: 301, difficulty: 'medium', word: 'ВЕРБЛЮД', forbidden: ['пустыня', 'горб', 'песок', 'животное', 'караван'] },
  { id: 302, difficulty: 'medium', word: 'ВЕСЛО', forbidden: ['лодка', 'грести', 'вода', 'река', 'каноэ'] },
  { id: 303, difficulty: 'medium', word: 'ВИОЛОНЧЕЛЬ', forbidden: ['струны', 'смычок', 'оркестр', 'музыка', 'инструмент'] },
  { id: 304, difficulty: 'medium', word: 'ВОРОНКА', forbidden: ['лить', 'жидкость', 'кухня', 'узкая', 'форма'] },
  { id: 305, difficulty: 'medium', word: 'ГАЗЕТА', forbidden: ['новости', 'бумага', 'читать', 'статья', 'печать'] },
  { id: 306, difficulty: 'medium', word: 'ГЕПАРД', forbidden: ['быстрый', 'кошка', 'Африка', 'хищник', 'пятна'] },
  { id: 307, difficulty: 'medium', word: 'ГИРЯ', forbidden: ['спорт', 'вес', 'железо', 'поднимать', 'тренировка'] },
  { id: 308, difficulty: 'medium', word: 'ГОНГ', forbidden: ['удар', 'звук', 'металл', 'музыка', 'молоток'] },
  { id: 309, difficulty: 'medium', word: 'ГРАДУСНИК', forbidden: ['температура', 'болезнь', 'ртуть', 'измерять', 'жар'] },
  { id: 310, difficulty: 'medium', word: 'ГРИБ', forbidden: ['лес', 'шляпка', 'ножка', 'собирать', 'съедобный'] },

  { id: 311, difficulty: 'medium', word: 'ДВОРЕЦ', forbidden: ['король', 'замок', 'богатый', 'здание', 'монарх'] },
  { id: 312, difficulty: 'medium', word: 'ДОМКРАТ', forbidden: ['машина', 'поднимать', 'колесо', 'ремонт', 'авто'] },
  { id: 313, difficulty: 'medium', word: 'ДОСКА', forbidden: ['дерево', 'поверхность', 'писать', 'школа', 'мел'] },
  { id: 314, difficulty: 'medium', word: 'ЖЕМЧУГ', forbidden: ['раковина', 'море', 'бусы', 'белый', 'украшение'] },
  { id: 315, difficulty: 'medium', word: 'ЖИРАФ', forbidden: ['шея', 'Африка', 'животное', 'пятна', 'высокий'] },
  { id: 316, difficulty: 'medium', word: 'ЖУРНАЛ', forbidden: ['читать', 'страницы', 'обложка', 'статья', 'глянец'] },
  { id: 317, difficulty: 'medium', word: 'ЗАМОК', forbidden: ['рыцарь', 'крепость', 'башня', 'король', 'средневековье'] },
  { id: 318, difficulty: 'medium', word: 'ЗЕРКАЛО', forbidden: ['отражение', 'смотреть', 'стекло', 'лицо', 'ванная'] },
  { id: 319, difficulty: 'medium', word: 'ЗМЕЙ', forbidden: ['воздушный', 'ветер', 'нитка', 'летать', 'небо'] },
  { id: 320, difficulty: 'medium', word: 'ИГЛУ', forbidden: ['снег', 'эскимос', 'дом', 'лед', 'Арктика'] },

  { id: 321, difficulty: 'medium', word: 'ИНКУБАТОР', forbidden: ['цыплёнок', 'яйцо', 'тепло', 'ферма', 'выводить'] },
  { id: 322, difficulty: 'medium', word: 'КАБИНЕТ', forbidden: ['офис', 'комната', 'работа', 'стол', 'врач'] },
  { id: 323, difficulty: 'medium', word: 'КАПИТАН', forbidden: ['корабль', 'команда', 'моряк', 'руководить', 'море'] },
  { id: 324, difficulty: 'medium', word: 'КАСКА', forbidden: ['строитель', 'голова', 'защита', 'шлем', 'безопасность'] },
  { id: 325, difficulty: 'medium', word: 'КЕНГУРУ', forbidden: ['Австралия', 'сумка', 'прыгать', 'детёныш', 'животное'] },
  { id: 326, difficulty: 'medium', word: 'КИСТЬ', forbidden: ['краска', 'рисовать', 'художник', 'щетина', 'полотно'] },
  { id: 327, difficulty: 'medium', word: 'КЛАДБИЩЕ', forbidden: ['могила', 'умерший', 'крест', 'кладбище', 'похороны'] },
  { id: 328, difficulty: 'medium', word: 'КЛЕТКА', forbidden: ['животное', 'прутья', 'зоопарк', 'птица', 'закрыть'] },
  { id: 329, difficulty: 'medium', word: 'КОЛОДЕЦ', forbidden: ['вода', 'ведро', 'деревня', 'глубокий', 'копать'] },
  { id: 330, difficulty: 'medium', word: 'КОФЕМОЛКА', forbidden: ['кофе', 'зерно', 'молоть', 'напиток', 'кухня'] },

  { id: 331, difficulty: 'medium', word: 'КРАН', forbidden: ['вода', 'кухня', 'открыть', 'раковина', 'течь'] },
  { id: 332, difficulty: 'medium', word: 'КРОТ', forbidden: ['земля', 'норы', 'слепой', 'животное', 'копать'] },
  { id: 333, difficulty: 'medium', word: 'КУПЕ', forbidden: ['поезд', 'вагон', 'дверь', 'пассажир', 'полка'] },
  { id: 334, difficulty: 'medium', word: 'ЛАМПА', forbidden: ['свет', 'лампочка', 'включить', 'настольная', 'освещение'] },
  { id: 335, difficulty: 'medium', word: 'ЛЕБЕДЬ', forbidden: ['птица', 'белый', 'озеро', 'шея', 'плавать'] },
  { id: 336, difficulty: 'medium', word: 'ЛЕСТНИЦА', forbidden: ['ступеньки', 'подниматься', 'этаж', 'вверх', 'спускаться'] },
  { id: 337, difficulty: 'medium', word: 'ЛИНЕЙКА', forbidden: ['измерять', 'школа', 'сантиметр', 'чертить', 'длина'] },
  { id: 338, difficulty: 'medium', word: 'ЛИФТ', forbidden: ['этаж', 'подниматься', 'кабина', 'кнопка', 'дом'] },
  { id: 339, difficulty: 'medium', word: 'ЛОПАТА', forbidden: ['копать', 'земля', 'сад', 'черенок', 'яма'] },
  { id: 340, difficulty: 'medium', word: 'ЛОСЬ', forbidden: ['рога', 'лес', 'животное', 'копыта', 'север'] },

  { id: 341, difficulty: 'medium', word: 'МАСКА', forbidden: ['лицо', 'скрывать', 'карнавал', 'надеть', 'театр'] },
  { id: 342, difficulty: 'medium', word: 'МАЯТНИК ФУКО', forbidden: ['земля', 'вращение', 'физика', 'эксперимент', 'шар'] },
  { id: 343, difficulty: 'medium', word: 'МЕЛ', forbidden: ['доска', 'писать', 'белый', 'школа', 'порошок'] },
  { id: 344, difficulty: 'medium', word: 'МЕТЛА', forbidden: ['мести', 'ведьма', 'уборка', 'пол', 'палка'] },
  { id: 345, difficulty: 'medium', word: 'МОЗАИКА', forbidden: ['кусочки', 'картинка', 'цветной', 'узор', 'собирать'] },
  { id: 346, difficulty: 'medium', word: 'МОРЖ', forbidden: ['бивни', 'лед', 'море', 'животное', 'Арктика'] },
  { id: 347, difficulty: 'medium', word: 'МУРАВЕЙНИК', forbidden: ['муравьи', 'насекомые', 'лес', 'куча', 'колония'] },
  { id: 348, difficulty: 'medium', word: 'МУФТА', forbidden: ['руки', 'зима', 'тепло', 'мех', 'одежда'] },
  { id: 349, difficulty: 'medium', word: 'НАКОВАЛЬНЯ', forbidden: ['кузнец', 'молот', 'железо', 'ковать', 'металл'] },
  { id: 350, difficulty: 'medium', word: 'НОЖНЫ', forbidden: ['меч', 'нож', 'хранить', 'оружие', 'чехол'] },

  { id: 351, difficulty: 'medium', word: 'ОРКЕСТР', forbidden: ['дирижёр', 'музыканты', 'концерт', 'инструменты', 'сцена'] },
  { id: 352, difficulty: 'medium', word: 'ПАЛЬМА', forbidden: ['тропики', 'кокос', 'дерево', 'пляж', 'листья'] },
  { id: 353, difficulty: 'medium', word: 'ПАРИК', forbidden: ['волосы', 'надеть', 'лысый', 'театр', 'причёска'] },
  { id: 354, difficulty: 'medium', word: 'ПАУТИНА', forbidden: ['паук', 'сеть', 'липкая', 'насекомые', 'нить'] },
  { id: 355, difficulty: 'medium', word: 'ПЕРЧАТКА', forbidden: ['рука', 'пальцы', 'зима', 'одежда', 'надеть'] },
  { id: 356, difficulty: 'medium', word: 'ПОДКОВА', forbidden: ['лошадь', 'удача', 'копыто', 'железо', 'кузнец'] },
  { id: 357, difficulty: 'medium', word: 'ПОПУГАЙ', forbidden: ['птица', 'говорить', 'клюв', 'перья', 'клетка'] },
  { id: 358, difficulty: 'medium', word: 'ПОРТРЕТ', forbidden: ['картина', 'лицо', 'художник', 'рисовать', 'человек'] },
  { id: 359, difficulty: 'medium', word: 'ПЫЛЕСОС', forbidden: ['уборка', 'пыль', 'всасывать', 'дом', 'пол'] },
  { id: 360, difficulty: 'medium', word: 'РАДУШКА', forbidden: ['глаз', 'цвет', 'зрачок', 'анатомия', 'видеть'] },

  { id: 361, difficulty: 'medium', word: 'РАКОВИНА', forbidden: ['умывальник', 'вода', 'ванная', 'кран', 'кухня'] },
  { id: 362, difficulty: 'medium', word: 'РОЯЛЬ', forbidden: ['пианино', 'клавиши', 'музыка', 'инструмент', 'концерт'] },
  { id: 363, difficulty: 'medium', word: 'РУКАВИЦА', forbidden: ['рука', 'варежка', 'зима', 'тепло', 'одежда'] },
  { id: 364, difficulty: 'medium', word: 'РЮКЗАК', forbidden: ['спина', 'лямки', 'поход', 'вещи', 'носить'] },
  { id: 365, difficulty: 'medium', word: 'САМОВАР', forbidden: ['чай', 'кипяток', 'Россия', 'металл', 'уголь'] },
  { id: 366, difficulty: 'medium', word: 'САНИ', forbidden: ['снег', 'зима', 'кататься', 'лошадь', 'полозья'] },
  { id: 367, difficulty: 'medium', word: 'СКВОРЕЧНИК', forbidden: ['птица', 'дерево', 'домик', 'гнездо', 'доски'] },
  { id: 368, difficulty: 'medium', word: 'СКРИП', forbidden: ['звук', 'дверь', 'пол', 'дерево', 'шум'] },
  { id: 369, difficulty: 'medium', word: 'СКУЛЬПТУРА', forbidden: ['камень', 'статуя', 'резьба', 'искусство', 'ваять'] },
  { id: 370, difficulty: 'medium', word: 'СУНДУК', forbidden: ['сокровища', 'ящик', 'крышка', 'дерево', 'хранить'] },

  { id: 371, difficulty: 'medium', word: 'ТАБУРЕТ', forbidden: ['сидеть', 'ножки', 'кухня', 'мебель', 'стул'] },
  { id: 372, difficulty: 'medium', word: 'ТАПОЧКИ', forbidden: ['дом', 'ноги', 'обувь', 'надеть', 'комната'] },
  { id: 373, difficulty: 'medium', word: 'ТЕРМОС', forbidden: ['горячий', 'напиток', 'сохранять', 'чай', 'колба'] },
  { id: 374, difficulty: 'medium', word: 'ТИСКИ', forbidden: ['зажимать', 'металл', 'верстак', 'инструмент', 'мастерская'] },
  { id: 375, difficulty: 'medium', word: 'ТРЕНОГА', forbidden: ['три', 'ножки', 'штатив', 'устойчивость', 'опора'] },
  { id: 376, difficulty: 'medium', word: 'ТРОН', forbidden: ['король', 'сидеть', 'дворец', 'монарх', 'кресло'] },
  { id: 377, difficulty: 'medium', word: 'УЛИТКА', forbidden: ['раковина', 'ползать', 'слизь', 'медленно', 'моллюск'] },
  { id: 378, difficulty: 'medium', word: 'ФЛЕЙТА', forbidden: ['духовой', 'музыка', 'играть', 'инструмент', 'свист'] },
  { id: 379, difficulty: 'medium', word: 'ФОРТОЧКА', forbidden: ['окно', 'открыть', 'воздух', 'проветрить', 'рама'] },
  { id: 380, difficulty: 'medium', word: 'ХАМЕЛЕОН', forbidden: ['цвет', 'ящерица', 'маскировка', 'язык', 'рептилия'] },

  { id: 381, difficulty: 'medium', word: 'ХИЖИНА', forbidden: ['дом', 'лес', 'дерево', 'маленький', 'изба'] },
  { id: 382, difficulty: 'medium', word: 'ХРУСТАЛЬ', forbidden: ['стекло', 'бокал', 'прозрачный', 'дорогой', 'посуда'] },
  { id: 383, difficulty: 'medium', word: 'ЦЕПЬ', forbidden: ['звенья', 'металл', 'замок', 'соединение', 'железо'] },
  { id: 384, difficulty: 'medium', word: 'ЧАЙКА', forbidden: ['птица', 'море', 'крылья', 'берег', 'летать'] },
  { id: 385, difficulty: 'medium', word: 'ЧЕМОДАН', forbidden: ['путешествие', 'багаж', 'ручка', 'колёса', 'вещи'] },
  { id: 386, difficulty: 'medium', word: 'ЧУГУН', forbidden: ['металл', 'сковорода', 'тяжёлый', 'литьё', 'железо'] },
  { id: 387, difficulty: 'medium', word: 'ШАХМАТЫ', forbidden: ['фигуры', 'король', 'доска', 'игра', 'мат'] },
  { id: 388, difficulty: 'medium', word: 'ШПИЛЬ', forbidden: ['башня', 'верх', 'острый', 'здание', 'крыша'] },
  { id: 389, difficulty: 'medium', word: 'ШТОПОР', forbidden: ['бутылка', 'пробка', 'открывать', 'вино', 'винт'] },
  { id: 390, difficulty: 'medium', word: 'ЯК', forbidden: ['животное', 'горы', 'шерсть', 'бык', 'Тибет'] },
  { id: 391, difficulty: 'medium', word: 'АБАЖУР', forbidden: ['лампа', 'свет', 'плафон', 'освещение', 'ткань'] },
  { id: 392, difficulty: 'medium', word: 'АЙВА', forbidden: ['фрукт', 'дерево', 'жёлтый', 'варенье', 'осень'] },
  { id: 393, difficulty: 'medium', word: 'АКРОБАТ', forbidden: ['цирк', 'трюк', 'гимнаст', 'кувырок', 'арена'] },
  { id: 394, difficulty: 'medium', word: 'АЛМАЗ', forbidden: ['бриллиант', 'камень', 'драгоценный', 'твёрдый', 'ювелир'] },
  { id: 395, difficulty: 'medium', word: 'АМБАР', forbidden: ['деревня', 'зерно', 'сарай', 'ферма', 'хранить'] },
  { id: 396, difficulty: 'medium', word: 'АРФА', forbidden: ['струны', 'музыка', 'инструмент', 'играть', 'оркестр'] },
  { id: 397, difficulty: 'medium', word: 'БАГАЖНИК', forbidden: ['машина', 'вещи', 'автомобиль', 'задний', 'груз'] },
  { id: 398, difficulty: 'medium', word: 'БАКЕН', forbidden: ['река', 'море', 'буй', 'судно', 'навигация'] },
  { id: 399, difficulty: 'medium', word: 'БАРХАН', forbidden: ['пустыня', 'песок', 'ветер', 'дюна', 'жара'] },
  { id: 400, difficulty: 'medium', word: 'БАШМАК', forbidden: ['обувь', 'нога', 'ботинок', 'носить', 'ступня'] },

  { id: 401, difficulty: 'medium', word: 'БИВЕНЬ', forbidden: ['слон', 'кость', 'мамонт', 'зуб', 'животное'] },
  { id: 402, difficulty: 'medium', word: 'БЛОКНОТ', forbidden: ['запись', 'бумага', 'тетрадь', 'лист', 'писать'] },
  { id: 403, difficulty: 'medium', word: 'БОЧКА', forbidden: ['дерево', 'вино', 'бочка', 'жидкость', 'круглая'] },
  { id: 404, difficulty: 'medium', word: 'БРОШЬ', forbidden: ['украшение', 'булавка', 'одежда', 'аксессуар', 'носить'] },
  { id: 405, difficulty: 'medium', word: 'БУЙ', forbidden: ['море', 'вода', 'плавать', 'навигация', 'бакен'] },
  { id: 406, difficulty: 'medium', word: 'БУФЕР', forbidden: ['смягчать', 'удар', 'защита', 'поезд', 'амортизация'] },
  { id: 407, difficulty: 'medium', word: 'ВАЛЕНОК', forbidden: ['зима', 'обувь', 'шерсть', 'мороз', 'сапог'] },
  { id: 408, difficulty: 'medium', word: 'ВЕНТИЛЯТОР', forbidden: ['воздух', 'лопасти', 'охлаждать', 'жара', 'дуть'] },
  { id: 409, difficulty: 'medium', word: 'ВЕРЕТЕНО', forbidden: ['нить', 'пряжа', 'прясть', 'рукоделие', 'дерево'] },
  { id: 410, difficulty: 'medium', word: 'ВЕСЫ', forbidden: ['масса', 'измерять', 'килограмм', 'взвешивать', 'стрелка'] },

  { id: 411, difficulty: 'medium', word: 'ВИТРАЖ', forbidden: ['стекло', 'цветной', 'окно', 'собор', 'узор'] },
  { id: 412, difficulty: 'medium', word: 'ВОЛЧОК', forbidden: ['игрушка', 'крутиться', 'дети', 'вращение', 'юла'] },
  { id: 413, difficulty: 'medium', word: 'ГАЛСТУК', forbidden: ['рубашка', 'шея', 'костюм', 'узел', 'одежда'] },
  { id: 414, difficulty: 'medium', word: 'ГАРДЕРОБ', forbidden: ['одежда', 'шкаф', 'вешалка', 'хранить', 'вещи'] },
  { id: 415, difficulty: 'medium', word: 'ГВОЗДЬ', forbidden: ['молоток', 'забивать', 'металл', 'дерево', 'острый'] },
  { id: 416, difficulty: 'medium', word: 'ГЛИНА', forbidden: ['горшок', 'лепить', 'керамика', 'земля', 'глина'] },
  { id: 417, difficulty: 'medium', word: 'ГНЕЗДО', forbidden: ['птица', 'яйца', 'дерево', 'ветки', 'птенцы'] },
  { id: 418, difficulty: 'medium', word: 'ГРАБЛИ', forbidden: ['сад', 'листья', 'зубья', 'земля', 'инструмент'] },
  { id: 419, difficulty: 'medium', word: 'ГРАНАТ', forbidden: ['фрукт', 'зерна', 'красный', 'кожура', 'сок'] },
  { id: 420, difficulty: 'medium', word: 'ГУСЛИ', forbidden: ['струны', 'музыка', 'инструмент', 'играть', 'народный'] },

  { id: 421, difficulty: 'medium', word: 'ДЕЛЬТА', forbidden: ['река', 'устье', 'рукава', 'география', 'море'] },
  { id: 422, difficulty: 'medium', word: 'ДЖОЙСТИК', forbidden: ['игра', 'контроллер', 'кнопки', 'консоль', 'управление'] },
  { id: 423, difficulty: 'medium', word: 'ДРОВОСЕК', forbidden: ['лес', 'топор', 'дерево', 'рубить', 'работа'] },
  { id: 424, difficulty: 'medium', word: 'ДУРШЛАГ', forbidden: ['кухня', 'макароны', 'дырки', 'вода', 'посуда'] },
  { id: 425, difficulty: 'medium', word: 'ДЫНЯ', forbidden: ['фрукт', 'жёлтая', 'бахча', 'сладкая', 'арбуз'] },
  { id: 426, difficulty: 'medium', word: 'ЕНОТ', forbidden: ['животное', 'полоски', 'хвост', 'лес', 'маска'] },
  { id: 427, difficulty: 'medium', word: 'ЖАЛЮЗИ', forbidden: ['окно', 'полоски', 'солнце', 'закрывать', 'шторы'] },
  { id: 428, difficulty: 'medium', word: 'ЖЕРНОВА', forbidden: ['мука', 'зерно', 'мельница', 'камень', 'молоть'] },
  { id: 429, difficulty: 'medium', word: 'ЖИЛЕТ', forbidden: ['одежда', 'безрукавка', 'костюм', 'надеть', 'пуговицы'] },
  { id: 430, difficulty: 'medium', word: 'ЖУРАВЛЬ', forbidden: ['птица', 'длинные ноги', 'болото', 'летать', 'клюв'] },

  { id: 431, difficulty: 'medium', word: 'ЗАПОНКИ', forbidden: ['рубашка', 'рукав', 'аксессуар', 'пуговицы', 'костюм'] },
  { id: 432, difficulty: 'medium', word: 'ЗОНД', forbidden: ['исследование', 'космос', 'аппарат', 'измерение', 'отправить'] },
  { id: 433, difficulty: 'medium', word: 'ЗУБИЛО', forbidden: ['молоток', 'камень', 'резать', 'металл', 'инструмент'] },
  { id: 434, difficulty: 'medium', word: 'ИВА', forbidden: ['дерево', 'ветки', 'река', 'плакучая', 'листья'] },
  { id: 435, difficulty: 'medium', word: 'ИНЕЙ', forbidden: ['мороз', 'белый', 'утро', 'ветки', 'лёд'] },
  { id: 436, difficulty: 'medium', word: 'КАДУШКА', forbidden: ['дерево', 'бочка', 'капуста', 'соленья', 'ёмкость'] },
  { id: 437, difficulty: 'medium', word: 'КАЙМА', forbidden: ['край', 'узор', 'ткань', 'одежда', 'граница'] },
  { id: 438, difficulty: 'medium', word: 'КАЛОШИ', forbidden: ['обувь', 'дождь', 'резина', 'лужи', 'ботинки'] },
  { id: 439, difficulty: 'medium', word: 'КАМЫШ', forbidden: ['болото', 'река', 'растение', 'берег', 'тростник'] },
  { id: 440, difficulty: 'medium', word: 'КАПЮШОН', forbidden: ['куртка', 'голова', 'одежда', 'дождь', 'надеть'] },

  { id: 441, difficulty: 'medium', word: 'КАРНИЗ', forbidden: ['шторы', 'окно', 'крепить', 'стена', 'потолок'] },
  { id: 442, difficulty: 'medium', word: 'КАШПО', forbidden: ['цветок', 'горшок', 'растение', 'декор', 'комната'] },
  { id: 443, difficulty: 'medium', word: 'КВАРЦ', forbidden: ['камень', 'минерал', 'кристалл', 'песок', 'часы'] },
  { id: 444, difficulty: 'medium', word: 'КЕРАМИКА', forbidden: ['глина', 'посуда', 'печь', 'изделие', 'обжиг'] },
  { id: 445, difficulty: 'medium', word: 'КИВИ', forbidden: ['фрукт', 'зелёный', 'волосатый', 'кислый', 'кожура'] },
  { id: 446, difficulty: 'medium', word: 'КИОСК', forbidden: ['газета', 'магазин', 'ларёк', 'улица', 'продавец'] },
  { id: 447, difficulty: 'medium', word: 'КИРКА', forbidden: ['шахта', 'копать', 'инструмент', 'камень', 'рабочий'] },
  { id: 448, difficulty: 'medium', word: 'КЛЕЩИ', forbidden: ['инструмент', 'сжимать', 'плоскогубцы', 'металл', 'ремонт'] },
  { id: 449, difficulty: 'medium', word: 'КОВШ', forbidden: ['экскаватор', 'лопата', 'металл', 'черпать', 'машина'] },
  { id: 450, difficulty: 'medium', word: 'КОЖУРА', forbidden: ['фрукт', 'очистить', 'банан', 'яблоко', 'кожица'] },
  { id: 451, difficulty: 'medium', word: 'ЛАВАНДА', forbidden: ['цветок', 'фиолетовый', 'запах', 'Прованс', 'французский'] },
  { id: 452, difficulty: 'medium', word: 'МАНЕКЕН', forbidden: ['одежда', 'магазин', 'витрина', 'пластик', 'кукла'] },
  { id: 453, difficulty: 'medium', word: 'МАСКАРАД', forbidden: ['костюм', 'маска', 'праздник', 'бал', 'танцы'] },
  { id: 454, difficulty: 'medium', word: 'МЕДАЛЬ', forbidden: ['золото', 'награда', 'спорт', 'место', 'орден'] },
  { id: 455, difficulty: 'medium', word: 'МОЛНИЯ', forbidden: ['гроза', 'гром', 'электричество', 'небо', 'дождь'] },
  { id: 456, difficulty: 'medium', word: 'МОНОПОЛИЯ', forbidden: ['игра', 'кубик', 'деньги', 'недвижимость', 'настольная'] },
  { id: 457, difficulty: 'medium', word: 'МОРЗЕ', forbidden: ['азбука', 'код', 'точка', 'тире', 'сигнал'] },
  { id: 458, difficulty: 'medium', word: 'НЕБОСКРЕБ', forbidden: ['здание', 'высокий', 'дом', 'этаж', 'город'] },
  { id: 459, difficulty: 'medium', word: 'НОТА', forbidden: ['музыка', 'песня', 'звук', 'пианино', 'скрипичный ключ'] },

  { id: 460, difficulty: 'medium', word: 'ОБЛАКО', forbidden: ['небо', 'белый', 'дождь', 'вата', 'пар'] },
  { id: 461, difficulty: 'medium', word: 'ОРАКУЛ', forbidden: ['предсказание', 'будущее', 'жрец', 'судьба', 'Греция'] },
  { id: 462, difficulty: 'medium', word: 'ОТКРЫТКА', forbidden: ['праздник', 'поздравление', 'письмо', 'почта', 'подарок'] },
  { id: 463, difficulty: 'medium', word: 'ОХОТНИК', forbidden: ['ружье', 'лес', 'добыча', 'животные', 'собака'] },
  { id: 464, difficulty: 'medium', word: 'ПАВЛИН', forbidden: ['хвост', 'птица', 'перья', 'яркий', 'красивый'] },
  { id: 465, difficulty: 'medium', word: 'ПАЛЬМА', forbidden: ['пляж', 'дерево', 'кокос', 'тропики', 'остров'] },
  { id: 466, difficulty: 'medium', word: 'ПАРКОВКА', forbidden: ['машина', 'место', 'стоянка', 'автомобиль', 'знак'] },
  { id: 467, difficulty: 'medium', word: 'ПАРУС', forbidden: ['ветер', 'лодка', 'корабль', 'море', 'мачта'] },
  { id: 468, difficulty: 'medium', word: 'ПАРФЮМ', forbidden: ['духи', 'запах', 'аромат', 'флакон', 'брызгать'] },
  { id: 469, difficulty: 'medium', word: 'ПАСПОРТ', forbidden: ['документ', 'гражданин', 'фото', 'граница', 'личность'] },

  { id: 470, difficulty: 'medium', word: 'ПАТРУЛЬ', forbidden: ['полиция', 'машина', 'город', 'охрана', 'улица'] },
  { id: 471, difficulty: 'medium', word: 'ПЕЛИКАН', forbidden: ['птица', 'клюв', 'мешок', 'рыба', 'рыболов'] },
  { id: 472, difficulty: 'medium', word: 'ПЕПЕЛ', forbidden: ['огонь', 'сигарета', 'костер', 'серый', 'вулкан'] },
  { id: 473, difficulty: 'medium', word: 'ПЕРИСКОП', forbidden: ['подводная лодка', 'смотреть', 'зеркало', 'вода', 'труба'] },
  { id: 474, difficulty: 'medium', word: 'ПЕРО', forbidden: ['птица', 'подушка', 'писать', 'чернила', 'крыло'] },
  { id: 475, difficulty: 'medium', word: 'ПЕСОЧНЫЕ ЧАСЫ', forbidden: ['время', 'песок', 'переворачивать', 'стекло', 'минута'] },
  { id: 476, difficulty: 'medium', word: 'ПИКНИК', forbidden: ['трава', 'еда', 'природа', 'корзина', 'плед'] },
  { id: 477, difficulty: 'medium', word: 'ПИНГВИН', forbidden: ['Антарктида', 'птица', 'холод', 'лед', 'фрак'] },
  { id: 478, difficulty: 'medium', word: 'ПИРАТ', forbidden: ['корабль', 'море', 'сундук', 'клад', 'попугай'] },
  { id: 479, difficulty: 'medium', word: 'ПЛАСТЫРЬ', forbidden: ['рана', 'кожа', 'аптечка', 'порез', 'клеить'] },

  { id: 480, difficulty: 'medium', word: 'ПЛОТИНА', forbidden: ['бобер', 'вода', 'река', 'ГЭС', 'строить'] },
  { id: 481, difficulty: 'medium', word: 'ПОДПИСКА', forbidden: ['журнал', 'сервис', 'деньги', 'месяц', 'онлайн'] },
  { id: 482, difficulty: 'medium', word: 'ПОЖАРНЫЙ', forbidden: ['огонь', 'вода', 'машина', 'тушить', 'сирена'] },
  { id: 483, difficulty: 'medium', word: 'ПОПКОРН', forbidden: ['кукуруза', 'кинотеатр', 'соленый', 'сладкий', 'ведро'] },
  { id: 485, difficulty: 'medium', word: 'ПОЧТАЛЬОН', forbidden: ['письмо', 'газета', 'сумка', 'ящик', 'доставка'] },
  { id: 486, difficulty: 'medium', word: 'РЕЖИССЕР', forbidden: ['кино', 'фильм', 'камера', 'актер', 'снимать'] },
  { id: 487, difficulty: 'medium', word: 'РЕЦЕПТ', forbidden: ['еда', 'готовка', 'блюдо', 'кухня', 'врач'] },
  { id: 489, difficulty: 'medium', word: 'САФАРИ', forbidden: ['Африка', 'животные', 'охота', 'джип', 'экскурсия'] },

  { id: 490, difficulty: 'medium', word: 'СЕЙФ', forbidden: ['деньги', 'замок', 'код', 'металл', 'взлом'] },
  { id: 491, difficulty: 'medium', word: 'СЕКУНДОМЕР', forbidden: ['время', 'спорт', 'бег', 'секунда', 'финиш'] },
  { id: 492, difficulty: 'medium', word: 'СИГНАЛИЗАЦИЯ', forbidden: ['машина', 'угон', 'звук', 'сирена', 'брелок'] },
  { id: 493, difficulty: 'medium', word: 'СКАФАНДР', forbidden: ['космос', 'космонавт', 'костюм', 'шлем', 'Луна'] },
  { id: 494, difficulty: 'medium', word: 'СКОРАЯ ПОМОЩЬ', forbidden: ['врач', 'больница', 'машина', 'сирена', 'вызов'] },
  { id: 495, difficulty: 'medium', word: 'СПУТНИК', forbidden: ['космос', 'Орбита', 'Земля', 'Луна', 'сигнал'] },
  { id: 496, difficulty: 'medium', word: 'СТАДИОН', forbidden: ['футбол', 'спорт', 'трибуна', 'бег', 'матч'] },
  { id: 497, difficulty: 'medium', word: 'СТюАРДЕССА', forbidden: ['самолет', 'полет', 'небо', 'форма', 'пассажир'] },
  { id: 498, difficulty: 'medium', word: 'СУФЛЕР', forbidden: ['театр', 'подсказывать', 'актер', 'текст', 'сцена'] },
  { id: 499, difficulty: 'medium', word: 'СУШИ', forbidden: ['рыба', 'рис', 'Япония', 'палочки', 'роллы'] }
];

// ─── Hard ──────────────────────────────────────────────────────────────────────
// Абстрактные и сложные слова, 5 запрещённых — самые ожидаемые пояснения под запретом
const HARD: TabooClassicCard[] = [
  {
    id: 61,
    difficulty: 'hard',
    word: 'СОВЕСТЬ',
    forbidden: ['чувство', 'поступок', 'вина', 'честность', 'душа'],
  },
  {
    id: 62,
    difficulty: 'hard',
    word: 'НОСТАЛЬГИЯ',
    forbidden: ['прошлое', 'воспоминание', 'грусть', 'детство', 'тоска'],
  },
  {
    id: 63,
    difficulty: 'hard',
    word: 'ГРАВИТАЦИЯ',
    forbidden: ['притяжение', 'падать', 'земля', 'сила', 'Ньютон'],
  },
  {
    id: 64,
    difficulty: 'hard',
    word: 'ИНФЛЯЦИЯ',
    forbidden: ['деньги', 'цены', 'расти', 'экономика', 'обесценить'],
  },
  {
    id: 65,
    difficulty: 'hard',
    word: 'ЭПИДЕМИЯ',
    forbidden: ['болезнь', 'распространять', 'вирус', 'заразный', 'массовый'],
  },
  {
    id: 66,
    difficulty: 'hard',
    word: 'МЕДИТАЦИЯ',
    forbidden: ['спокойствие', 'дыхание', 'расслабить', 'концентрация', 'йога'],
  },
  {
    id: 67,
    difficulty: 'hard',
    word: 'ЭМПАТИЯ',
    forbidden: ['сочувствие', 'понимать', 'чувствовать', 'другой', 'переживать'],
  },
  {
    id: 68,
    difficulty: 'hard',
    word: 'ИЛЛЮЗИЯ',
    forbidden: ['обман', 'видеть', 'настоящий', 'восприятие', 'фокус'],
  },
  {
    id: 69,
    difficulty: 'hard',
    word: 'РЕПУТАЦИЯ',
    forbidden: ['мнение', 'имя', 'доверие', 'образ', 'общество'],
  },
  {
    id: 70,
    difficulty: 'hard',
    word: 'ХАОС',
    forbidden: ['беспорядок', 'разрушение', 'паника', 'контроль', 'смешать'],
  },
  {
    id: 71,
    difficulty: 'hard',
    word: 'ПАРАДОКС',
    forbidden: ['противоречие', 'логика', 'невозможный', 'истина', 'загадка'],
  },
  {
    id: 72,
    difficulty: 'hard',
    word: 'МОНОПОЛИЯ',
    forbidden: ['игра', 'власть', 'рынок', 'контроль', 'один'],
  },
  {
    id: 73,
    difficulty: 'hard',
    word: 'ТАКТИКА',
    forbidden: ['план', 'стратегия', 'действие', 'игра', 'победить'],
  },
  {
    id: 74,
    difficulty: 'hard',
    word: 'ДИАЛЕКТ',
    forbidden: ['язык', 'говор', 'регион', 'речь', 'отличие'],
  },
  {
    id: 75,
    difficulty: 'hard',
    word: 'ФЕНОМЕН',
    forbidden: ['явление', 'необычный', 'природа', 'уникальный', 'наблюдать'],
  },
  {
    id: 76,
    difficulty: 'hard',
    word: 'КАТАЛИЗАТОР',
    forbidden: ['ускорять', 'реакция', 'химия', 'изменение', 'процесс'],
  },
  {
    id: 77,
    difficulty: 'hard',
    word: 'СУВЕРЕНИТЕТ',
    forbidden: ['государство', 'независимость', 'власть', 'страна', 'право'],
  },
  {
    id: 78,
    difficulty: 'hard',
    word: 'ИМПРОВИЗАЦИЯ',
    forbidden: ['спонтанный', 'подготовка', 'музыка', 'театр', 'сочинять'],
  },
  {
    id: 79,
    difficulty: 'hard',
    word: 'КОНСЕНСУС',
    forbidden: ['согласие', 'решение', 'группа', 'договориться', 'мнение'],
  },
  {
    id: 80,
    difficulty: 'hard',
    word: 'АРХИТЕКТУРА',
    forbidden: ['строить', 'здание', 'дизайн', 'проектировать', 'город'],
  },
  {
    id: 81,
    difficulty: 'hard',
    word: 'ХАРИЗМА',
    forbidden: ['личность', 'обаяние', 'привлекать', 'лидер', 'магнетизм'],
  },
  {
    id: 82,
    difficulty: 'hard',
    word: 'ПРОПАГАНДА',
    forbidden: ['информация', 'влиять', 'государство', 'СМИ', 'манипуляция'],
  },
  {
    id: 83,
    difficulty: 'hard',
    word: 'МЕТАФОРА',
    forbidden: ['сравнение', 'слово', 'литература', 'образ', 'язык'],
  },
  {
    id: 84,
    difficulty: 'hard',
    word: 'АВАНТЮРА',
    forbidden: ['риск', 'приключение', 'план', 'авантюрист', 'неизвестность'],
  },
  {
    id: 85,
    difficulty: 'hard',
    word: 'БЮРОКРАТИЯ',
    forbidden: ['чиновник', 'документ', 'бумага', 'государство', 'правило'],
  },
  {
    id: 86,
    difficulty: 'hard',
    word: 'ДЕГРАДАЦИЯ',
    forbidden: ['упадок', 'ухудшение', 'разрушать', 'падать', 'регресс'],
  },
  {
    id: 87,
    difficulty: 'hard',
    word: 'СТЕРЕОТИП',
    forbidden: ['предрассудок', 'мнение', 'группа', 'ярлык', 'убеждение'],
  },
  {
    id: 88,
    difficulty: 'hard',
    word: 'ЛОЯЛЬНОСТЬ',
    forbidden: ['верность', 'преданность', 'доверие', 'поддержка', 'слушаться'],
  },
  {
    id: 89,
    difficulty: 'hard',
    word: 'КОМПРОМИСС',
    forbidden: ['уступка', 'договор', 'обе стороны', 'решение', 'середина'],
  },
  {
    id: 90,
    difficulty: 'hard',
    word: 'ПРОКРАСТИНАЦИЯ',
    forbidden: ['откладывать', 'лень', 'потом', 'время', 'работа'],
  },
  {
    id: 91,
    difficulty: 'hard',
    word: 'АМБИЦИЯ',
    forbidden: ['цель', 'желание', 'успех', 'карьера', 'стремление'],
  },
  {
    id: 92,
    difficulty: 'hard',
    word: 'АЛГОРИТМ',
    forbidden: ['программа', 'последовательность', 'код', 'компьютер', 'шаг'],
  },
  {
    id: 93,
    difficulty: 'hard',
    word: 'АНАРХИЯ',
    forbidden: ['власть', 'хаос', 'государство', 'порядок', 'закон'],
  },
  {
    id: 94,
    difficulty: 'hard',
    word: 'АНОМАЛИЯ',
    forbidden: ['отклонение', 'необычный', 'норма', 'явление', 'исключение'],
  },
  {
    id: 95,
    difficulty: 'hard',
    word: 'АПАТИЯ',
    forbidden: ['безразличие', 'эмоции', 'желание', 'усталость', 'интерес'],
  },
  {
    id: 96,
    difficulty: 'hard',
    word: 'АРГУМЕНТ',
    forbidden: ['доказательство', 'спор', 'мнение', 'факт', 'убеждать'],
  },
  {
    id: 97,
    difficulty: 'hard',
    word: 'АССОЦИАЦИЯ',
    forbidden: ['связь', 'образ', 'мысль', 'память', 'слово'],
  },
  {
    id: 98,
    difficulty: 'hard',
    word: 'АТМОСФЕРА',
    forbidden: ['воздух', 'планета', 'небо', 'слой', 'земля'],
  },
  {
    id: 99,
    difficulty: 'hard',
    word: 'АУТЕНТИЧНОСТЬ',
    forbidden: ['подлинность', 'настоящий', 'оригинал', 'копия', 'истинный'],
  },
  {
    id: 100,
    difficulty: 'hard',
    word: 'БАЛАНС',
    forbidden: ['равновесие', 'весы', 'устойчивость', 'гармония', 'равный'],
  },
  {
    id: 101,
    difficulty: 'hard',
    word: 'БЕСКОНЕЧНОСТЬ',
    forbidden: ['вечность', 'конец', 'математика', 'безграничный', 'число'],
  },
  {
    id: 102,
    difficulty: 'hard',
    word: 'БЕСПРИСТРАСТНОСТЬ',
    forbidden: ['объективность', 'нейтральность', 'справедливость', 'предвзятость', 'судья'],
  },
  {
    id: 103,
    difficulty: 'hard',
    word: 'ВАКУУМ',
    forbidden: ['пустота', 'воздух', 'космос', 'давление', 'пространство'],
  },
  {
    id: 104,
    difficulty: 'hard',
    word: 'ВЕРОЯТНОСТЬ',
    forbidden: ['шанс', 'случайность', 'процент', 'математика', 'событие'],
  },
  {
    id: 105,
    difficulty: 'hard',
    word: 'ВИРТУАЛЬНОСТЬ',
    forbidden: ['компьютер', 'интернет', 'цифровой', 'реальность', 'VR'],
  },
  {
    id: 106,
    difficulty: 'hard',
    word: 'ВОЛАТИЛЬНОСТЬ',
    forbidden: ['рынок', 'изменение', 'цена', 'биржа', 'колебание'],
  },
  {
    id: 107,
    difficulty: 'hard',
    word: 'ВОСПРИЯТИЕ',
    forbidden: ['ощущение', 'чувство', 'видеть', 'понимание', 'мозг'],
  },
  {
    id: 108,
    difficulty: 'hard',
    word: 'ГАРМОНИЯ',
    forbidden: ['согласие', 'музыка', 'равновесие', 'красота', 'мир'],
  },
  {
    id: 109,
    difficulty: 'hard',
    word: 'ГЕНОЦИД',
    forbidden: ['народ', 'уничтожение', 'война', 'этнос', 'массовый'],
  },
  {
    id: 110,
    difficulty: 'hard',
    word: 'ГИПОТЕЗА',
    forbidden: ['предположение', 'теория', 'наука', 'проверка', 'доказать'],
  },
  {
    id: 111,
    difficulty: 'hard',
    word: 'ГЛОБАЛИЗАЦИЯ',
    forbidden: ['мир', 'страны', 'экономика', 'объединение', 'международный'],
  },
  {
    id: 112,
    difficulty: 'hard',
    word: 'ДЕМОКРАТИЯ',
    forbidden: ['народ', 'выборы', 'власть', 'голосование', 'государство'],
  },
  {
    id: 113,
    difficulty: 'hard',
    word: 'ДИЛЕММА',
    forbidden: ['выбор', 'проблема', 'решение', 'вариант', 'сложный'],
  },
  {
    id: 114,
    difficulty: 'hard',
    word: 'ДИСКРИМИНАЦИЯ',
    forbidden: ['неравенство', 'ущемление', 'права', 'предубеждение', 'отношение'],
  },
  {
    id: 115,
    difficulty: 'hard',
    word: 'ДОМИНО',
    forbidden: ['эффект', 'костяшка', 'цепочка', 'падение', 'игра'],
  },
  {
    id: 116,
    difficulty: 'hard',
    word: 'ДУАЛИЗМ',
    forbidden: ['двойственность', 'два', 'философия', 'противоположность', 'единство'],
  },
  {
    id: 117,
    difficulty: 'hard',
    word: 'ЕСТЕСТВЕННЫЙ ОТБОР',
    forbidden: ['эволюция', 'Дарвин', 'вид', 'выживание', 'природа'],
  },
  {
    id: 118,
    difficulty: 'hard',
    word: 'ЗАБЛУЖДЕНИЕ',
    forbidden: ['ошибка', 'неправда', 'думать', 'мнение', 'обман'],
  },
  {
    id: 119,
    difficulty: 'hard',
    word: 'ИДЕНТИЧНОСТЬ',
    forbidden: ['личность', 'самоопределение', 'индивидуальность', 'кто', 'образ'],
  },
  {
    id: 120,
    difficulty: 'hard',
    word: 'ИДЕОЛОГИЯ',
    forbidden: ['убеждения', 'политика', 'идеи', 'система', 'взгляды'],
  },
  {
    id: 121,
    difficulty: 'hard',
    word: 'ИЕРАРХИЯ',
    forbidden: ['уровень', 'подчинение', 'структура', 'начальник', 'порядок'],
  },
  {
    id: 122,
    difficulty: 'hard',
    word: 'ИНЕРЦИЯ',
    forbidden: ['движение', 'физика', 'Ньютон', 'тело', 'скорость'],
  },
  {
    id: 123,
    difficulty: 'hard',
    word: 'ИННОВАЦИЯ',
    forbidden: ['новинка', 'технология', 'изобретение', 'разработка', 'идея'],
  },
  {
    id: 124,
    difficulty: 'hard',
    word: 'ИНТУИЦИЯ',
    forbidden: ['чувство', 'предчувствие', 'логика', 'подсказка', 'догадка'],
  },
  {
    id: 125,
    difficulty: 'hard',
    word: 'ИРОНИЯ',
    forbidden: ['сарказм', 'насмешка', 'шутка', 'противоположность', 'юмор'],
  },
  {
    id: 126,
    difficulty: 'hard',
    word: 'КОНКУРЕНЦИЯ',
    forbidden: ['соревнование', 'рынок', 'соперник', 'борьба', 'компания'],
  },
  {
    id: 127,
    difficulty: 'hard',
    word: 'КОНФОРМИЗМ',
    forbidden: ['общество', 'большинство', 'подчинение', 'мнение', 'толпа'],
  },
  {
    id: 128,
    difficulty: 'hard',
    word: 'КОНФРОНТАЦИЯ',
    forbidden: ['конфликт', 'столкновение', 'противостояние', 'спор', 'борьба'],
  },
  {
    id: 129,
    difficulty: 'hard',
    word: 'КОРРЕЛЯЦИЯ',
    forbidden: ['связь', 'статистика', 'зависимость', 'данные', 'отношение'],
  },
  {
    id: 130,
    difficulty: 'hard',
    word: 'КРЕАТИВНОСТЬ',
    forbidden: ['творчество', 'идея', 'воображение', 'создавать', 'оригинальность'],
  },
  {
    id: 131,
    difficulty: 'hard',
    word: 'ЛЕГИТИМНОСТЬ',
    forbidden: ['законность', 'власть', 'право', 'признание', 'государство'],
  },
  {
    id: 132,
    difficulty: 'hard',
    word: 'ЛИБЕРАЛИЗМ',
    forbidden: ['политика', 'свобода', 'идеология', 'права', 'государство'],
  },
  {
    id: 133,
    difficulty: 'hard',
    word: 'ЛИНГВИСТИКА',
    forbidden: ['язык', 'слово', 'речь', 'наука', 'грамматика'],
  },
  {
    id: 134,
    difficulty: 'hard',
    word: 'ЛОГИКА',
    forbidden: ['мышление', 'вывод', 'разум', 'аргумент', 'заключение'],
  },
  {
    id: 135,
    difficulty: 'hard',
    word: 'МАНИПУЛЯЦИЯ',
    forbidden: ['влияние', 'обман', 'управлять', 'человек', 'давление'],
  },
  {
    id: 136,
    difficulty: 'hard',
    word: 'МИРОВОЗЗРЕНИЕ',
    forbidden: ['убеждения', 'взгляд', 'жизнь', 'ценности', 'мир'],
  },
  {
    id: 137,
    difficulty: 'hard',
    word: 'МОТИВАЦИЯ',
    forbidden: ['стимул', 'желание', 'цель', 'действие', 'интерес'],
  },
  {
    id: 138,
    difficulty: 'hard',
    word: 'НЕЙТРАЛИТЕТ',
    forbidden: ['сторона', 'конфликт', 'война', 'нейтральный', 'позиция'],
  },
  {
    id: 139,
    difficulty: 'hard',
    word: 'НЕОПРЕДЕЛЁННОСТЬ',
    forbidden: ['неизвестность', 'сомнение', 'будущее', 'ясность', 'непонятно'],
  },
  {
    id: 140,
    difficulty: 'hard',
    word: 'ОБЪЕКТИВНОСТЬ',
    forbidden: ['факт', 'предвзятость', 'мнение', 'нейтральность', 'истина'],
  },
  {
    id: 141,
    difficulty: 'hard',
    word: 'ПАМЯТЬ',
    forbidden: ['воспоминание', 'мозг', 'запоминать', 'прошлое', 'информация'],
  },
  {
    id: 142,
    difficulty: 'hard',
    word: 'ПАНДЕМИЯ',
    forbidden: ['вирус', 'болезнь', 'мир', 'эпидемия', 'карантин'],
  },
  {
    id: 143,
    difficulty: 'hard',
    word: 'ПЕРСПЕКТИВА',
    forbidden: ['будущее', 'вид', 'точка зрения', 'возможность', 'горизонт'],
  },
  {
    id: 144,
    difficulty: 'hard',
    word: 'ПЛАЦЕБО',
    forbidden: ['лекарство', 'эффект', 'таблетка', 'пациент', 'медицина'],
  },
  {
    id: 145,
    difficulty: 'hard',
    word: 'ПЛЮРАЛИЗМ',
    forbidden: ['многообразие', 'мнения', 'общество', 'идеология', 'различие'],
  },
  {
    id: 146,
    difficulty: 'hard',
    word: 'ПОДСОЗНАНИЕ',
    forbidden: ['мозг', 'психология', 'сознание', 'мысли', 'Фрейд'],
  },
  {
    id: 147,
    difficulty: 'hard',
    word: 'ПОЛЯРИЗАЦИЯ',
    forbidden: ['разделение', 'общество', 'мнение', 'противоположность', 'конфликт'],
  },
  {
    id: 148,
    difficulty: 'hard',
    word: 'ПОСТУЛАТ',
    forbidden: ['утверждение', 'аксиома', 'теория', 'доказательство', 'наука'],
  },
  {
    id: 149,
    difficulty: 'hard',
    word: 'ПРАГМАТИЗМ',
    forbidden: ['практика', 'выгода', 'реальность', 'польза', 'подход'],
  },
  {
    id: 150,
    difficulty: 'hard',
    word: 'ПРЕДУБЕЖДЕНИЕ',
    forbidden: ['стереотип', 'мнение', 'убеждение', 'отношение', 'предрассудок'],
  },
  {
    id: 151,
    difficulty: 'hard',
    word: 'ПРЕСТИЖ',
    forbidden: ['статус', 'уважение', 'репутация', 'общество', 'успех'],
  },
  {
    id: 152,
    difficulty: 'hard',
    word: 'ПРИОРИТЕТ',
    forbidden: ['главный', 'важность', 'очередь', 'цель', 'первый'],
  },
  {
    id: 153,
    difficulty: 'hard',
    word: 'ПРОГРЕСС',
    forbidden: ['развитие', 'улучшение', 'движение', 'вперёд', 'рост'],
  },
  {
    id: 154,
    difficulty: 'hard',
    word: 'ПСИХОАНАЛИЗ',
    forbidden: ['Фрейд', 'психология', 'пациент', 'подсознание', 'терапия'],
  },
  {
    id: 155,
    difficulty: 'hard',
    word: 'РАВЕНСТВО',
    forbidden: ['права', 'одинаковый', 'общество', 'справедливость', 'люди'],
  },
  {
    id: 156,
    difficulty: 'hard',
    word: 'РАЦИОНАЛЬНОСТЬ',
    forbidden: ['логика', 'разум', 'мышление', 'обоснование', 'решение'],
  },
  {
    id: 157,
    difficulty: 'hard',
    word: 'РЕВОЛЮЦИЯ',
    forbidden: ['переворот', 'власть', 'изменение', 'народ', 'государство'],
  },
  {
    id: 158,
    difficulty: 'hard',
    word: 'РЕЗОНАНС',
    forbidden: ['частота', 'звук', 'колебание', 'физика', 'волна'],
  },
  {
    id: 159,
    difficulty: 'hard',
    word: 'РЕЛЯТИВИЗМ',
    forbidden: ['относительность', 'истина', 'философия', 'точка зрения', 'абсолют'],
  },
  {
    id: 160,
    difficulty: 'hard',
    word: 'РЕФЛЕКСИЯ',
    forbidden: ['анализ', 'самоанализ', 'размышление', 'мысли', 'осознание'],
  },
  {
    id: 161,
    difficulty: 'hard',
    word: 'САБОТАЖ',
    forbidden: ['вред', 'работа', 'умышленно', 'срыв', 'препятствие'],
  },
  {
    id: 162,
    difficulty: 'hard',
    word: 'САМООЦЕНКА',
    forbidden: ['личность', 'оценивать', 'уверенность', 'себя', 'ценность'],
  },
  {
    id: 163,
    difficulty: 'hard',
    word: 'САРКАЗМ',
    forbidden: ['ирония', 'насмешка', 'юмор', 'колкость', 'шутка'],
  },
  {
    id: 164,
    difficulty: 'hard',
    word: 'СИМБИОЗ',
    forbidden: ['организм', 'взаимодействие', 'польза', 'биология', 'совместный'],
  },
  {
    id: 165,
    difficulty: 'hard',
    word: 'СИМВОЛИЗМ',
    forbidden: ['знак', 'образ', 'литература', 'символ', 'значение'],
  },
  {
    id: 166,
    difficulty: 'hard',
    word: 'СКЕПТИЦИЗМ',
    forbidden: ['сомнение', 'недоверие', 'критика', 'убеждение', 'верить'],
  },
  {
    id: 167,
    difficulty: 'hard',
    word: 'СОЛИДАРНОСТЬ',
    forbidden: ['единство', 'поддержка', 'общество', 'вместе', 'согласие'],
  },
  {
    id: 168,
    difficulty: 'hard',
    word: 'СПРАВЕДЛИВОСТЬ',
    forbidden: ['правосудие', 'честность', 'закон', 'равенство', 'суд'],
  },
  {
    id: 169,
    difficulty: 'hard',
    word: 'СТАБИЛЬНОСТЬ',
    forbidden: ['устойчивость', 'изменение', 'постоянство', 'равновесие', 'надёжность'],
  },
  {
    id: 170,
    difficulty: 'hard',
    word: 'СТАГНАЦИЯ',
    forbidden: ['застой', 'развитие', 'экономика', 'рост', 'остановка'],
  },
  {
    id: 171,
    difficulty: 'hard',
    word: 'СУБЪЕКТИВНОСТЬ',
    forbidden: ['мнение', 'личный', 'объективность', 'взгляд', 'оценка'],
  },
  {
    id: 172,
    difficulty: 'hard',
    word: 'ТЕНДЕНЦИЯ',
    forbidden: ['направление', 'изменение', 'мода', 'развитие', 'тренд'],
  },
  {
    id: 173,
    difficulty: 'hard',
    word: 'ТОЛЕРАНТНОСТЬ',
    forbidden: ['уважение', 'терпимость', 'другой', 'общество', 'принятие'],
  },
  {
    id: 174,
    difficulty: 'hard',
    word: 'ТРАНСФОРМАЦИЯ',
    forbidden: ['изменение', 'превращение', 'форма', 'процесс', 'преобразование'],
  },
  {
    id: 175,
    difficulty: 'hard',
    word: 'УБЕЖДЕНИЕ',
    forbidden: ['мнение', 'вера', 'ценности', 'принцип', 'позиция'],
  },
  {
    id: 176,
    difficulty: 'hard',
    word: 'УРБАНИЗАЦИЯ',
    forbidden: ['город', 'население', 'строительство', 'миграция', 'мегаполис'],
  },
  {
    id: 177,
    difficulty: 'hard',
    word: 'ФАТАЛИЗМ',
    forbidden: ['судьба', 'предопределение', 'рок', 'неизбежность', 'вера'],
  },
  {
    id: 178,
    difficulty: 'hard',
    word: 'ФРАГМЕНТАЦИЯ',
    forbidden: ['разделение', 'часть', 'распад', 'целое', 'дробление'],
  },
  {
    id: 179,
    difficulty: 'hard',
    word: 'ЦЕННОСТЬ',
    forbidden: ['важность', 'значение', 'принцип', 'мораль', 'оценка'],
  },
  {
    id: 180,
    difficulty: 'hard',
    word: 'ЦИВИЛИЗАЦИЯ',
    forbidden: ['общество', 'культура', 'развитие', 'государство', 'история'],
  },
  {
    id: 181,
    difficulty: 'hard',
    word: 'ЭВОЛЮЦИЯ',
    forbidden: ['Дарвин', 'развитие', 'изменение', 'вид', 'природа'],
  },
  {
    id: 182,
    difficulty: 'hard',
    word: 'ЭГОИЗМ',
    forbidden: ['себя', 'интерес', 'другие', 'самолюбие', 'личный'],
  },
  {
    id: 183,
    difficulty: 'hard',
    word: 'ЭКОСИСТЕМА',
    forbidden: ['природа', 'животные', 'растения', 'среда', 'биология'],
  },
  {
    id: 184,
    difficulty: 'hard',
    word: 'ЭКСПАНСИЯ',
    forbidden: ['расширение', 'территория', 'рост', 'захват', 'распространение'],
  },
  {
    id: 185,
    difficulty: 'hard',
    word: 'ЭКСПЕРТИЗА',
    forbidden: ['оценка', 'специалист', 'проверка', 'анализ', 'заключение'],
  },
  {
    id: 186,
    difficulty: 'hard',
    word: 'ЭНТРОПИЯ',
    forbidden: ['хаос', 'термодинамика', 'порядок', 'физика', 'система'],
  },
  {
    id: 187,
    difficulty: 'hard',
    word: 'ЭРУДИЦИЯ',
    forbidden: ['знания', 'образование', 'умный', 'начитанность', 'интеллект'],
  },
  {
    id: 188,
    difficulty: 'hard',
    word: 'ЭТИКА',
    forbidden: ['мораль', 'поведение', 'добро', 'зло', 'правила'],
  },
  {
    id: 189,
    difficulty: 'hard',
    word: 'ЭФФЕКТИВНОСТЬ',
    forbidden: ['результат', 'польза', 'производительность', 'успех', 'работа'],
  },
  {
    id: 190,
    difficulty: 'hard',
    word: 'ЯВЛЕНИЕ',
    forbidden: ['событие', 'наблюдать', 'процесс', 'природа', 'феномен'],
  },
  { id: 501, difficulty: 'hard', word: 'АБСТРАКЦИЯ', forbidden: ['идея', 'форма', 'искусство', 'мышление', 'обобщение'] },
  { id: 502, difficulty: 'hard', word: 'КОНТЕКСТ', forbidden: ['ситуация', 'смысл', 'текст', 'окружение', 'значение'] },
  { id: 503, difficulty: 'hard', word: 'СИНЕРГИЯ', forbidden: ['эффект', 'вместе', 'результат', 'сотрудничество', 'система'] },
  { id: 504, difficulty: 'hard', word: 'ИНСАЙТ', forbidden: ['понимание', 'идея', 'внезапно', 'озарение', 'мысль'] },
  { id: 505, difficulty: 'hard', word: 'ПЕРЦЕПЦИЯ', forbidden: ['восприятие', 'чувства', 'мозг', 'ощущение', 'интерпретация'] },

  { id: 506, difficulty: 'hard', word: 'КВИНТЭССЕНЦИЯ', forbidden: ['суть', 'основа', 'главное', 'эссенция', 'смысл'] },
  { id: 507, difficulty: 'hard', word: 'ДИСПЕРСИЯ', forbidden: ['разброс', 'статистика', 'данные', 'вариация', 'отклонение'] },
  { id: 508, difficulty: 'hard', word: 'ПАРАДИГМА', forbidden: ['модель', 'система', 'мышление', 'наука', 'подход'] },
  { id: 509, difficulty: 'hard', word: 'КОНВЕРГЕНЦИЯ', forbidden: ['схождение', 'развитие', 'точка', 'слияние', 'процесс'] },
  { id: 510, difficulty: 'hard', word: 'ДИВЕРГЕНЦИЯ', forbidden: ['расхождение', 'разделение', 'развитие', 'линия', 'отклонение'] },

  { id: 511, difficulty: 'hard', word: 'СИМУЛЯКР', forbidden: ['копия', 'реальность', 'образ', 'иллюзия', 'знак'] },
  { id: 512, difficulty: 'hard', word: 'РЕФЕРЕНТНОСТЬ', forbidden: ['ссылка', 'значение', 'контекст', 'объект', 'указание'] },
  { id: 513, difficulty: 'hard', word: 'ЭКЗИСТЕНЦИЯ', forbidden: ['существование', 'жизнь', 'бытие', 'философия', 'человек'] },
  { id: 514, difficulty: 'hard', word: 'ФЕНОМЕНОЛОГИЯ', forbidden: ['сознание', 'опыт', 'философия', 'восприятие', 'явление'] },
  { id: 515, difficulty: 'hard', word: 'ДЕКОНСТРУКЦИЯ', forbidden: ['разбор', 'анализ', 'структура', 'разрушение', 'текст'] },

  { id: 516, difficulty: 'hard', word: 'СЕМИОТИКА', forbidden: ['знаки', 'символы', 'язык', 'значение', 'коммуникация'] },
  { id: 517, difficulty: 'hard', word: 'ГЕРМЕНЕВТИКА', forbidden: ['интерпретация', 'текст', 'смысл', 'понимание', 'анализ'] },
  { id: 518, difficulty: 'hard', word: 'ПРОЛИФЕРАЦИЯ', forbidden: ['рост', 'размножение', 'увеличение', 'распространение', 'процесс'] },
  { id: 519, difficulty: 'hard', word: 'КАТАРСИС', forbidden: ['очищение', 'эмоции', 'театр', 'переживание', 'разрядка'] },
  { id: 520, difficulty: 'hard', word: 'АВТЕНТИЧНОСТЬ', forbidden: ['настоящий', 'подлинность', 'истина', 'оригинал', 'личность'] },

  { id: 521, difficulty: 'hard', word: 'РЕЗИЛЬЕНТНОСТЬ', forbidden: ['устойчивость', 'стресс', 'адаптация', 'психология', 'восстановление'] },
  { id: 522, difficulty: 'hard', word: 'СИНГУЛЯРНОСТЬ', forbidden: ['точка', 'технология', 'будущее', 'ИИ', 'развитие'] },
  { id: 523, difficulty: 'hard', word: 'ТРИВИАЛЬНОСТЬ', forbidden: ['простое', 'очевидное', 'банальное', 'легкое', 'обычное'] },
  { id: 524, difficulty: 'hard', word: 'КОНЦЕПТУАЛИЗАЦИЯ', forbidden: ['идея', 'понятие', 'формирование', 'мышление', 'структура'] },
  { id: 525, difficulty: 'hard', word: 'АЛЬТЕРНАТИВА', forbidden: ['выбор', 'вариант', 'другой', 'решение', 'сравнение'] },

  { id: 526, difficulty: 'hard', word: 'РЕДУКЦИЯ', forbidden: ['сокращение', 'упрощение', 'уменьшение', 'анализ', 'процесс'] },
  { id: 527, difficulty: 'hard', word: 'ПРЕЦЕДЕНТ', forbidden: ['случай', 'пример', 'закон', 'суд', 'решение'] },
  { id: 528, difficulty: 'hard', word: 'КОНСТРУКТ', forbidden: ['идея', 'модель', 'построение', 'понятие', 'структура'] },
  { id: 529, difficulty: 'hard', word: 'ДИСКУРС', forbidden: ['речь', 'текст', 'анализ', 'язык', 'коммуникация'] },
  { id: 530, difficulty: 'hard', word: 'ИНТЕРСУБЪЕКТИВНОСТЬ', forbidden: ['люди', 'сознание', 'общение', 'понимание', 'восприятие'] },

  { id: 531, difficulty: 'hard', word: 'РЕПРЕЗЕНТАЦИЯ', forbidden: ['представление', 'образ', 'показ', 'символ', 'значение'] },
  { id: 532, difficulty: 'hard', word: 'СЕМАНТИКА', forbidden: ['значение', 'язык', 'слово', 'смысл', 'лингвистика'] },
  { id: 533, difficulty: 'hard', word: 'ПРАГМАТИКА', forbidden: ['язык', 'смысл', 'контекст', 'общение', 'значение'] },
  { id: 534, difficulty: 'hard', word: 'РЕКУРСИЯ', forbidden: ['функция', 'повтор', 'код', 'алгоритм', 'программирование'] },
  { id: 535, difficulty: 'hard', word: 'ИНВАРИАНТ', forbidden: ['неизменный', 'математика', 'свойство', 'постоянство', 'система'] },

  { id: 536, difficulty: 'hard', word: 'МОДАЛЬНОСТЬ', forbidden: ['возможность', 'логика', 'значение', 'тип', 'состояние'] },
  { id: 537, difficulty: 'hard', word: 'КОГНИЦИЯ', forbidden: ['мышление', 'мозг', 'знание', 'психология', 'процесс'] },
  { id: 538, difficulty: 'hard', word: 'РЕТРОСПЕКТИВА', forbidden: ['прошлое', 'анализ', 'взгляд', 'история', 'событие'] },
  { id: 539, difficulty: 'hard', word: 'ПРОСПЕКТИВА', forbidden: ['будущее', 'вид', 'план', 'перспектива', 'развитие'] },
  { id: 540, difficulty: 'hard', word: 'АНТРОПОЛОГИЯ', forbidden: ['человек', 'наука', 'общество', 'культура', 'исследование'] },

  { id: 541, difficulty: 'hard', word: 'СОЦИАЛИЗАЦИЯ', forbidden: ['общество', 'люди', 'поведение', 'адаптация', 'группа'] },
  { id: 542, difficulty: 'hard', word: 'РЕГУЛЯТИВ', forbidden: ['правило', 'норма', 'управление', 'контроль', 'система'] },
  { id: 543, difficulty: 'hard', word: 'СИНКРЕТИЗМ', forbidden: ['смешение', 'искусство', 'культура', 'единство', 'форма'] },
  { id: 544, difficulty: 'hard', word: 'ТЕЛЕОЛОГИЯ', forbidden: ['цель', 'философия', 'смысл', 'причина', 'направление'] },
  { id: 545, difficulty: 'hard', word: 'УТИЛИТАРИЗМ', forbidden: ['польза', 'философия', 'выгода', 'мораль', 'принцип'] },

  { id: 546, difficulty: 'hard', word: 'ФУНКЦИОНАЛЬНОСТЬ', forbidden: ['функция', 'работа', 'система', 'назначение', 'использование'] },
  { id: 547, difficulty: 'hard', word: 'ЦЕЛЕСООБРАЗНОСТЬ', forbidden: ['логика', 'польза', 'разум', 'решение', 'эффективность'] },
  { id: 548, difficulty: 'hard', word: 'ЭПИСТЕМОЛОГИЯ', forbidden: ['знание', 'философия', 'истина', 'познание', 'наука'] },
  { id: 549, difficulty: 'hard', word: 'ЮРИСДИКЦИЯ', forbidden: ['закон', 'суд', 'территория', 'власть', 'право'] },
  { id: 550, difficulty: 'hard', word: 'ЭСТЕТИКА', forbidden: ['красота', 'искусство', 'вкус', 'философия', 'форма'] },
  { id: 555, difficulty: 'hard', word: 'РЕФЛЕКСИВНОСТЬ', forbidden: ['мышление', 'самоанализ', 'сознание', 'размышление', 'рефлексия'] },
  { id: 556, difficulty: 'hard', word: 'КОНГРУЭНТНОСТЬ', forbidden: ['соответствие', 'равенство', 'совпадение', 'геометрия', 'форма'] },
  { id: 557, difficulty: 'hard', word: 'ДЕТЕРМИНИЗМ', forbidden: ['судьба', 'причина', 'свобода', 'выбор', 'закономерность'] },
  { id: 558, difficulty: 'hard', word: 'ИНДЕТЕРМИНИЗМ', forbidden: ['случайность', 'свобода', 'выбор', 'причина', 'хаос'] },
  { id: 559, difficulty: 'hard', word: 'ГЕРМЕНЕВТИКА', forbidden: ['толкование', 'текст', 'смысл', 'понимание', 'анализ'] },

  { id: 560, difficulty: 'hard', word: 'СИНЕРГИЯ', forbidden: ['эффект', 'взаимодействие', 'сила', 'работа', 'результат'] },
  { id: 561, difficulty: 'hard', word: 'ЭМЕРДЖЕНТНОСТЬ', forbidden: ['система', 'свойство', 'сложность', 'части', 'целое'] },
  { id: 562, difficulty: 'hard', word: 'ТОПОГРАФИЯ', forbidden: ['карта', 'местность', 'рельеф', 'измерение', 'земля'] },
  { id: 563, difficulty: 'hard', word: 'КОНЦЕПТУАЛИЗАЦИЯ', forbidden: ['идея', 'понятие', 'мышление', 'создание', 'модель'] },
  { id: 564, difficulty: 'hard', word: 'МЕТАНАРРАТИВ', forbidden: ['история', 'рассказ', 'общество', 'идеология', 'смысл'] },

  { id: 565, difficulty: 'hard', word: 'СОЦИОКУЛЬТУРНЫЙ', forbidden: ['общество', 'культура', 'люди', 'социальный', 'традиция'] },
  { id: 566, difficulty: 'hard', word: 'ПЛЮРАЛИЗМ', forbidden: ['мнение', 'разнообразие', 'идея', 'общество', 'выбор'] },
  { id: 567, difficulty: 'hard', word: 'РЕДУКЦИОНИЗМ', forbidden: ['упрощение', 'система', 'часть', 'целое', 'анализ'] },
  { id: 568, difficulty: 'hard', word: 'КОРРЕЛЯЦИЯ', forbidden: ['связь', 'зависимость', 'статистика', 'данные', 'отношение'] },
  { id: 569, difficulty: 'hard', word: 'КАУЗАЛЬНОСТЬ', forbidden: ['причина', 'следствие', 'связь', 'влияние', 'логика'] },

  { id: 570, difficulty: 'hard', word: 'СЕМИОТИКА', forbidden: ['знак', 'язык', 'символ', 'смысл', 'коммуникация'] },
  { id: 571, difficulty: 'hard', word: 'ДИСКУРС', forbidden: ['речь', 'текст', 'разговор', 'язык', 'смысл'] },
  { id: 572, difficulty: 'hard', word: 'ИДЕОГРАФИЯ', forbidden: ['символ', 'знак', 'письмо', 'язык', 'значение'] },
  { id: 573, difficulty: 'hard', word: 'АНТРОПОЦЕНТРИЗМ', forbidden: ['человек', 'мир', 'природа', 'центр', 'вселенная'] },
  { id: 574, difficulty: 'hard', word: 'ЭКОСИСТЕМА', forbidden: ['природа', 'животные', 'система', 'баланс', 'среда'] },

  { id: 575, difficulty: 'hard', word: 'КИБЕРНЕТИКА', forbidden: ['система', 'управление', 'компьютер', 'информация', 'обратная связь'] },
  { id: 576, difficulty: 'hard', word: 'АЛГОРИТМИЗАЦИЯ', forbidden: ['алгоритм', 'код', 'решение', 'шаги', 'программа'] },
  { id: 577, difficulty: 'hard', word: 'ФОРМАЛИЗАЦИЯ', forbidden: ['форма', 'правило', 'структура', 'запись', 'система'] },
  { id: 578, difficulty: 'hard', word: 'АКСИОМАТИКА', forbidden: ['аксиома', 'математика', 'доказательство', 'теория', 'логика'] },
  { id: 579, difficulty: 'hard', word: 'ЛОГИЦИЗМ', forbidden: ['логика', 'математика', 'мышление', 'доказательство', 'система'] },

  { id: 580, difficulty: 'hard', word: 'ВЕРИФИКАЦИЯ', forbidden: ['проверка', 'истина', 'доказательство', 'тест', 'подтверждение'] },
  { id: 581, difficulty: 'hard', word: 'ФАЛЬСИФИКАЦИЯ', forbidden: ['ложь', 'проверка', 'ошибка', 'наука', 'доказательство'] },
  { id: 582, difficulty: 'hard', word: 'ИНТЕРПРЕТАЦИЯ', forbidden: ['смысл', 'толкование', 'понимание', 'анализ', 'объяснение'] },
  { id: 583, difficulty: 'hard', word: 'РЕПРЕЗЕНТАЦИЯ', forbidden: ['представление', 'образ', 'символ', 'показ', 'изображение'] },
  { id: 584, difficulty: 'hard', word: 'СИМВОЛИЗАЦИЯ', forbidden: ['символ', 'знак', 'значение', 'образ', 'представление'] },

  { id: 585, difficulty: 'hard', word: 'КОНСТРУКТИВИЗМ', forbidden: ['построение', 'знание', 'обучение', 'идея', 'модель'] },
  { id: 586, difficulty: 'hard', word: 'ФУНКЦИОНАЛИЗМ', forbidden: ['функция', 'роль', 'система', 'психология', 'структура'] },
  { id: 587, difficulty: 'hard', word: 'СТРУКТУРАЛИЗМ', forbidden: ['структура', 'язык', 'система', 'анализ', 'смысл'] },
  { id: 588, difficulty: 'hard', word: 'ПОСТСТРУКТУРАЛИЗМ', forbidden: ['структура', 'смысл', 'язык', 'анализ', 'философия'] },
  { id: 589, difficulty: 'hard', word: 'РЕЦЕПЦИЯ', forbidden: ['восприятие', 'приём', 'понимание', 'ответ', 'интерпретация'] },

  { id: 590, difficulty: 'hard', word: 'ИНТЕРСУБЪЕКТИВНОСТЬ', forbidden: ['люди', 'сознание', 'общение', 'понимание', 'восприятие'] },
  { id: 591, difficulty: 'hard', word: 'КОГНИТИВИЗМ', forbidden: ['мышление', 'познание', 'психология', 'разум', 'информация'] },
  { id: 592, difficulty: 'hard', word: 'БИХЕВИОРИЗМ', forbidden: ['поведение', 'реакция', 'психология', 'стимул', 'действие'] },
  { id: 593, difficulty: 'hard', word: 'НЕОПОЗИТИВИЗМ', forbidden: ['наука', 'логика', 'истина', 'философия', 'проверка'] },
  { id: 594, difficulty: 'hard', word: 'ПАРАДОКСАЛЬНОСТЬ', forbidden: ['противоречие', 'логика', 'странность', 'ситуация', 'смысл'] },

  { id: 595, difficulty: 'hard', word: 'АМБИВАЛЕНТНОСТЬ', forbidden: ['чувства', 'двойственность', 'неопределённость', 'отношение', 'эмоции'] },
  { id: 596, difficulty: 'hard', word: 'КАТЕГОРИЗАЦИЯ', forbidden: ['класс', 'группа', 'разделение', 'сортировка', 'понятие'] },
  { id: 597, difficulty: 'hard', word: 'ДИФФЕРЕНЦИАЦИЯ', forbidden: ['различие', 'разделение', 'разница', 'процесс', 'анализ'] },
  { id: 598, difficulty: 'hard', word: 'ИНТЕГРАЦИЯ', forbidden: ['объединение', 'система', 'связь', 'целое', 'соединение'] },
  { id: 599, difficulty: 'hard', word: 'МОДЕЛИРОВАНИЕ', forbidden: ['модель', 'система', 'симуляция', 'процесс', 'создание'] },

];

export const TABOO_CLASSIC_CARDS: readonly TabooClassicCard[] = [...EASY, ...MEDIUM, ...HARD];

/** Все слова колоды данной сложности — общий источник для игры и contentService.getWordStats. */
export function getTabooClassicWordPool(difficulty: Difficulty): string[] {
  return TABOO_CLASSIC_CARDS.filter((c) => c.difficulty === difficulty).map((c) => c.word);
}

/** Pick a random unused card of the given difficulty. */
export function getNextTabooClassicCard(
  difficulty: Difficulty,
  usedIds: ReadonlySet<number>
): TabooClassicCard {
  const pool = TABOO_CLASSIC_CARDS.filter((c) => c.difficulty === difficulty && !usedIds.has(c.id));
  if (pool.length === 0) {
    // All cards used — fall back to full deck
    return TABOO_CLASSIC_CARDS.filter((c) => c.difficulty === difficulty)[
      Math.floor(
        Math.random() * TABOO_CLASSIC_CARDS.filter((c) => c.difficulty === difficulty).length
      )
    ];
  }
  return pool[Math.floor(Math.random() * pool.length)];
}
