export interface FakeArtistCategory {
  category: string;
  word: string;
}

export type FakeArtistDifficulty = 'easy' | 'medium' | 'hard';

export const FAKE_ARTIST_DIFFICULTY_CONFIG = {
  easy: {
    label: 'Легко',
    emoji: '🌱',
    desc: 'Узнаваемые образы — понятно всем',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    text: 'text-emerald-400',
  },
  medium: {
    label: 'Средне',
    emoji: '🔥',
    desc: 'Сложнее нарисовать за одну линию',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    text: 'text-orange-400',
  },
  hard: {
    label: 'Сложно',
    emoji: '💀',
    desc: 'Абстракции — самозванцу легче слиться',
    bg: 'bg-red-500/10',
    border: 'border-red-500/30',
    text: 'text-red-400',
  },
} as const;

export const FAKE_ARTIST_DATA_BY_DIFFICULTY: Record<FakeArtistDifficulty, FakeArtistCategory[]> = {
  easy: [
    // Животные
    { category: "Животные", word: "Жираф" },
    { category: "Животные", word: "Слон" },
    { category: "Животные", word: "Пингвин" },
    { category: "Животные", word: "Осьминог" },
    { category: "Животные", word: "Коала" },
    { category: "Животные", word: "Сова" },
    { category: "Животные", word: "Черепаха" },
    { category: "Животные", word: "Лягушка" },
    { category: "Животные", word: "Акула" },
    { category: "Животные", word: "Кролик" },
    { category: "Животные", word: "Кот" },
    { category: "Животные", word: "Собака" },
    { category: "Животные", word: "Рыба" },
    { category: "Животные", word: "Лошадь" },
    { category: "Животные", word: "Утка" },
    { category: "Животные", word: "Петух" },
    { category: "Животные", word: "Медведь" },
    { category: "Животные", word: "Бабочка" },
    { category: "Животные", word: "Змея" },
    { category: "Животные", word: "Краб" },
    // Транспорт
    { category: "Транспорт", word: "Самолёт" },
    { category: "Транспорт", word: "Поезд" },
    { category: "Транспорт", word: "Велосипед" },
    { category: "Транспорт", word: "Корабль" },
    { category: "Транспорт", word: "Лодка" },
    { category: "Транспорт", word: "Автобус" },
    { category: "Транспорт", word: "Ракета" },
    { category: "Транспорт", word: "Скутер" },
    { category: "Транспорт", word: "Грузовик" },
    // Предметы
    { category: "Предметы", word: "Будильник" },
    { category: "Предметы", word: "Гитара" },
    { category: "Предметы", word: "Зонт" },
    { category: "Предметы", word: "Ключ" },
    { category: "Предметы", word: "Свеча" },
    { category: "Предметы", word: "Молоток" },
    { category: "Предметы", word: "Карандаш" },
    { category: "Предметы", word: "Телевизор" },
    { category: "Предметы", word: "Чайник" },
    { category: "Предметы", word: "Фонарик" },
    { category: "Предметы", word: "Очки" },
    { category: "Предметы", word: "Книга" },
    { category: "Предметы", word: "Лампочка" },
    { category: "Предметы", word: "Фотоаппарат" },
    { category: "Предметы", word: "Рюкзак" },
    { category: "Предметы", word: "Мяч" },
    { category: "Предметы", word: "Зеркало" },
    // Еда
    { category: "Еда", word: "Пицца" },
    { category: "Еда", word: "Бургер" },
    { category: "Еда", word: "Мороженое" },
    { category: "Еда", word: "Пончик" },
    { category: "Еда", word: "Торт" },
    { category: "Еда", word: "Арбуз" },
    { category: "Еда", word: "Яблоко" },
    { category: "Еда", word: "Попкорн" },
    { category: "Еда", word: "Банан" },
    { category: "Еда", word: "Морковь" },
    { category: "Еда", word: "Клубника" },
    { category: "Еда", word: "Тыква" },
    // Места
    { category: "Места", word: "Пляж" },
    { category: "Места", word: "Парк" },
    { category: "Места", word: "Замок" },
    { category: "Места", word: "Вулкан" },
    { category: "Места", word: "Маяк" },
    { category: "Места", word: "Пирамида" },
    { category: "Места", word: "Лес" },
    { category: "Места", word: "Пустыня" },
    { category: "Места", word: "Гора" },
  ],
  medium: [
    // Животные
    { category: "Животные", word: "Кенгуру" },
    { category: "Животные", word: "Тигр" },
    { category: "Животные", word: "Лиса" },
    { category: "Животные", word: "Крокодил" },
    { category: "Животные", word: "Панда" },
    { category: "Животные", word: "Верблюд" },
    { category: "Животные", word: "Белка" },
    { category: "Животные", word: "Пчела" },
    { category: "Животные", word: "Дельфин" },
    { category: "Животные", word: "Кит" },
    { category: "Животные", word: "Страус" },
    // Транспорт
    { category: "Транспорт", word: "Вертолёт" },
    { category: "Транспорт", word: "Подводная лодка" },
    { category: "Транспорт", word: "Пожарная машина" },
    { category: "Транспорт", word: "Мотоцикл" },
    { category: "Транспорт", word: "Трактор" },
    { category: "Транспорт", word: "Метро" },
    { category: "Транспорт", word: "Танк" },
    // Еда
    { category: "Еда", word: "Суши" },
    { category: "Еда", word: "Хот-дог" },
    { category: "Еда", word: "Спагетти" },
    { category: "Еда", word: "Тако" },
    { category: "Еда", word: "Шоколад" },
    { category: "Еда", word: "Омлет" },
    { category: "Еда", word: "Картошка фри" },
    { category: "Еда", word: "Ананас" },
    { category: "Еда", word: "Виноград" },
    { category: "Еда", word: "Лимон" },
    { category: "Еда", word: "Брокколи" },
    // Спорт
    { category: "Спорт", word: "Футбол" },
    { category: "Спорт", word: "Теннис" },
    { category: "Спорт", word: "Бокс" },
    { category: "Спорт", word: "Баскетбол" },
    { category: "Спорт", word: "Хоккей" },
    { category: "Спорт", word: "Серфинг" },
    { category: "Спорт", word: "Йога" },
    { category: "Спорт", word: "Карате" },
    { category: "Спорт", word: "Гольф" },
    { category: "Спорт", word: "Плавание" },
    { category: "Спорт", word: "Боулинг" },
    { category: "Спорт", word: "Волейбол" },
    { category: "Спорт", word: "Лыжи" },
    { category: "Спорт", word: "Скейтбординг" },
    { category: "Спорт", word: "Фехтование" },
    // Природа
    { category: "Природа", word: "Водопад" },
    { category: "Природа", word: "Радуга" },
    { category: "Природа", word: "Ураган" },
    { category: "Природа", word: "Торнадо" },
    { category: "Природа", word: "Пещера" },
    { category: "Природа", word: "Озеро" },
    { category: "Природа", word: "Река" },
    { category: "Природа", word: "Ледник" },
    { category: "Природа", word: "Остров" },
    { category: "Природа", word: "Каньон" },
    { category: "Природа", word: "Болото" },
    { category: "Природа", word: "Джунгли" },
    // Сказки и фэнтези
    { category: "Сказки", word: "Дракон" },
    { category: "Сказки", word: "Единорог" },
    { category: "Сказки", word: "Русалка" },
    { category: "Сказки", word: "Феникс" },
    { category: "Сказки", word: "Гоблин" },
    { category: "Сказки", word: "Фея" },
    { category: "Сказки", word: "Тролль" },
    { category: "Сказки", word: "Рыцарь" },
    { category: "Сказки", word: "Принцесса" },
    { category: "Сказки", word: "Волшебник" },
    // Одежда
    { category: "Одежда", word: "Куртка" },
    { category: "Одежда", word: "Кроссовки" },
    { category: "Одежда", word: "Перчатки" },
    { category: "Одежда", word: "Шарф" },
    { category: "Одежда", word: "Носки" },
    { category: "Одежда", word: "Платье" },
    { category: "Одежда", word: "Галстук" },
    { category: "Одежда", word: "Кепка" },
    { category: "Одежда", word: "Свитер" },
    { category: "Одежда", word: "Шляпа" },
    // Музыкальные инструменты
    { category: "Муз. инструменты", word: "Барабан" },
    { category: "Муз. инструменты", word: "Скрипка" },
    { category: "Муз. инструменты", word: "Пианино" },
    { category: "Муз. инструменты", word: "Труба" },
    { category: "Муз. инструменты", word: "Арфа" },
    { category: "Муз. инструменты", word: "Флейта" },
    { category: "Муз. инструменты", word: "Саксофон" },
    { category: "Муз. инструменты", word: "Укулеле" },
    { category: "Муз. инструменты", word: "Электрогитара" },
    { category: "Муз. инструменты", word: "Баян" },
    { category: "Муз. инструменты", word: "Ксилофон" },
    { category: "Муз. инструменты", word: "Виолончель" },
  ],
  hard: [
    // Эмоции
    { category: "Эмоции", word: "Радость" },
    { category: "Эмоции", word: "Грусть" },
    { category: "Эмоции", word: "Страх" },
    { category: "Эмоции", word: "Удивление" },
    { category: "Эмоции", word: "Злость" },
    { category: "Эмоции", word: "Смущение" },
    { category: "Эмоции", word: "Гордость" },
    { category: "Эмоции", word: "Сонливость" },
    { category: "Эмоции", word: "Восторг" },
    { category: "Эмоции", word: "Паника" },
    { category: "Эмоции", word: "Любопытство" },
    { category: "Эмоции", word: "Скука" },
    { category: "Эмоции", word: "Шок" },
    { category: "Эмоции", word: "Спокойствие" },
    { category: "Эмоции", word: "Надежда" },
    // Профессии
    { category: "Профессии", word: "Повар" },
    { category: "Профессии", word: "Врач" },
    { category: "Профессии", word: "Космонавт" },
    { category: "Профессии", word: "Учитель" },
    { category: "Профессии", word: "Полицейский" },
    { category: "Профессии", word: "Пожарный" },
    { category: "Профессии", word: "Музыкант" },
    { category: "Профессии", word: "Фермер" },
    { category: "Профессии", word: "Художник" },
    { category: "Профессии", word: "Программист" },
    { category: "Профессии", word: "Строитель" },
    { category: "Профессии", word: "Пилот" },
    { category: "Профессии", word: "Детектив" },
    { category: "Профессии", word: "Бариста" },
    { category: "Профессии", word: "Судья" },
    // Технологии
    { category: "Технологии", word: "Робот" },
    { category: "Технологии", word: "Смартфон" },
    { category: "Технологии", word: "Дрон" },
    { category: "Технологии", word: "VR-очки" },
    { category: "Технологии", word: "Клавиатура" },
    { category: "Технологии", word: "Wi-Fi" },
    { category: "Технологии", word: "Сервер" },
    { category: "Технологии", word: "Искусственный интеллект" },
    { category: "Технологии", word: "3D-принтер" },
    { category: "Технологии", word: "Умные часы" },
    { category: "Технологии", word: "Камера наблюдения" },
    { category: "Технологии", word: "Голограмма" },
    // Игры
    { category: "Игры", word: "Шахматы" },
    { category: "Игры", word: "Тетрис" },
    { category: "Игры", word: "Мафия" },
    { category: "Игры", word: "Монополия" },
    { category: "Игры", word: "Minecraft" },
    { category: "Игры", word: "Pac-Man" },
    { category: "Игры", word: "Among Us" },
    { category: "Игры", word: "Покер" },
    { category: "Игры", word: "Домино" },
    { category: "Игры", word: "Крестики-нолики" },
    { category: "Игры", word: "Судоку" },
    { category: "Игры", word: "Рулетка" },
    // Космос
    { category: "Космос", word: "Планета" },
    { category: "Космос", word: "Комета" },
    { category: "Космос", word: "Спутник" },
    { category: "Космос", word: "Астероид" },
    { category: "Космос", word: "Телескоп" },
    { category: "Космос", word: "Инопланетянин" },
    { category: "Космос", word: "Чёрная дыра" },
    { category: "Космос", word: "Созвездие" },
    { category: "Космос", word: "Галактика" },
    { category: "Космос", word: "Космическая станция" },
    // Сложные фэнтези / места
    { category: "Сказки", word: "Замок дракона" },
    { category: "Сказки", word: "Магический посох" },
    { category: "Сказки", word: "Зелье" },
    { category: "Сказки", word: "Заколдованный лес" },
    { category: "Сказки", word: "Грифон" },
    { category: "Места", word: "Эйфелева башня" },
    { category: "Места", word: "Музей" },
    { category: "Места", word: "Стадион" },
    { category: "Места", word: "Аэропорт" },
    { category: "Места", word: "Аквапарк" },
    { category: "Природа", word: "Северное сияние" },
  ],
};

export const FAKE_ARTIST_DATA: FakeArtistCategory[] = [
  ...FAKE_ARTIST_DATA_BY_DIFFICULTY.easy,
  ...FAKE_ARTIST_DATA_BY_DIFFICULTY.medium,
  ...FAKE_ARTIST_DATA_BY_DIFFICULTY.hard,
];

export const FAKE_ARTIST_INSTRUCTIONS = [
  { title: "Суть игры", content: "Все игроки знают Тему и Слово, кроме одного (Самозванца). Он знает только Тему." },
  { title: "Рисование", content: "Игроки по очереди рисуют по ОДНОЙ непрерывной линии. Нельзя отрывать руку/стилус от экрана во время хода." },
  { title: "Два круга", content: "Игра длится ровно два круга. Каждый должен внести свой вклад в рисунок, не выдавая слово слишком явно." },
  { title: "Сложность", content: "Лёгкий: чёткие образы, самозванца легко вычислить. Сложный: абстракции — всем труднее рисовать, самозванцу проще скрыться." },
  { title: "Финал", content: "После второго круга все голосуют за Самозванца. Если его поймали, у него есть шанс угадать слово и победить!" },
];
