import type {Difficulty} from "@/shared/types";


export interface FakeArtistCategory {
    category: string;
    word: string;
}

export const FAKE_ARTIST_ROLE_IDS = {
    IMPOSTER: 'Самозванец',
    ARTIST: 'Художник',
} as const;

export const FAKE_ARTIST_DATA_BY_DIFFICULTY: Record<Difficulty, FakeArtistCategory[]> = {
    easy: [
        // Животные
        {category: 'Животные', word: 'Кот'},
        {category: 'Животные', word: 'Собака'},
        {category: 'Животные', word: 'Жираф'},
        {category: 'Животные', word: 'Слон'},
        {category: 'Животные', word: 'Лев'},
        {category: 'Животные', word: 'Тигр'},
        {category: 'Животные', word: 'Пингвин'},
        {category: 'Животные', word: 'Крокодил'},
        {category: 'Животные', word: 'Черепаха'},
        {category: 'Животные', word: 'Обезьяна'},
        {category: 'Животные', word: 'Зебра'},
        {category: 'Животные', word: 'Коала'},
        {category: 'Животные', word: 'Лиса'},
        {category: 'Животные', word: 'Волк'},
        {category: 'Животные', word: 'Кролик'},
        {category: 'Животные', word: 'Бегемот'},
        {category: 'Животные', word: 'Панда'},
        {category: 'Животные', word: 'Ёж'},
        {category: 'Животные', word: 'Белка'},
        {category: 'Животные', word: 'Петух'},


        // Еда
        {category: 'Еда', word: 'Пицца'},
        {category: 'Еда', word: 'Бургер'},
        {category: 'Еда', word: 'Мороженое'},
        {category: 'Еда', word: 'Яблоко'},
        {category: 'Еда', word: 'Банан'},
        {category: 'Еда', word: 'Торт'},
        {category: 'Еда', word: 'Суши'},
        {category: 'Еда', word: 'Картошка фри'},
        {category: 'Еда', word: 'Арбуз'},
        {category: 'Еда', word: 'Пончик'},
        {category: 'Еда', word: 'Хот-дог'},
        {category: 'Еда', word: 'Спагетти'},
        {category: 'Еда', word: 'Омлет'},
        {category: 'Еда', word: 'Кекс'},
        {category: 'Еда', word: 'Попкорн'},
        {category: 'Еда', word: 'Шоколад'},
        {category: 'Еда', word: 'Круассан'},
        {category: 'Еда', word: 'Пельмени'},
        {category: 'Еда', word: 'Тако'},

        // Предметы
        {category: 'Предметы', word: 'Стул'},
        {category: 'Предметы', word: 'Стол'},
        {category: 'Предметы', word: 'Лампа'},
        {category: 'Предметы', word: 'Телефон'},
        {category: 'Предметы', word: 'Рюкзак'},
        {category: 'Предметы', word: 'Часы'},
        {category: 'Предметы', word: 'Зонт'},
        {category: 'Предметы', word: 'Кружка'},
        {category: 'Предметы', word: 'Подушка'},
        {category: 'Предметы', word: 'Ножницы'},
        {category: 'Предметы', word: 'Микрофон'},
        {category: 'Предметы', word: 'Гитара'},
        {category: 'Предметы', word: 'Свеча'},
        {category: 'Предметы', word: 'Ключ'},
        {category: 'Предметы', word: 'Чемодан'},
        {category: 'Предметы', word: 'Шлем'},
        {category: 'Предметы', word: 'Вентилятор'},
        {category: 'Предметы', word: 'Молоток'},
        {category: 'Предметы', word: 'Фотоаппарат'},
        {category: 'Предметы', word: 'Зеркало'},
        {category: 'Предметы', word: 'Очки'},
        {category: 'Предметы', word: 'Будильник'},

        // Природа
        {category: 'Природа', word: 'Солнце'},
        {category: 'Природа', word: 'Луна'},
        {category: 'Природа', word: 'Облако'},
        {category: 'Природа', word: 'Гора'},
        {category: 'Природа', word: 'Река'},
        {category: 'Природа', word: 'Лес'},
        {category: 'Природа', word: 'Остров'},
        {category: 'Природа', word: 'Вулкан'},
        {category: 'Природа', word: 'Пляж'},
        {category: 'Природа', word: 'Радуга'},
        {category: 'Природа', word: 'Снежинка'},
        {category: 'Природа', word: 'Водопад'},
        {category: 'Природа', word: 'Пустыня'},
        {category: 'Природа', word: 'Пещера'},
        {category: 'Природа', word: 'Гроза'},
        {category: 'Природа', word: 'Каньон'},
        {category: 'Природа', word: 'Молния'},
        {category: 'Природа', word: 'Айсберг'},

        {category: 'Транспорт', word: 'Машина'},
        {category: 'Транспорт', word: 'Автобус'},
        {category: 'Транспорт', word: 'Велосипед'},
        {category: 'Транспорт', word: 'Самолёт'},
        {category: 'Транспорт', word: 'Поезд'},
        {category: 'Транспорт', word: 'Корабль'},
        {category: 'Транспорт', word: 'Самокат'},
        {category: 'Транспорт', word: 'Метро'},
        {category: 'Транспорт', word: 'Такси'},
        {category: 'Транспорт', word: 'Трактор'},
        {category: 'Транспорт', word: 'Лодка'},
        {category: 'Транспорт', word: 'Грузовик'},
        {category: 'Транспорт', word: 'Мотоцикл'},
        {category: 'Транспорт', word: 'Ракета'},
        {category: 'Транспорт', word: 'Катер'},
        {category: 'Транспорт', word: 'Лимузин'},
        {category: 'Транспорт', word: 'Экскаватор'},
        {category: 'Транспорт', word: 'Скутер'},
        {category: 'Транспорт', word: 'Парусник'},

        {category: 'Игрушки', word: 'Мяч'},
        {category: 'Игрушки', word: 'Кукла'},
        {category: 'Игрушки', word: 'Плюшевый мишка'},
        {category: 'Игрушки', word: 'Воздушный змей'},
        {category: 'Игрушки', word: 'Йо-йо'},
        {category: 'Игрушки', word: 'Водяной пистолет'},

        {category: 'Фрукты и ягоды', word: 'Клубника'},
        {category: 'Фрукты и ягоды', word: 'Виноград'},
        {category: 'Фрукты и ягоды', word: 'Апельсин'},
        {category: 'Фрукты и ягоды', word: 'Лимон'},
        {category: 'Фрукты и ягоды', word: 'Груша'},
        {category: 'Фрукты и ягоды', word: 'Вишня'},

        {category: 'Дом', word: 'Кровать'},
        {category: 'Дом', word: 'Холодильник'},
        {category: 'Дом', word: 'Плита'},
        {category: 'Дом', word: 'Окно'},
        {category: 'Дом', word: 'Дверь'},
        {category: 'Дом', word: 'Полка'},

        {category: 'Овощи', word: 'Морковь'},
        {category: 'Овощи', word: 'Огурец'},
        {category: 'Овощи', word: 'Помидор'},
        {category: 'Овощи', word: 'Лук'},
        {category: 'Овощи', word: 'Капуста'},
        {category: 'Овощи', word: 'Тыква'},

        {category: 'Сезоны', word: 'Зима'},
        {category: 'Сезоны', word: 'Весна'},
        {category: 'Сезоны', word: 'Осень'},
        {category: 'Сезоны', word: 'Лето'},
        {category: 'Сезоны', word: 'Дождь'},
        {category: 'Сезоны', word: 'Снег'},

        {category: 'Цветы', word: 'Роза'},
        {category: 'Цветы', word: 'Калла'},
        {category: 'Цветы', word: 'Тюльпан'},
        {category: 'Цветы', word: 'Нарцисс'},
        {category: 'Цветы', word: 'Сирень'},
        {category: 'Цветы', word: 'Жасмин'},

        {category: 'Кухня', word: 'Сковородка'},
        {category: 'Кухня', word: 'Кастрюля'},
        {category: 'Кухня', word: 'Тарелка'},
        {category: 'Кухня', word: 'Ложка'},
        {category: 'Кухня', word: 'Нож'},
        {category: 'Кухня', word: 'Вилка'},

        {category: 'Птицы', word: 'Воробей'},
        {category: 'Птицы', word: 'Синица'},
        {category: 'Птицы', word: 'Дятел'},
        {category: 'Птицы', word: 'Утка'},
        {category: 'Птицы', word: 'Гусь'},
        {category: 'Птицы', word: 'Индейка'},
    ],

    medium: [
        // Настольные игры
        {category: 'Настольные игры', word: 'Шашки'},
        {category: 'Настольные игры', word: 'Монополия'},
        {category: 'Настольные игры', word: 'Мафия'},
        {category: 'Настольные игры', word: 'Дженга'},
        {category: 'Настольные игры', word: 'Домино'},
        {category: 'Настольные игры', word: 'Лото'},

// Морская тематика
        {category: 'Море', word: 'Якорь'},
        {category: 'Море', word: 'Маяк'},
        {category: 'Море', word: 'Штурвал'},
        {category: 'Море', word: 'Буй'},
        {category: 'Море', word: 'Риф'},
        {category: 'Море', word: 'Парус'},


        // Космос (не пересекается с hard-категорией "Космос")
        {category: 'Космические объекты', word: 'Спутник'},
        {category: 'Космические объекты', word: 'Марсоход'},
        {category: 'Космические объекты', word: 'Луноход'},
        {category: 'Космические объекты', word: 'Космическая станция'},
        {category: 'Космические объекты', word: 'Телескоп'},
        {category: 'Космические объекты', word: 'Скафандр'},

        // Сказки
        {category: 'Сказки', word: 'Баба-яга'},
        {category: 'Сказки', word: 'Колобок'},
        {category: 'Сказки', word: 'Золушка'},
        {category: 'Сказки', word: 'Красная Шапочка'},
        {category: 'Сказки', word: 'Джинн'},
        {category: 'Сказки', word: 'Пиноккио'},

        // Город
        {category: 'Город', word: 'Светофор'},
        {category: 'Город', word: 'Фонтан'},
        {category: 'Город', word: 'Небоскрёб'},
        {category: 'Город', word: 'Мост'},
        {category: 'Город', word: 'Пешеходный переход'},
        {category: 'Город', word: 'Остановка'},

        // Путешествия
        {category: 'Путешествия', word: 'Паспорт'},
        {category: 'Путешествия', word: 'Компас'},
        {category: 'Путешествия', word: 'Карта'},
        {category: 'Путешествия', word: 'Палатка'},
        {category: 'Путешествия', word: 'Рюкзак'},
        {category: 'Путешествия', word: 'Бинокль'},

        // Кино
        {category: 'Кино', word: 'Попкорн'},
        {category: 'Кино', word: 'Киноплёнка'},
        {category: 'Кино', word: 'Режиссёр'},
        {category: 'Кино', word: 'Каскадёр'},
        {category: 'Кино', word: 'Сценарий'},
        {category: 'Кино', word: 'Оскар'},

        // Магия
        {category: 'Магия', word: 'Волшебная палочка'},
        {category: 'Магия', word: 'Зелье'},
        {category: 'Магия', word: 'Заклинание'},
        {category: 'Магия', word: 'Кристалл'},
        {category: 'Магия', word: 'Гримуар'},
        {category: 'Магия', word: 'Амулет'},

        {category: 'Профессии', word: 'Повар'},
        {category: 'Профессии', word: 'Пожарный'},
        {category: 'Профессии', word: 'Хирург'},
        {category: 'Профессии', word: 'Космонавт'},
        {category: 'Профессии', word: 'Программист'},
        {category: 'Профессии', word: 'Археолог'},
        {category: 'Профессии', word: 'Детектив'},
        {category: 'Профессии', word: 'Пират'},
        {category: 'Профессии', word: 'Фокусник'},
        {category: 'Профессии', word: 'Бармен'},
        {category: 'Профессии', word: 'Блогер'},
        {category: 'Профессии', word: 'Каскадёр'},
        {category: 'Профессии', word: 'Шахтёр'},
        {category: 'Профессии', word: 'Фермер'},
        {category: 'Профессии', word: 'Диджей'},
        {category: 'Профессии', word: 'Водолаз'},
        {category: 'Профессии', word: 'Пилот'},
        {category: 'Профессии', word: 'Самурай'},

        {category: 'Места', word: 'Больница'},
        {category: 'Места', word: 'Аэропорт'},
        {category: 'Места', word: 'Супермаркет'},
        {category: 'Места', word: 'Зоопарк'},
        {category: 'Места', word: 'Музей'},
        {category: 'Места', word: 'Школа'},
        {category: 'Места', word: 'Цирк'},
        {category: 'Места', word: 'Тюрьма'},
        {category: 'Места', word: 'Аквапарк'},
        {category: 'Места', word: 'Бункер'},
        {category: 'Места', word: 'Кладбище'},
        {category: 'Места', word: 'Лаборатория'},
        {category: 'Места', word: 'Обсерватория'},
        {category: 'Места', word: 'Подземелье'},
        {category: 'Места', word: 'Маяк'},
        {category: 'Места', word: 'Порт'},
        {category: 'Места', word: 'Замок'},
        {category: 'Места', word: 'Пирамида'},

        {category: 'Одежда', word: 'Кроссовки'},
        {category: 'Одежда', word: 'Шляпа'},
        {category: 'Одежда', word: 'Куртка'},
        {category: 'Одежда', word: 'Перчатки'},
        {category: 'Одежда', word: 'Скафандр'},
        {category: 'Одежда', word: 'Плащ'},
        {category: 'Одежда', word: 'Кимоно'},
        {category: 'Одежда', word: 'Корона'},
        {category: 'Одежда', word: 'Мантия'},
        {category: 'Одежда', word: 'Броня'},
        {category: 'Одежда', word: 'Маска'},
        {category: 'Одежда', word: 'Галстук'},
        {category: 'Одежда', word: 'Сапоги'},
        {category: 'Одежда', word: 'Шарф'},

        {category: 'Технологии', word: 'Ноутбук'},
        {category: 'Технологии', word: 'Робот'},
        {category: 'Технологии', word: 'Дрон'},
        {category: 'Технологии', word: 'Наушники'},
        {category: 'Технологии', word: 'Камера'},
        {category: 'Технологии', word: 'Сервер'},
        {category: 'Технологии', word: 'Голограмма'},
        {category: 'Технологии', word: 'Смартфон'},
        {category: 'Технологии', word: 'Спутник'},
        {category: 'Технологии', word: 'Клавиатура'},
        {category: 'Технологии', word: 'Проектор'},
        {category: 'Технологии', word: 'VR-шлем'},
        {category: 'Технологии', word: 'Роутер'},

        {category: 'Развлечения', word: 'Квест'},
        {category: 'Развлечения', word: 'Настолка'},
        {category: 'Развлечения', word: 'Фейерверк'},
        {category: 'Развлечения', word: 'Караоке'},
        {category: 'Развлечения', word: 'Концерт'},
        {category: 'Развлечения', word: 'Кинотеатр'},

        {category: 'Спорт', word: 'Футбол'},
        {category: 'Спорт', word: 'Теннис'},
        {category: 'Спорт', word: 'Бокс'},
        {category: 'Спорт', word: 'Сёрфинг'},
        {category: 'Спорт', word: 'Шахматы'},
        {category: 'Спорт', word: 'Сноуборд'},

        {category: 'Музыкальные инструменты', word: 'Барабан'},
        {category: 'Музыкальные инструменты', word: 'Скрипка'},
        {category: 'Музыкальные инструменты', word: 'Пианино'},
        {category: 'Музыкальные инструменты', word: 'Труба'},
        {category: 'Музыкальные инструменты', word: 'Арфа'},
        {category: 'Музыкальные инструменты', word: 'Саксофон'},

        {category: 'Погода', word: 'Туман'},
        {category: 'Погода', word: 'Метель'},
        {category: 'Погода', word: 'Жара'},
        {category: 'Погода', word: 'Ливень'},
        {category: 'Погода', word: 'Ураган'},
        {category: 'Погода', word: 'Гололёд'},

        {category: 'История и культура', word: 'Рыцарь'},
        {category: 'История и культура', word: 'Викинг'},
        {category: 'История и культура', word: 'Фараон'},
        {category: 'История и культура', word: 'Гладиатор'},
        {category: 'История и культура', word: 'Шаман'},
        {category: 'История и культура', word: 'Монах'},

        {category: 'Природа 2', word: 'Берёза'},
        {category: 'Природа 2', word: 'Клён'},
        {category: 'Природа 2', word: 'Дуб'},
        {category: 'Природа 2', word: 'Осина'},
        {category: 'Природа 2', word: 'Папоротник'},
        {category: 'Природа 2', word: 'Кактус'},

        {category: 'Времена года', word: 'Январь'},
        {category: 'Времена года', word: 'Июль'},
        {category: 'Времена года', word: 'Март'},
        {category: 'Времена года', word: 'Ноябрь'},
        {category: 'Времена года', word: 'Воскресенье'},
        {category: 'Времена года', word: 'Четверг'},

        {category: 'Растения', word: 'Картофель'},
        {category: 'Растения', word: 'Баклажан'},
        {category: 'Растения', word: 'Редиска'},
        {category: 'Растения', word: 'Чеснок'},
        {category: 'Растения', word: 'Базилик'},
        {category: 'Растения', word: 'Мята'},

        {category: 'Аксессуары', word: 'Сумка'},
        {category: 'Аксессуары', word: 'Ремень'},
        {category: 'Аксессуары', word: 'Браслет'},
        {category: 'Аксессуары', word: 'Кольцо'},
        {category: 'Аксессуары', word: 'Заколка'},
        {category: 'Аксессуары', word: 'Брошь'},

        {category: 'Наука', word: 'Атмосфера'},
        {category: 'Наука', word: 'Океан'},
        {category: 'Наука', word: 'География'},
        {category: 'Наука', word: 'Математика'},
        {category: 'Наука', word: 'Химия'},
        {category: 'Наука', word: 'Физика'},
    ],

    hard: [
        {category: 'Интернет', word: 'Лайк'},
        {category: 'Интернет', word: 'Селфи'},
        {category: 'Интернет', word: 'Стример'},
        {category: 'Интернет', word: 'Мем'},
        {category: 'Интернет', word: 'Хештег'},
        {category: 'Интернет', word: 'Подкаст'},
        {category: 'Интернет', word: 'Блогер'},
        {category: 'Интернет', word: 'Эмодзи'},
        {category: 'Интернет', word: 'Вирусное видео'},
        {category: 'Интернет', word: 'Уведомление'},
        // Эмоции
        {category: 'Эмоции', word: 'Радость'},
        {category: 'Эмоции', word: 'Тревога'},
        {category: 'Эмоции', word: 'Зависть'},
        {category: 'Эмоции', word: 'Одиночество'},
        {category: 'Эмоции', word: 'Смущение'},
        {category: 'Эмоции', word: 'Гнев'},
        {category: 'Эмоции', word: 'Эйфория'},
        {category: 'Эмоции', word: 'Стыд'},
        {category: 'Эмоции', word: 'Паника'},
        {category: 'Эмоции', word: 'Надежда'},
        {category: 'Эмоции', word: 'Ностальгия'},
        {category: 'Эмоции', word: 'Разочарование'},
        {category: 'Эмоции', word: 'Вдохновение'},
        {category: 'Эмоции', word: 'Подозрение'},
        {category: 'Эмоции', word: 'Удивление'},
        {category: 'Эмоции', word: 'Обида'},

        // Абстракции
        {category: 'Абстракции', word: 'Свобода'},
        {category: 'Абстракции', word: 'Время'},
        {category: 'Абстракции', word: 'Хаос'},
        {category: 'Абстракции', word: 'Порядок'},
        {category: 'Абстракции', word: 'Судьба'},
        {category: 'Абстракции', word: 'Бесконечность'},
        {category: 'Абстракции', word: 'Иллюзия'},
        {category: 'Абстракции', word: 'Гармония'},
        {category: 'Абстракции', word: 'Энергия'},
        {category: 'Абстракции', word: 'Память'},
        {category: 'Абстракции', word: 'Баланс'},
        {category: 'Абстракции', word: 'Риск'},
        {category: 'Абстракции', word: 'Контроль'},
        {category: 'Абстракции', word: 'Эволюция'},
        {category: 'Абстракции', word: 'Тишина'},
        {category: 'Абстракции', word: 'Импульс'},

        // Фантастика
        {category: 'Фантастика', word: 'Киборг'},
        {category: 'Фантастика', word: 'Дракон'},
        {category: 'Фантастика', word: 'Некромант'},
        {category: 'Фантастика', word: 'Инопланетянин'},
        {category: 'Фантастика', word: 'Мутант'},
        {category: 'Фантастика', word: 'Демон'},
        {category: 'Фантастика', word: 'Андроид'},
        {category: 'Фантастика', word: 'Телепат'},
        {category: 'Фантастика', word: 'Паладин'},
        {category: 'Фантастика', word: 'Виверна'},
        {category: 'Фантастика', word: 'Чародей'},
        {category: 'Фантастика', word: 'Гоблин'},
        {category: 'Фантастика', word: 'Феникс'},
        {category: 'Фантастика', word: 'Лич'},
        {category: 'Фантастика', word: 'Титан'},

        // Сложные объекты
        {category: 'Сложные объекты', word: 'Лабиринт'},
        {category: 'Сложные объекты', word: 'Марионетка'},
        {category: 'Сложные объекты', word: 'Катапульта'},
        {category: 'Сложные объекты', word: 'Тотем'},
        {category: 'Сложные объекты', word: 'Обелиск'},
        {category: 'Сложные объекты', word: 'Механизм'},
        {category: 'Сложные объекты', word: 'Цитадель'},
        {category: 'Сложные объекты', word: 'Реликвия'},
        {category: 'Сложные объекты', word: 'Монолит'},
        {category: 'Сложные объекты', word: 'Турбина'},
        {category: 'Сложные объекты', word: 'Крипта'},
        {category: 'Философия', word: 'Истина'},
        {category: 'Философия', word: 'Мораль'},
        {category: 'Философия', word: 'Сознание'},
        {category: 'Философия', word: 'Сомнение'},
        {category: 'Философия', word: 'Выбор'},
        {category: 'Философия', word: 'Парадокс'},

        {category: 'Социальные явления', word: 'Революция'},
        {category: 'Социальные явления', word: 'Пропаганда'},
        {category: 'Социальные явления', word: 'Паника толпы'},
        {category: 'Социальные явления', word: 'Культ'},
        {category: 'Социальные явления', word: 'Изоляция'},
        {category: 'Социальные явления', word: 'Бунт'},

        {category: 'Мистика', word: 'Проклятие'},
        {category: 'Мистика', word: 'Омен'},
        {category: 'Мистика', word: 'Одержимость'},
        {category: 'Мистика', word: 'Ритуал'},
        {category: 'Мистика', word: 'Пророчество'},
        {category: 'Мистика', word: 'Астрал'},

        {category: 'Космос', word: 'Сингулярность'},
        {category: 'Космос', word: 'Сверхновая'},
        {category: 'Космос', word: 'Червоточина'},
        {category: 'Космос', word: 'Орбита'},
        {category: 'Космос', word: 'Пульсар'},
        {category: 'Космос', word: 'Туманность'},

        {category: 'Психология', word: 'Психоз'},
        {category: 'Психология', word: 'Апатия'},
        {category: 'Психология', word: 'Экзальтация'},
        {category: 'Психология', word: 'Амбивалентность'},
        {category: 'Психология', word: 'Деперсонализация'},
        {category: 'Психология', word: 'Когнитивность'},

        {category: 'Литература', word: 'Метафора'},
        {category: 'Литература', word: 'Символизм'},
        {category: 'Литература', word: 'Аллегория'},
        {category: 'Литература', word: 'Параллель'},
        {category: 'Литература', word: 'Ирония'},
        {category: 'Литература', word: 'А **¿**азия'},

        {category: 'Медицина', word: 'Анатомия'},
        {category: 'Медицина', word: 'Вирус'},
        {category: 'Медицина', word: 'Вакцина'},
        {category: 'Медицина', word: 'Терапия'},
        {category: 'Медицина', word: 'Диагностика'},
        {category: 'Медицина', word: 'Рецепт'},

        {category: 'Архитектура', word: 'Арка'},
        {category: 'Архитектура', word: 'Купол'},
        {category: 'Архитектура', word: 'Фундамент'},
        {category: 'Архитектура', word: 'Колонна'},
        {category: 'Архитектура', word: 'Балкон'},
        {category: 'Архитектура', word: 'Атриум'},

        {category: 'Астрономия', word: 'Галактика'},
        {category: 'Астрономия', word: 'Звезда'},
        {category: 'Астрономия', word: 'Комета'},
        {category: 'Астрономия', word: 'Метеор'},
        {category: 'Астрономия', word: 'Астероид'},
        {category: 'Астрономия', word: 'Экзопланета'},

        {category: 'Экономика', word: 'Бюджет'},
        {category: 'Экономика', word: 'Инфляция'},
        {category: 'Экономика', word: 'Кредит'},
        {category: 'Экономика', word: 'Дивиденды'},
        {category: 'Экономика', word: 'Акции'},
        {category: 'Экономика', word: 'Налог'},

        {category: 'Мифология', word: 'Минотавр'},
        {category: 'Мифология', word: 'Медуза Горгона'},
        {category: 'Мифология', word: 'Кентавр'},
        {category: 'Мифология', word: 'Гидра'},
        {category: 'Мифология', word: 'Сфинкс'},
        {category: 'Мифология', word: 'Цербер'},
        {category: 'Мифология', word: 'Грифон'},
        {category: 'Мифология', word: 'Русалка'},
        {category: 'Мифология', word: 'Пегас'},
        {category: 'Мифология', word: 'Йети'},
    ],
};
