export interface FakeArtistCategory {
  category: string;
  word: string;
}

export type FakeArtistDifficulty = 'easy' | 'medium' | 'hard';



export const FAKE_ARTIST_DATA_BY_DIFFICULTY: Record<FakeArtistDifficulty, FakeArtistCategory[]> = {
  easy: [
    // Животные
    { category: "Животные", word: "Кот" },
    { category: "Животные", word: "Собака" },
    { category: "Животные", word: "Жираф" },
    { category: "Животные", word: "Слон" },
    { category: "Животные", word: "Лев" },
    { category: "Животные", word: "Тигр" },
    { category: "Животные", word: "Пингвин" },
    { category: "Животные", word: "Крокодил" },
    { category: "Животные", word: "Черепаха" },
    { category: "Животные", word: "Обезьяна" },
    { category: "Животные", word: "Зебра" },
    { category: "Животные", word: "Коала" },
    { category: "Животные", word: "Лиса" },
    { category: "Животные", word: "Волк" },
    { category: "Животные", word: "Кролик" },
    { category: "Животные", word: "Бегемот" },
    { category: "Животные", word: "Панда" },
    { category: "Животные", word: "Ёж" },
    { category: "Животные", word: "Белка" },
    { category: "Животные", word: "Петух" },

    // Еда
    { category: "Еда", word: "Пицца" },
    { category: "Еда", word: "Бургер" },
    { category: "Еда", word: "Мороженое" },
    { category: "Еда", word: "Яблоко" },
    { category: "Еда", word: "Банан" },
    { category: "Еда", word: "Торт" },
    { category: "Еда", word: "Суши" },
    { category: "Еда", word: "Картошка фри" },
    { category: "Еда", word: "Арбуз" },
    { category: "Еда", word: "Пончик" },
    { category: "Еда", word: "Хот-дог" },
    { category: "Еда", word: "Спагетти" },
    { category: "Еда", word: "Омлет" },
    { category: "Еда", word: "Кекс" },
    { category: "Еда", word: "Попкорн" },
    { category: "Еда", word: "Шоколад" },
    { category: "Еда", word: "Круассан" },
    { category: "Еда", word: "Пельмени" },
    { category: "Еда", word: "Тако" },

    // Предметы
    { category: "Предметы", word: "Стул" },
    { category: "Предметы", word: "Стол" },
    { category: "Предметы", word: "Лампа" },
    { category: "Предметы", word: "Телефон" },
    { category: "Предметы", word: "Рюкзак" },
    { category: "Предметы", word: "Часы" },
    { category: "Предметы", word: "Зонт" },
    { category: "Предметы", word: "Кружка" },
    { category: "Предметы", word: "Подушка" },
    { category: "Предметы", word: "Ножницы" },
    { category: "Предметы", word: "Микрофон" },
    { category: "Предметы", word: "Гитара" },
    { category: "Предметы", word: "Свеча" },
    { category: "Предметы", word: "Ключ" },
    { category: "Предметы", word: "Чемодан" },
    { category: "Предметы", word: "Шлем" },
    { category: "Предметы", word: "Вентилятор" },
    { category: "Предметы", word: "Молоток" },
    { category: "Предметы", word: "Фотоаппарат" },
    { category: "Предметы", word: "Зеркало" },
    { category: "Предметы", word: "Очки" },
    { category: "Предметы", word: "Будильник" },

    // Природа
    { category: "Природа", word: "Солнце" },
    { category: "Природа", word: "Луна" },
    { category: "Природа", word: "Облако" },
    { category: "Природа", word: "Гора" },
    { category: "Природа", word: "Река" },
    { category: "Природа", word: "Лес" },
    { category: "Природа", word: "Остров" },
    { category: "Природа", word: "Вулкан" },
    { category: "Природа", word: "Пляж" },
    { category: "Природа", word: "Радуга" },
    { category: "Природа", word: "Снежинка" },
    { category: "Природа", word: "Водопад" },
    { category: "Природа", word: "Пустыня" },
    { category: "Природа", word: "Пещера" },
    { category: "Природа", word: "Гроза" },
    { category: "Природа", word: "Каньон" },
    { category: "Природа", word: "Молния" },
    { category: "Природа", word: "Айсберг" },

    // Транспорт
    { category: "Транспорт", word: "Машина" },
    { category: "Транспорт", word: "Автобус" },
    { category: "Транспорт", word: "Велосипед" },
    { category: "Транспорт", word: "Самолёт" },
    { category: "Транспорт", word: "Поезд" },
    { category: "Транспорт", word: "Корабль" },
    { category: "Транспорт", word: "Самокат" },
    { category: "Транспорт", word: "Метро" },
    { category: "Транспорт", word: "Такси" },
    { category: "Транспорт", word: "Трактор" },
    { category: "Транспорт", word: "Лодка" },
    { category: "Транспорт", word: "Грузовик" },
    { category: "Транспорт", word: "Мотоцикл" },
    { category: "Транспорт", word: "Ракета" },
    { category: "Транспорт", word: "Катер" },
    { category: "Транспорт", word: "Лимузин" },
    { category: "Транспорт", word: "Экскаватор" },
    { category: "Транспорт", word: "Скутер" },
    { category: "Транспорт", word: "Парусник" }
  ],

  medium: [
    // Профессии
    { category: "Профессии", word: "Повар" },
    { category: "Профессии", word: "Пожарный" },
    { category: "Профессии", word: "Хирург" },
    { category: "Профессии", word: "Космонавт" },
    { category: "Профессии", word: "Программист" },
    { category: "Профессии", word: "Археолог" },
    { category: "Профессии", word: "Детектив" },
    { category: "Профессии", word: "Пират" },
    { category: "Профессии", word: "Фокусник" },
    { category: "Профессии", word: "Бармен" },
    { category: "Профессии", word: "Блогер" },
    { category: "Профессии", word: "Каскадёр" },
    { category: "Профессии", word: "Шахтёр" },
    { category: "Профессии", word: "Фермер" },
    { category: "Профессии", word: "Диджей" },
    { category: "Профессии", word: "Водолаз" },
    { category: "Профессии", word: "Пилот" },
    { category: "Профессии", word: "Самурай" },

    // Места
    { category: "Места", word: "Больница" },
    { category: "Места", word: "Аэропорт" },
    { category: "Места", word: "Супермаркет" },
    { category: "Места", word: "Зоопарк" },
    { category: "Места", word: "Музей" },
    { category: "Места", word: "Школа" },
    { category: "Места", word: "Цирк" },
    { category: "Места", word: "Тюрьма" },
    { category: "Места", word: "Аквапарк" },
    { category: "Места", word: "Бункер" },
    { category: "Места", word: "Кладбище" },
    { category: "Места", word: "Лаборатория" },
    { category: "Места", word: "Обсерватория" },
    { category: "Места", word: "Подземелье" },
    { category: "Места", word: "Маяк" },
    { category: "Места", word: "Порт" },
    { category: "Места", word: "Замок" },
    { category: "Места", word: "Пирамида" },

    // Одежда
    { category: "Одежда", word: "Кроссовки" },
    { category: "Одежда", word: "Шляпа" },
    { category: "Одежда", word: "Куртка" },
    { category: "Одежда", word: "Перчатки" },
    { category: "Одежда", word: "Скафандр" },
    { category: "Одежда", word: "Плащ" },
    { category: "Одежда", word: "Кимоно" },
    { category: "Одежда", word: "Корона" },
    { category: "Одежда", word: "Мантия" },
    { category: "Одежда", word: "Броня" },
    { category: "Одежда", word: "Маска" },
    { category: "Одежда", word: "Галстук" },
    { category: "Одежда", word: "Сапоги" },
    { category: "Одежда", word: "Шарф" },

    // Технологии
    { category: "Технологии", word: "Ноутбук" },
    { category: "Технологии", word: "Робот" },
    { category: "Технологии", word: "Дрон" },
    { category: "Технологии", word: "Наушники" },
    { category: "Технологии", word: "Камера" },
    { category: "Технологии", word: "Сервер" },
    { category: "Технологии", word: "Голограмма" },
    { category: "Технологии", word: "Смартфон" },
    { category: "Технологии", word: "Спутник" },
    { category: "Технологии", word: "Клавиатура" },
    { category: "Технологии", word: "Проектор" },
    { category: "Технологии", word: "VR-шлем" },
    { category: "Технологии", word: "Роутер" },

    // Развлечения
    { category: "Развлечения", word: "Квест" },
    { category: "Развлечения", word: "Настолка" },
    { category: "Развлечения", word: "Фейерверк" },
    { category: "Развлечения", word: "Караоке" },
    { category: "Развлечения", word: "Концерт" },
    { category: "Развлечения", word: "Кинотеатр" }
  ],

  hard: [
    // Эмоции
    { category: "Эмоции", word: "Радость" },
    { category: "Эмоции", word: "Тревога" },
    { category: "Эмоции", word: "Зависть" },
    { category: "Эмоции", word: "Одиночество" },
    { category: "Эмоции", word: "Смущение" },
    { category: "Эмоции", word: "Гнев" },
    { category: "Эмоции", word: "Эйфория" },
    { category: "Эмоции", word: "Стыд" },
    { category: "Эмоции", word: "Паника" },
    { category: "Эмоции", word: "Надежда" },
    { category: "Эмоции", word: "Ностальгия" },
    { category: "Эмоции", word: "Разочарование" },
    { category: "Эмоции", word: "Вдохновение" },
    { category: "Эмоции", word: "Подозрение" },
    { category: "Эмоции", word: "Удивление" },
    { category: "Эмоции", word: "Обида" },

    // Абстракции
    { category: "Абстракции", word: "Свобода" },
    { category: "Абстракции", word: "Время" },
    { category: "Абстракции", word: "Хаос" },
    { category: "Абстракции", word: "Порядок" },
    { category: "Абстракции", word: "Судьба" },
    { category: "Абстракции", word: "Бесконечность" },
    { category: "Абстракции", word: "Иллюзия" },
    { category: "Абстракции", word: "Гармония" },
    { category: "Абстракции", word: "Энергия" },
    { category: "Абстракции", word: "Память" },
    { category: "Абстракции", word: "Баланс" },
    { category: "Абстракции", word: "Риск" },
    { category: "Абстракции", word: "Контроль" },
    { category: "Абстракции", word: "Эволюция" },
    { category: "Абстракции", word: "Тишина" },
    { category: "Абстракции", word: "Импульс" },

    // Фантастика
    { category: "Фантастика", word: "Киборг" },
    { category: "Фантастика", word: "Дракон" },
    { category: "Фантастика", word: "Некромант" },
    { category: "Фантастика", word: "Инопланетянин" },
    { category: "Фантастика", word: "Мутант" },
    { category: "Фантастика", word: "Демон" },
    { category: "Фантастика", word: "Андроид" },
    { category: "Фантастика", word: "Телепат" },
    { category: "Фантастика", word: "Паладин" },
    { category: "Фантастика", word: "Виверна" },
    { category: "Фантастика", word: "Чародей" },
    { category: "Фантастика", word: "Гоблин" },
    { category: "Фантастика", word: "Феникс" },
    { category: "Фантастика", word: "Лич" },
    { category: "Фантастика", word: "Титан" },

    // Сложные объекты
    { category: "Сложные объекты", word: "Лабиринт" },
    { category: "Сложные объекты", word: "Марионетка" },
    { category: "Сложные объекты", word: "Катапульта" },
    { category: "Сложные объекты", word: "Тотем" },
    { category: "Сложные объекты", word: "Обелиск" },
    { category: "Сложные объекты", word: "Механизм" },
    { category: "Сложные объекты", word: "Цитадель" },
    { category: "Сложные объекты", word: "Реликвия" },
    { category: "Сложные объекты", word: "Монолит" },
    { category: "Сложные объекты", word: "Турбина" },
    { category: "Сложные объекты", word: "Крипта" }
  ]
};
