export interface TabooCard {
  id: number;
  word: string;
  required: string[];
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_REVERSE_CARDS: readonly TabooCard[] = [
  // ── EASY ─────────────────────────────────────────────────────────────────
  { id: 1,  difficulty: 'easy', word: 'САМОЛЁТ',    required: ['крылья', 'небо', 'пилот', 'лететь'] },
  { id: 2,  difficulty: 'easy', word: 'ПИЦЦА',      required: ['тесто', 'сыр', 'томат', 'Италия'] },
  { id: 3,  difficulty: 'easy', word: 'КОШКА',      required: ['мяукать', 'шерсть', 'коготь', 'мурлыкать'] },
  { id: 4,  difficulty: 'easy', word: 'ТЕЛЕФОН',    required: ['звонить', 'экран', 'заряд', 'карман'] },
  { id: 5,  difficulty: 'easy', word: 'МОРЕ',       required: ['волна', 'соль', 'пляж', 'горизонт'] },
  { id: 6,  difficulty: 'easy', word: 'КНИГА',      required: ['страница', 'читать', 'автор', 'полка'] },
  { id: 7,  difficulty: 'easy', word: 'СНЕГ',       required: ['зима', 'белый', 'таять', 'санки'] },
  { id: 8,  difficulty: 'easy', word: 'СОБАКА',     required: ['лаять', 'хвост', 'поводок', 'кость'] },
  { id: 9,  difficulty: 'easy', word: 'КОФЕ',       required: ['чашка', 'утро', 'зерно', 'горький'] },
  { id: 10, difficulty: 'easy', word: 'ДОМ',        required: ['стена', 'крыша', 'дверь', 'семья'] },
  { id: 11, difficulty: 'easy', word: 'ВЕЛОСИПЕД',  required: ['колесо', 'педаль', 'шлем', 'ехать'] },
  { id: 12, difficulty: 'easy', word: 'ДОЖДЬ',      required: ['зонт', 'лужа', 'облако', 'капля'] },
  { id: 13, difficulty: 'easy', word: 'МОРОЖЕНОЕ',  required: ['холодный', 'лето', 'вафля', 'таять'] },
  { id: 14, difficulty: 'easy', word: 'ПОЕЗД',      required: ['рельсы', 'вагон', 'перрон', 'купе'] },
  { id: 15, difficulty: 'easy', word: 'ГИТАРА',     required: ['струна', 'играть', 'аккорд', 'дерево'] },
  { id: 16, difficulty: 'easy', word: 'ВРАЧ',       required: ['больница', 'укол', 'таблетка', 'белый'] },
  { id: 17, difficulty: 'easy', word: 'ШКОЛА',      required: ['урок', 'учитель', 'доска', 'оценка'] },
  { id: 18, difficulty: 'easy', word: 'ЛЕТО',       required: ['жара', 'отпуск', 'солнце', 'арбуз'] },
  { id: 19, difficulty: 'easy', word: 'ТОРТ',       required: ['крем', 'праздник', 'свеча', 'шоколад'] },
  { id: 20, difficulty: 'easy', word: 'ГОРЫ',       required: ['вершина', 'снег', 'воздух', 'крутой'] },
  { id: 21, difficulty: 'easy', word: 'ФОНТАН',     required: ['вода', 'площадь', 'брызги', 'монета'] },
  { id: 22, difficulty: 'easy', word: 'ПЛЯЖ',       required: ['песок', 'загар', 'полотенце', 'ракушка'] },
  { id: 23, difficulty: 'easy', word: 'АПТЕКА',     required: ['таблетка', 'рецепт', 'витамин', 'кашель'] },
  { id: 24, difficulty: 'easy', word: 'РЫНОК',      required: ['торговать', 'цена', 'свежий', 'овощ'] },
  { id: 25, difficulty: 'easy', word: 'ЛИФТ',       required: ['этаж', 'кнопка', 'подниматься', 'тесный'] },
  { id: 26, difficulty: 'easy', word: 'ЗЕРКАЛО',    required: ['отражение', 'смотреть', 'стекло', 'ванная'] },
  { id: 27, difficulty: 'easy', word: 'МАГАЗИН',    required: ['покупать', 'касса', 'полка', 'корзина'] },
  { id: 28, difficulty: 'easy', word: 'БАНАН',      required: ['желтый', 'тропики', 'обезьяна', 'гнуть'] },
  { id: 29, difficulty: 'easy', word: 'ЧАСЫ',       required: ['стрелка', 'тикать', 'запястье', 'время'] },
  { id: 30, difficulty: 'easy', word: 'ОКНО',       required: ['стекло', 'рама', 'вид', 'открыть'] },

  // ── MEDIUM ───────────────────────────────────────────────────────────────
  { id: 31, difficulty: 'medium', word: 'ЗАВИСТЬ',       required: ['сосед', 'машина', 'успех', 'зелёный', 'молчать'] },
  { id: 32, difficulty: 'medium', word: 'ЛОЖЬ',           required: ['правда', 'глаза', 'скрыть', 'стыд', 'верить'] },
  { id: 33, difficulty: 'medium', word: 'ПАМЯТЬ',         required: ['забыть', 'фото', 'детство', 'запах', 'вспомнить'] },
  { id: 34, difficulty: 'medium', word: 'УСТАЛОСТЬ',      required: ['диван', 'вечер', 'работа', 'веки', 'зевать'] },
  { id: 35, difficulty: 'medium', word: 'СКУКА',          required: ['потолок', 'ждать', 'окно', 'ничего', 'зевать'] },
  { id: 36, difficulty: 'medium', word: 'ДРУЖБА',         required: ['доверие', 'вместе', 'помочь', 'смеяться', 'молчать'] },
  { id: 37, difficulty: 'medium', word: 'СТРАХ',          required: ['темнота', 'сердце', 'избегать', 'детство', 'дрожать'] },
  { id: 38, difficulty: 'medium', word: 'СЕКРЕТ',         required: ['шептать', 'никому', 'тайна', 'доверить', 'узнать'] },
  { id: 39, difficulty: 'medium', word: 'НОСТАЛЬГИЯ',     required: ['детство', 'запах', 'вернуться', 'больно', 'раньше'] },
  { id: 40, difficulty: 'medium', word: 'ИНТУИЦИЯ',       required: ['чувствовать', 'предчувствие', 'знать', 'объяснить', 'мозг'] },
  { id: 41, difficulty: 'medium', word: 'УСПЕХ',          required: ['труд', 'цена', 'чужой', 'путь', 'вершина'] },
  { id: 42, difficulty: 'medium', word: 'ПРИВЫЧКА',       required: ['утро', 'автоматически', 'трудно', 'бросить', 'повторять'] },
  { id: 43, difficulty: 'medium', word: 'ВДОХНОВЕНИЕ',    required: ['идея', 'внезапно', 'творить', 'пропасть', 'художник'] },
  { id: 44, difficulty: 'medium', word: 'СМЕЛОСТЬ',       required: ['страх', 'прыгнуть', 'несмотря', 'дрожать', 'сделать'] },
  { id: 45, difficulty: 'medium', word: 'ОДИНОЧЕСТВО',    required: ['толпа', 'рядом', 'тихо', 'позвонить', 'всегда'] },
  { id: 46, difficulty: 'medium', word: 'ДЕНЬГИ',         required: ['бумажник', 'банк', 'считать', 'нехватка', 'купить'] },
  { id: 47, difficulty: 'medium', word: 'СЛУЧАЙ',         required: ['совпадение', 'неожиданно', 'везение', 'встреча', 'цепочка'] },
  { id: 48, difficulty: 'medium', word: 'СТРЕСС',         required: ['дышать', 'дедлайн', 'голова', 'сжать', 'выход'] },
  { id: 49, difficulty: 'medium', word: 'ОЖИДАНИЕ',       required: ['тикать', 'надежда', 'минута', 'бесконечность', 'момент'] },
  { id: 50, difficulty: 'medium', word: 'ПРИВЯЗАННОСТЬ',  required: ['отпустить', 'рядом', 'потерять', 'тепло', 'зависеть'] },
  { id: 51, difficulty: 'medium', word: 'ПЕРЕМЕНА',       required: ['боятся', 'неизбежно', 'старое', 'вчера', 'расти'] },
  { id: 52, difficulty: 'medium', word: 'ОПОЗДАНИЕ',      required: ['минута', 'пробка', 'бежать', 'извиниться', 'снова'] },
  { id: 53, difficulty: 'medium', word: 'ДЕТСТВО',        required: ['двор', 'велосипед', 'лето', 'взрослый', 'никогда'] },
  { id: 54, difficulty: 'medium', word: 'ТАЛАНТ',         required: ['рождение', 'практика', 'зависть', 'скрытый', 'раскрыть'] },
  { id: 55, difficulty: 'medium', word: 'ТРЕВОГА',        required: ['завтра', 'сердце', 'ночь', 'причина', 'думать'] },

  // ── HARD ─────────────────────────────────────────────────────────────────
  { id: 56, difficulty: 'hard', word: 'ТИШИНА',       required: ['крик', 'музыка', 'взрыв', 'толпа', 'шум'] },
  { id: 57, difficulty: 'hard', word: 'ПУСТОТА',      required: ['полный', 'смысл', 'внутри', 'кричать', 'один'] },
  { id: 58, difficulty: 'hard', word: 'СВОБОДА',      required: ['тюрьма', 'птица', 'выбор', 'цепь', 'отпустить'] },
  { id: 59, difficulty: 'hard', word: 'ПРАВДА',       required: ['горькая', 'скрывать', 'больно', 'знать', 'ложь'] },
  { id: 60, difficulty: 'hard', word: 'НАДЕЖДА',      required: ['конец', 'темнота', 'умерла', 'ждать', 'свет'] },
  { id: 61, difficulty: 'hard', word: 'ПРОШЛОЕ',      required: ['вернуть', 'изменить', 'тень', 'жить', 'напоминать'] },
  { id: 62, difficulty: 'hard', word: 'ГРАНИЦА',      required: ['нарушить', 'линия', 'другой', 'невидимый', 'охрана'] },
  { id: 63, difficulty: 'hard', word: 'СМЫСЛ',        required: ['жизнь', 'найти', 'потерять', 'зачем', 'внутри'] },
  { id: 64, difficulty: 'hard', word: 'ДОВЕРИЕ',      required: ['предать', 'строить', 'слепо', 'хрупкое', 'проверить'] },
  { id: 65, difficulty: 'hard', word: 'ОТЧАЯНИЕ',     required: ['выход', 'конец', 'последнее', 'сила', 'темно'] },
  { id: 66, difficulty: 'hard', word: 'ЗАБВЕНИЕ',     required: ['помнить', 'стереть', 'боль', 'исчезнуть', 'специально'] },
  { id: 67, difficulty: 'hard', word: 'СЛУЧАЙНОСТЬ',  required: ['план', 'судьба', 'нарочно', 'произошло', 'связь'] },
  { id: 68, difficulty: 'hard', word: 'ВРЕМЯ',        required: ['часы', 'спешить', 'потерять', 'назад', 'стрелка'] },
  { id: 69, difficulty: 'hard', word: 'ВОЗРАСТ',      required: ['зеркало', 'моложе', 'опыт', 'цифра', 'внутри'] },
  { id: 70, difficulty: 'hard', word: 'ВЛАСТЬ',       required: ['слабый', 'корона', 'подчиняться', 'страх', 'один'] },

  // ── EASY (batch 2) ───────────────────────────────────────────────────────
  { id: 71,  difficulty: 'easy', word: 'МАШИНА',      required: ['руль', 'дорога', 'бензин', 'ехать'] },
  { id: 72,  difficulty: 'easy', word: 'КОМПЬЮТЕР',   required: ['экран', 'мышь', 'клавиша', 'интернет'] },
  { id: 73,  difficulty: 'easy', word: 'ЛУНА',        required: ['ночь', 'круглая', 'светить', 'тёмный'] },
  { id: 74,  difficulty: 'easy', word: 'РЕСТОРАН',    required: ['меню', 'официант', 'столик', 'заказать'] },
  { id: 75,  difficulty: 'easy', word: 'ПАРК',        required: ['дерево', 'прогулка', 'скамейка', 'голубь'] },
  { id: 76,  difficulty: 'easy', word: 'МЯЧ',         required: ['круглый', 'пинать', 'команда', 'прыгать'] },
  { id: 77,  difficulty: 'easy', word: 'ШАПКА',       required: ['голова', 'зима', 'тёплый', 'вязать'] },
  { id: 78,  difficulty: 'easy', word: 'ГРИБ',        required: ['лес', 'корзина', 'собирать', 'осень'] },
  { id: 79,  difficulty: 'easy', word: 'КЛУБНИКА',    required: ['красный', 'сладкий', 'поляна', 'варенье'] },
  { id: 80,  difficulty: 'easy', word: 'ТАКСИ',       required: ['ехать', 'вызвать', 'водитель', 'счётчик'] },
  { id: 81,  difficulty: 'easy', word: 'КИНО',        required: ['фильм', 'зал', 'попкорн', 'темнота'] },
  { id: 82,  difficulty: 'easy', word: 'РЮКЗАК',      required: ['нести', 'плечи', 'школа', 'молния'] },
  { id: 83,  difficulty: 'easy', word: 'ПОДУШКА',     required: ['спать', 'мягкий', 'кровать', 'пух'] },
  { id: 84,  difficulty: 'easy', word: 'ДУШ',         required: ['вода', 'мыться', 'кран', 'утро'] },
  { id: 85,  difficulty: 'easy', word: 'МАСКА',       required: ['лицо', 'прятать', 'карнавал', 'защита'] },
  { id: 86,  difficulty: 'easy', word: 'ПАСПОРТ',     required: ['документ', 'граница', 'фото', 'виза'] },
  { id: 87,  difficulty: 'easy', word: 'ПАЛЬТО',      required: ['длинный', 'зима', 'карман', 'пуговица'] },
  { id: 88,  difficulty: 'easy', word: 'ГАЗЕТА',      required: ['новости', 'бумага', 'читать', 'утро'] },
  { id: 89,  difficulty: 'easy', word: 'СТАКАН',      required: ['пить', 'стекло', 'наполнить', 'круглый'] },
  { id: 90,  difficulty: 'easy', word: 'МАРШРУТКА',   required: ['остановка', 'ехать', 'толкаться', 'монета'] },

  // ── MEDIUM (batch 2) ─────────────────────────────────────────────────────
  { id: 91,  difficulty: 'medium', word: 'РАЗОЧАРОВАНИЕ', required: ['ожидать', 'обещать', 'не оправдать', 'пустота', 'горький'] },
  { id: 92,  difficulty: 'medium', word: 'ГОРДОСТЬ',       required: ['достижение', 'выше', 'чужой', 'взгляд', 'грудь'] },
  { id: 93,  difficulty: 'medium', word: 'ЛЮБОПЫТСТВО',    required: ['запрет', 'нос', 'узнать', 'тайна', 'кошка'] },
  { id: 94,  difficulty: 'medium', word: 'ТЕРПЕНИЕ',       required: ['ждать', 'бесконечность', 'награда', 'трудно', 'момент'] },
  { id: 95,  difficulty: 'medium', word: 'ПРОЩЕНИЕ',       required: ['обида', 'забыть', 'принять', 'просить', 'легче'] },
  { id: 96,  difficulty: 'medium', word: 'РЕВНОСТЬ',       required: ['чужой', 'взгляд', 'свой', 'боль', 'подозревать'] },
  { id: 97,  difficulty: 'medium', word: 'СОМНЕНИЕ',       required: ['уверен', 'снова', 'решение', 'правильно', 'завтра'] },
  { id: 98,  difficulty: 'medium', word: 'ВИНА',           required: ['виноват', 'простить', 'внутри', 'тяжело', 'знаешь'] },
  { id: 99,  difficulty: 'medium', word: 'МЕЧТА',          required: ['далёко', 'цель', 'верить', 'когда-нибудь', 'спать'] },
  { id: 100, difficulty: 'medium', word: 'ОБИДА',          required: ['сказал', 'молчать', 'помнить', 'слёзы', 'не думал'] },
  { id: 101, difficulty: 'medium', word: 'АЗАРТ',          required: ['ставка', 'риск', 'выиграть', 'адреналин', 'снова'] },
  { id: 102, difficulty: 'medium', word: 'РАСТЕРЯННОСТЬ',  required: ['где', 'зачем', 'стоять', 'вокруг', 'назад'] },
  { id: 103, difficulty: 'medium', word: 'РАЗДРАЖЕНИЕ',    required: ['снова', 'всегда', 'почему', 'дышать', 'маленький'] },
  { id: 104, difficulty: 'medium', word: 'БЛАГОДАРНОСТЬ',  required: ['получить', 'сказать', 'редко', 'чувствовать', 'должен'] },
  { id: 105, difficulty: 'medium', word: 'СКРОМНОСТЬ',     required: ['лучший', 'молчать', 'другие', 'смотреть', 'кивать'] },

  // ── HARD (batch 2) ───────────────────────────────────────────────────────
  { id: 106, difficulty: 'hard', word: 'ПОТЕРЯ',           required: ['найти', 'было', 'больше', 'никогда', 'рядом'] },
  { id: 107, difficulty: 'hard', word: 'ПРИНЯТИЕ',         required: ['бороться', 'другой', 'остановиться', 'есть', 'быть'] },
  { id: 108, difficulty: 'hard', word: 'РАВНОДУШИЕ',       required: ['важно', 'чувствовать', 'раньше', 'вокруг', 'нет'] },
  { id: 109, difficulty: 'hard', word: 'ЧЕСТНОСТЬ',        required: ['больно', 'выгода', 'признать', 'зеркало', 'риск'] },
  { id: 110, difficulty: 'hard', word: 'ЗАВИСИМОСТЬ',      required: ['хотеть', 'остановиться', 'снова', 'контроль', 'нужно'] },
  { id: 111, difficulty: 'hard', word: 'ВЕЧНОСТЬ',         required: ['конец', 'мгновение', 'всегда', 'остановить', 'существовать'] },
  { id: 112, difficulty: 'hard', word: 'НЕОПРЕДЕЛЁННОСТЬ', required: ['план', 'ясно', 'завтра', 'ждать', 'может'] },
  { id: 113, difficulty: 'hard', word: 'СУДЬБА',           required: ['случайно', 'выбор', 'написано', 'изменить', 'знак'] },
  { id: 114, difficulty: 'hard', word: 'СОЖАЛЕНИЕ',        required: ['раньше', 'другой', 'нельзя', 'вернуть', 'если'] },
  { id: 115, difficulty: 'hard', word: 'ОТВЕТСТВЕННОСТЬ',  required: ['виноват', 'решение', 'взять', 'нести', 'чужое'] },

  // ── EASY (batch 3) ───────────────────────────────────────────────────────
  { id: 116, difficulty: 'easy', word: 'ЗАМОК',       required: ['ключ', 'закрыть', 'дверь', 'башня'] },
  { id: 117, difficulty: 'easy', word: 'РАДУГА',      required: ['дождь', 'семь', 'цвет', 'красивый'] },
  { id: 118, difficulty: 'easy', word: 'ТЕТРАДЬ',     required: ['писать', 'линейка', 'школа', 'ручка'] },
  { id: 119, difficulty: 'easy', word: 'ВАННА',       required: ['вода', 'мыться', 'пена', 'тёплый'] },
  { id: 120, difficulty: 'easy', word: 'ДИВАН',       required: ['сидеть', 'мягкий', 'телевизор', 'лежать'] },
  { id: 121, difficulty: 'easy', word: 'КЛЮЧ',        required: ['замок', 'открыть', 'потерять', 'металл'] },
  { id: 122, difficulty: 'easy', word: 'КОНВЕРТ',     required: ['письмо', 'марка', 'запечатать', 'отправить'] },
  { id: 123, difficulty: 'easy', word: 'ОЧКИ',        required: ['видеть', 'стекло', 'нос', 'читать'] },
  { id: 124, difficulty: 'easy', word: 'ПЕРЧАТКИ',    required: ['руки', 'зима', 'пара', 'надевать'] },
  { id: 125, difficulty: 'easy', word: 'АПЕЛЬСИН',    required: ['круглый', 'сочный', 'кожура', 'витамин'] },
  { id: 126, difficulty: 'easy', word: 'НОЖНИЦЫ',     required: ['резать', 'острый', 'бумага', 'металл'] },
  { id: 127, difficulty: 'easy', word: 'КРЕСЛО',      required: ['сидеть', 'мягкий', 'кабинет', 'откидываться'] },
  { id: 128, difficulty: 'easy', word: 'СВЕЧА',       required: ['огонь', 'темнота', 'воск', 'плавить'] },
  { id: 129, difficulty: 'easy', word: 'БУДИЛЬНИК',   required: ['звонить', 'утро', 'не спать', 'кнопка'] },
  { id: 130, difficulty: 'easy', word: 'РЮМКА',       required: ['стекло', 'пить', 'маленький', 'звенеть'] },
  { id: 131, difficulty: 'easy', word: 'САЛАТ',       required: ['нарезать', 'зелёный', 'заправка', 'вилка'] },
  { id: 132, difficulty: 'easy', word: 'ПРИНТЕР',     required: ['бумага', 'печатать', 'офис', 'картридж'] },
  { id: 133, difficulty: 'easy', word: 'БАТАРЕЙКА',   required: ['заряд', 'круглый', 'пульт', 'менять'] },
  { id: 134, difficulty: 'easy', word: 'КОРЗИНА',     required: ['нести', 'плести', 'бросить', 'наполнить'] },
  { id: 135, difficulty: 'easy', word: 'ЗОНТ',        required: ['держать', 'мокрый', 'раскрыть', 'ручка'] },

  // ── MEDIUM (batch 3) ─────────────────────────────────────────────────────
  { id: 136, difficulty: 'medium', word: 'РЕШИМОСТЬ',    required: ['страх', 'назад', 'шаг', 'несмотря', 'твёрдо'] },
  { id: 137, difficulty: 'medium', word: 'АПАТИЯ',        required: ['делать', 'хотеть', 'диван', 'вставать', 'зачем'] },
  { id: 138, difficulty: 'medium', word: 'СОЧУВСТВИЕ',    required: ['чужая', 'боль', 'чувствовать', 'рядом', 'понять'] },
  { id: 139, difficulty: 'medium', word: 'УПРЯМСТВО',     required: ['нет', 'правда', 'другой', 'доказать', 'стоять'] },
  { id: 140, difficulty: 'medium', word: 'ВЫБОР',         required: ['нельзя', 'оба', 'решать', 'потерять', 'остаться'] },
  { id: 141, difficulty: 'medium', word: 'МАНИПУЛЯЦИЯ',   required: ['чувствовать', 'хотеть', 'незаметно', 'польза', 'согласиться'] },
  { id: 142, difficulty: 'medium', word: 'ЗРЕЛОСТЬ',      required: ['возраст', 'отвечать', 'решать', 'ребёнок', 'сам'] },
  { id: 143, difficulty: 'medium', word: 'ЛЮБОВЬ',        required: ['сказать', 'потерять', 'первый', 'слова', 'всё'] },
  { id: 144, difficulty: 'medium', word: 'КОНФЛИКТ',      required: ['молчать', 'взорваться', 'виноват', 'разрешить', 'между'] },
  { id: 145, difficulty: 'medium', word: 'ПРОГРЕСС',      required: ['назад', 'медленно', 'новый', 'изменить', 'движение'] },
  { id: 146, difficulty: 'medium', word: 'ПРИВИЛЕГИЯ',    required: ['заслуга', 'другой', 'позволить', 'иметь', 'редко'] },
  { id: 147, difficulty: 'medium', word: 'ЗАГАДКА',       required: ['отгадать', 'спрятать', 'ключ', 'думать', 'странный'] },
  { id: 148, difficulty: 'medium', word: 'НАДМЕННОСТЬ',   required: ['выше', 'смотреть', 'другой', 'нос', 'молчать'] },
  { id: 149, difficulty: 'medium', word: 'ИНТЕРЕС',       required: ['узнать', 'больше', 'начать', 'почему', 'задать'] },
  { id: 150, difficulty: 'medium', word: 'НАДЛОМ',        required: ['держаться', 'внутри', 'трещина', 'тихо', 'видно'] },

  // ── HARD (batch 3) ───────────────────────────────────────────────────────
  { id: 151, difficulty: 'hard', word: 'БЕССИЛИЕ',       required: ['хотеть', 'мочь', 'стена', 'кричать', 'нельзя'] },
  { id: 152, difficulty: 'hard', word: 'ИЛЛЮЗИЯ',        required: ['реальность', 'видеть', 'исчезнуть', 'верить', 'обман'] },
  { id: 153, difficulty: 'hard', word: 'САМООБМАН',      required: ['знать', 'убедить', 'видеть', 'удобно', 'правда'] },
  { id: 154, difficulty: 'hard', word: 'ПРОТИВОРЕЧИЕ',   required: ['одновременно', 'да', 'нет', 'оба', 'внутри'] },
  { id: 155, difficulty: 'hard', word: 'НЕПОСТОЯНСТВО',  required: ['вчера', 'сегодня', 'верить', 'снова', 'другой'] },
  { id: 156, difficulty: 'hard', word: 'ХАОС',           required: ['порядок', 'план', 'сам', 'система', 'вокруг'] },
  { id: 157, difficulty: 'hard', word: 'ОСОЗНАНИЕ',      required: ['знал', 'раньше', 'момент', 'ясно', 'теперь'] },
  { id: 158, difficulty: 'hard', word: 'ИДЕНТИЧНОСТЬ',   required: ['кто', 'другой', 'маска', 'роль', 'внутри'] },
  { id: 159, difficulty: 'hard', word: 'БЕСКОНЕЧНОСТЬ',  required: ['конец', 'начало', 'считать', 'остановить', 'круг'] },
  { id: 160, difficulty: 'hard', word: 'ПОДЛИННОСТЬ',    required: ['притворяться', 'настоящее', 'скрыть', 'видно', 'редко'] },
];

export function getNextTabooCard(
  difficulty: 'easy' | 'medium' | 'hard',
  usedIds: ReadonlySet<number>,
): TabooCard {
  const pool = TABOO_REVERSE_CARDS.filter(c => c.difficulty === difficulty && !usedIds.has(c.id));
  const src = pool.length > 0 ? pool : TABOO_REVERSE_CARDS.filter(c => c.difficulty === difficulty);
  return src[Math.floor(Math.random() * src.length)];
}
