import type { GameTheme } from '../types';

// RGB-каналы — ЕДИНСТВЕННЫЙ источник цветов палитры. @theme-токены
// (--color-premium-*) генерируются отсюда скриптом scripts/generateThemeColors.ts
// в src/app/styles/premium-colors.css (автоматически перед dev и build,
// вручную — npm run theme:gen). Менять цвет — только здесь.
export const PREMIUM_RGB = {
  red: '255,46,77',
  green: '0,216,138',
  sky: '31,182,255',
  blue: '63,123,255',
  orange: '255,138,31',
  yellow: '255,204,31',
  purple: '199,123,255',
  pink: '255,46,180',
  cyan: '0,229,255',
  lime: '132,204,22',
  teal: '20,184,166',
  indigo: '99,102,241',
} as const satisfies Record<GameTheme, string>;

// Helper for inline style props (boxShadow, filter, background) — not for className
export const rgba = (color: GameTheme, alpha: number): string =>
  `rgba(${PREMIUM_RGB[color]},${alpha})`;

// ─── Theme token map ───────────────────────────────────────────────────────────

export interface ThemeTokens {
  // Single-class utilities
  text: string;
  solid: string;
  bg5: string;
  bg10: string;
  bg20: string;
  border20: string;
  border30: string;
  border40: string;
  // Compound class groups
  indexBg: string; // player index badge
  activeOption: string; // active setting button (UniversalGameSettings)
  button: string; // primary action button
  gradient: string; // radial ambient gradient
  focus: string; // input focus ring
  addHover: string; // add-player button hover
  closeHover: string; // close/remove button hover
  glow: string; // shadow glow (InstructionsModal)
  headerTheme: string; // GameHeader icon border + text
}

// ─── Arbitrary-value compound tokens ──────────────────────────────────────────
// These three fields contain Tailwind arbitrary values ([...]) that cannot be
// detected from template literals — so they stay as literal strings here.
// The remaining 14 regular fields are generated by makeSimpleTokens() below,
// covered by @source inline() in index.css.
const ARBITRARY: Record<GameTheme, Pick<ThemeTokens, 'activeOption' | 'button' | 'gradient'>> = {
  red: {
    activeOption:
      'bg-premium-red/10 border-premium-red/40 text-premium-red shadow-[0_0_20px_rgba(255,46,77,0.12)]',
    button:
      'bg-premium-red hover:bg-[#ff4d6a] active:scale-95 shadow-[0_20px_50px_rgba(255,46,77,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(255,46,77,0.15),transparent_70%)]',
  },
  green: {
    activeOption:
      'bg-premium-green/10 border-premium-green/40 text-premium-green shadow-[0_0_20px_rgba(0,216,138,0.12)]',
    button:
      'bg-premium-green hover:bg-[#1ae599] active:scale-95 shadow-[0_20px_50px_rgba(0,216,138,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(0,216,138,0.15),transparent_70%)]',
  },
  sky: {
    activeOption:
      'bg-premium-sky/10 border-premium-sky/40 text-premium-sky shadow-[0_0_20px_rgba(31,182,255,0.12)]',
    button:
      'bg-premium-sky hover:bg-[#3ac1ff] active:scale-95 shadow-[0_20px_50px_rgba(31,182,255,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(31,182,255,0.15),transparent_70%)]',
  },
  blue: {
    activeOption:
      'bg-premium-blue/10 border-premium-blue/40 text-premium-blue shadow-[0_0_20px_rgba(63,123,255,0.12)]',
    button:
      'bg-premium-blue hover:bg-[#6699ff] active:scale-95 shadow-[0_20px_50px_rgba(63,123,255,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(63,123,255,0.15),transparent_70%)]',
  },
  orange: {
    activeOption:
      'bg-premium-orange/10 border-premium-orange/40 text-premium-orange shadow-[0_0_20px_rgba(255,138,31,0.12)]',
    button:
      'bg-premium-orange hover:bg-[#ffa14d] active:scale-95 shadow-[0_20px_50px_rgba(255,138,31,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(255,138,31,0.15),transparent_70%)]',
  },
  yellow: {
    activeOption:
      'bg-premium-yellow/10 border-premium-yellow/40 text-premium-yellow shadow-[0_0_20px_rgba(255,204,31,0.12)]',
    button:
      'bg-premium-yellow hover:bg-[#ffd14d] active:scale-95 shadow-[0_20px_50px_rgba(255,204,31,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(255,204,31,0.15),transparent_70%)]',
  },
  purple: {
    activeOption:
      'bg-premium-purple/10 border-premium-purple/40 text-premium-purple shadow-[0_0_20px_rgba(199,123,255,0.12)]',
    button:
      'bg-premium-purple hover:bg-[#d499ff] active:scale-95 shadow-[0_20px_50px_rgba(199,123,255,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(199,123,255,0.15),transparent_70%)]',
  },
  pink: {
    activeOption:
      'bg-premium-pink/10 border-premium-pink/40 text-premium-pink shadow-[0_0_20px_rgba(255,46,180,0.12)]',
    button:
      'bg-premium-pink hover:bg-[#ff4dc4] active:scale-95 shadow-[0_20px_50px_rgba(255,46,180,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(255,46,180,0.15),transparent_70%)]',
  },
  cyan: {
    activeOption:
      'bg-premium-cyan/10 border-premium-cyan/40 text-premium-cyan shadow-[0_0_20px_rgba(0,229,255,0.12)]',
    button:
      'bg-premium-cyan hover:bg-[#33eaff] active:scale-95 shadow-[0_20px_50px_rgba(0,229,255,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(0,229,255,0.15),transparent_70%)]',
  },
  lime: {
    activeOption:
      'bg-premium-lime/10 border-premium-lime/40 text-premium-lime shadow-[0_0_20px_rgba(132,204,22,0.12)]',
    button:
      'bg-premium-lime hover:bg-[#a3e635] active:scale-95 shadow-[0_20px_50px_rgba(132,204,22,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(132,204,22,0.15),transparent_70%)]',
  },
  teal: {
    activeOption:
      'bg-premium-teal/10 border-premium-teal/40 text-premium-teal shadow-[0_0_20px_rgba(20,184,166,0.12)]',
    button:
      'bg-premium-teal hover:bg-[#2dd4bf] active:scale-95 shadow-[0_20px_50px_rgba(20,184,166,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(20,184,166,0.15),transparent_70%)]',
  },
  indigo: {
    activeOption:
      'bg-premium-indigo/10 border-premium-indigo/40 text-premium-indigo shadow-[0_0_20px_rgba(99,102,241,0.12)]',
    button:
      'bg-premium-indigo hover:bg-[#818cf8] active:scale-95 shadow-[0_20px_50px_rgba(99,102,241,0.3)]',
    gradient: 'bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,0.15),transparent_70%)]',
  },
};

// ─── Regular token generator ───────────────────────────────────────────────────
// Produces the 14 purely formulaic tokens from a color name alone.
// All generated class names are covered by @source inline() in index.css.
function makeSimpleTokens(c: GameTheme): Omit<ThemeTokens, 'activeOption' | 'button' | 'gradient'> {
  return {
    text: `text-premium-${c}`,
    solid: `bg-premium-${c}`,
    bg5: `bg-premium-${c}/5`,
    bg10: `bg-premium-${c}/10`,
    bg20: `bg-premium-${c}/20`,
    border20: `border-premium-${c}/20`,
    border30: `border-premium-${c}/30`,
    border40: `border-premium-${c}/40`,
    indexBg: `bg-premium-${c}/20 text-premium-${c} border-premium-${c}/30`,
    focus: `focus:border-premium-${c}/50`,
    addHover: `hover:bg-premium-${c}/5 hover:text-white/80 hover:border-premium-${c}/20`,
    closeHover: `hover:bg-premium-${c}/10 hover:text-premium-${c}`,
    glow: `shadow-premium-${c}/20`,
    headerTheme: `border-premium-${c}/50 text-premium-${c}`,
  };
}

export const THEME_TOKENS: Record<GameTheme, ThemeTokens> = Object.fromEntries(
  (Object.keys(PREMIUM_RGB) as GameTheme[]).map((c) => [
    c,
    { ...makeSimpleTokens(c), ...ARBITRARY[c] },
  ])
) as Record<GameTheme, ThemeTokens>;

export const getTheme = (color: GameTheme): ThemeTokens => THEME_TOKENS[color];

// ─── Role tokens ───────────────────────────────────────────────────────────────
// Semantic role colors for RoleDistribution/FakeArtistDistribution.
// These are NOT game theme colors — they are fixed per role identity.
// Values go into style={{}} props (not className), so template literals are safe here.

export const ROLE_TOKENS = {
  spy: {
    cardBorder: `1.5px solid rgba(${PREMIUM_RGB.red},0.45)`,
    cardShadow: `0 0 80px rgba(${PREMIUM_RGB.red},0.22), 0 32px 64px rgba(0,0,0,0.55), inset 0 1px 0 rgba(${PREMIUM_RGB.red},0.12)`,
    topGlow: `rgba(${PREMIUM_RGB.red},0.3)`,
    iconFilter: `drop-shadow(0 0 20px rgba(${PREMIUM_RGB.red},0.5))`,
    textShadow: `0 0 48px rgba(${PREMIUM_RGB.red},0.45)`,
    btnShadow: `0 8px 32px rgba(${PREMIUM_RGB.red},0.35)`,
  },
  traitor: {
    cardBorder: `1.5px solid rgba(${PREMIUM_RGB.orange},0.4)`,
    cardShadow: `0 0 70px rgba(${PREMIUM_RGB.orange},0.15), 0 32px 64px rgba(0,0,0,0.55)`,
    topGlow: `rgba(${PREMIUM_RGB.orange},0.22)`,
    iconFilter: `drop-shadow(0 0 16px rgba(${PREMIUM_RGB.orange},0.45))`,
    btnShadow: `0 8px 32px rgba(${PREMIUM_RGB.orange},0.25)`,
  },
  agent: {
    cardBorder: `1.5px solid rgba(${PREMIUM_RGB.green},0.32)`,
    cardShadow: `0 0 70px rgba(${PREMIUM_RGB.green},0.12), 0 32px 64px rgba(0,0,0,0.55), inset 0 1px 0 rgba(${PREMIUM_RGB.green},0.08)`,
    topGlow: `rgba(${PREMIUM_RGB.green},0.18)`,
    iconFilter: `drop-shadow(0 0 16px rgba(${PREMIUM_RGB.green},0.4))`,
    textShadow: `0 0 32px rgba(${PREMIUM_RGB.green},0.22)`,
    btnShadow: `0 8px 32px rgba(${PREMIUM_RGB.green},0.22)`,
  },
} as const;
