export interface FakeArtistCategory {
  category: string;
  word: string;
}

export const FAKE_ARTIST_DATA: FakeArtistCategory[] = [
  // Животные
  { category: "Животные", word: "Жираф" },
  { category: "Животные", word: "Слон" },
  { category: "Животные", word: "Пингвин" },
  { category: "Животные", word: "Краб" },
  { category: "Животные", word: "Кенгуру" },
  { category: "Животные", word: "Тигр" },
  { category: "Животные", word: "Лиса" },
  { category: "Животные", word: "Черепаха" },
  { category: "Животные", word: "Осьминог" },
  { category: "Животные", word: "Крокодил" },
  { category: "Животные", word: "Коала" },
  { category: "Животные", word: "Сова" },
  { category: "Животные", word: "Панда" },
  { category: "Животные", word: "Верблюд" },
  { category: "Животные", word: "Белка" },

  // Транспорт
  { category: "Транспорт", word: "Вертолет" },
  { category: "Транспорт", word: "Подводная лодка" },
  { category: "Транспорт", word: "Пожарная машина" },
  { category: "Транспорт", word: "Ракета" },
  { category: "Транспорт", word: "Самолет" },
  { category: "Транспорт", word: "Поезд" },
  { category: "Транспорт", word: "Велосипед" },
  { category: "Транспорт", word: "Мотоцикл" },
  { category: "Транспорт", word: "Трактор" },
  { category: "Транспорт", word: "Лодка" },
  { category: "Транспорт", word: "Скутер" },
  { category: "Транспорт", word: "Танк" },
  { category: "Транспорт", word: "Корабль" },
  { category: "Транспорт", word: "Метро" },
  { category: "Транспорт", word: "Грузовик" },

  // Предметы
  { category: "Предметы", word: "Будильник" },
  { category: "Предметы", word: "Зеркало" },
  { category: "Предметы", word: "Гитара" },
  { category: "Предметы", word: "Фонарик" },
  { category: "Предметы", word: "Чайник" },
  { category: "Предметы", word: "Телевизор" },
  { category: "Предметы", word: "Рюкзак" },
  { category: "Предметы", word: "Ноутбук" },
  { category: "Предметы", word: "Ключ" },
  { category: "Предметы", word: "Очки" },
  { category: "Предметы", word: "Свеча" },
  { category: "Предметы", word: "Молоток" },
  { category: "Предметы", word: "Фотоаппарат" },
  { category: "Предметы", word: "Карандаш" },
  { category: "Предметы", word: "Зонт" },

  // Еда
  { category: "Еда", word: "Пицца" },
  { category: "Еда", word: "Бургер" },
  { category: "Еда", word: "Суши" },
  { category: "Еда", word: "Мороженое" },
  { category: "Еда", word: "Хот-дог" },
  { category: "Еда", word: "Пончик" },
  { category: "Еда", word: "Спагетти" },
  { category: "Еда", word: "Торт" },
  { category: "Еда", word: "Картошка фри" },
  { category: "Еда", word: "Шоколад" },
  { category: "Еда", word: "Арбуз" },
  { category: "Еда", word: "Яблоко" },
  { category: "Еда", word: "Омлет" },
  { category: "Еда", word: "Тако" },
  { category: "Еда", word: "Попкорн" },

  // Места
  { category: "Места", word: "Эйфелева башня" },
  { category: "Места", word: "Пирамида" },
  { category: "Места", word: "Замок" },
  { category: "Места", word: "Пляж" },
  { category: "Места", word: "Музей" },
  { category: "Места", word: "Парк" },
  { category: "Места", word: "Школа" },
  { category: "Места", word: "Больница" },
  { category: "Места", word: "Стадион" },
  { category: "Места", word: "Аэропорт" },
  { category: "Места", word: "Маяк" },
  { category: "Места", word: "Вулкан" },
  { category: "Места", word: "Лес" },
  { category: "Места", word: "Пустыня" },
  { category: "Места", word: "Аквапарк" },

  // Спорт
  { category: "Спорт", word: "Футбол" },
  { category: "Спорт", word: "Теннис" },
  { category: "Спорт", word: "Бокс" },
  { category: "Спорт", word: "Баскетбол" },
  { category: "Спорт", word: "Хоккей" },
  { category: "Спорт", word: "Гольф" },
  { category: "Спорт", word: "Серфинг" },
  { category: "Спорт", word: "Йога" },
  { category: "Спорт", word: "Плавание" },
  { category: "Спорт", word: "Боулинг" },
  { category: "Спорт", word: "Волейбол" },
  { category: "Спорт", word: "Карате" },
  { category: "Спорт", word: "Скейтбординг" },
  { category: "Спорт", word: "Лыжи" },
  { category: "Спорт", word: "Фехтование" },

  // Профессии
  { category: "Профессии", word: "Повар" },
  { category: "Профессии", word: "Врач" },
  { category: "Профессии", word: "Космонавт" },
  { category: "Профессии", word: "Учитель" },
  { category: "Профессии", word: "Полицейский" },
  { category: "Профессии", word: "Пожарный" },
  { category: "Профессии", word: "Музыкант" },
  { category: "Профессии", word: "Фермер" },
  { category: "Профессии", word: "Художник" },
  { category: "Профессии", word: "Программист" },
  { category: "Профессии", word: "Строитель" },
  { category: "Профессии", word: "Пилот" },
  { category: "Профессии", word: "Детектив" },
  { category: "Профессии", word: "Бариста" },
  { category: "Профессии", word: "Судья" },

  // Космос
  { category: "Космос", word: "Планета" },
  { category: "Космос", word: "Звезда" },
  { category: "Космос", word: "Комета" },
  { category: "Космос", word: "Спутник" },
  { category: "Космос", word: "Марс" },
  { category: "Космос", word: "Сатурн" },
  { category: "Космос", word: "Луна" },
  { category: "Космос", word: "Астероид" },
  { category: "Космос", word: "Телескоп" },
  { category: "Космос", word: "Инопланетянин" },
  { category: "Космос", word: "Черная дыра" },
  { category: "Космос", word: "Созвездие" },
  { category: "Космос", word: "Метеорит" },
  { category: "Космос", word: "Галактика" },
  { category: "Космос", word: "Космическая станция" },

  // Музыкальные инструменты
  { category: "Музыкальные инструменты", word: "Барабан" },
  { category: "Музыкальные инструменты", word: "Скрипка" },
  { category: "Музыкальные инструменты", word: "Пианино" },
  { category: "Музыкальные инструменты", word: "Труба" },
  { category: "Музыкальные инструменты", word: "Арфа" },
  { category: "Музыкальные инструменты", word: "Флейта" },
  { category: "Музыкальные инструменты", word: "Саксофон" },
  { category: "Музыкальные инструменты", word: "Баян" },
  { category: "Музыкальные инструменты", word: "Укулеле" },
  { category: "Музыкальные инструменты", word: "Контрабас" },
  { category: "Музыкальные инструменты", word: "Ксилофон" },
  { category: "Музыкальные инструменты", word: "Электрогитара" },
  { category: "Музыкальные инструменты", word: "Губная гармошка" },
  { category: "Музыкальные инструменты", word: "Виолончель" },
  { category: "Музыкальные инструменты", word: "Треугольник" },

  // Одежда
  { category: "Одежда", word: "Шляпа" },
  { category: "Одежда", word: "Куртка" },
  { category: "Одежда", word: "Кроссовки" },
  { category: "Одежда", word: "Перчатки" },
  { category: "Одежда", word: "Шарф" },
  { category: "Одежда", word: "Носки" },
  { category: "Одежда", word: "Платье" },
  { category: "Одежда", word: "Галстук" },
  { category: "Одежда", word: "Очки" },
  { category: "Одежда", word: "Рюкзак" },
  { category: "Одежда", word: "Тапки" },
  { category: "Одежда", word: "Кепка" },
  { category: "Одежда", word: "Свитер" },
  { category: "Одежда", word: "Джинсы" },
  { category: "Одежда", word: "Ремень" },

  // Сказки и фэнтези
  { category: "Сказки и фэнтези", word: "Дракон" },
  { category: "Сказки и фэнтези", word: "Единорог" },
  { category: "Сказки и фэнтези", word: "Русалка" },
  { category: "Сказки и фэнтези", word: "Волшебник" },
  { category: "Сказки и фэнтези", word: "Гоблин" },
  { category: "Сказки и фэнтези", word: "Фея" },
  { category: "Сказки и фэнтези", word: "Тролль" },
  { category: "Сказки и фэнтези", word: "Замок дракона" },
  { category: "Сказки и фэнтези", word: "Магический посох" },
  { category: "Сказки и фэнтези", word: "Зелье" },
  { category: "Сказки и фэнтези", word: "Принцесса" },
  { category: "Сказки и фэнтези", word: "Рыцарь" },
  { category: "Сказки и фэнтези", word: "Грифон" },
  { category: "Сказки и фэнтези", word: "Феникс" },
  { category: "Сказки и фэнтези", word: "Заколдованный лес" },

  // Технологии
  { category: "Технологии", word: "Робот" },
  { category: "Технологии", word: "Смартфон" },
  { category: "Технологии", word: "Дрон" },
  { category: "Технологии", word: "VR-очки" },
  { category: "Технологии", word: "Клавиатура" },
  { category: "Технологии", word: "Мышка" },
  { category: "Технологии", word: "Процессор" },
  { category: "Технологии", word: "Wi-Fi" },
  { category: "Технологии", word: "Сервер" },
  { category: "Технологии", word: "Чип" },
  { category: "Технологии", word: "Искусственный интеллект" },
  { category: "Технологии", word: "3D-принтер" },
  { category: "Технологии", word: "Умные часы" },
  { category: "Технологии", word: "Камера наблюдения" },
  { category: "Технологии", word: "Голограмма" },

  // Природа
  { category: "Природа", word: "Водопад" },
  { category: "Природа", word: "Гора" },
  { category: "Природа", word: "Радуга" },
  { category: "Природа", word: "Озеро" },
  { category: "Природа", word: "Река" },
  { category: "Природа", word: "Ураган" },
  { category: "Природа", word: "Торнадо" },
  { category: "Природа", word: "Лавина" },
  { category: "Природа", word: "Ледник" },
  { category: "Природа", word: "Пещера" },
  { category: "Природа", word: "Джунгли" },
  { category: "Природа", word: "Северное сияние" },
  { category: "Природа", word: "Остров" },
  { category: "Природа", word: "Каньон" },
  { category: "Природа", word: "Болото" },

  // Эмоции
  { category: "Эмоции", word: "Радость" },
  { category: "Эмоции", word: "Грусть" },
  { category: "Эмоции", word: "Страх" },
  { category: "Эмоции", word: "Удивление" },
  { category: "Эмоции", word: "Злость" },
  { category: "Эмоции", word: "Смущение" },
  { category: "Эмоции", word: "Гордость" },
  { category: "Эмоции", word: "Сонливость" },
  { category: "Эмоции", word: "Восторг" },
  { category: "Эмоции", word: "Паника" },
  { category: "Эмоции", word: "Любопытство" },
  { category: "Эмоции", word: "Скука" },
  { category: "Эмоции", word: "Шок" },
  { category: "Эмоции", word: "Спокойствие" },
  { category: "Эмоции", word: "Надежда" },

  // Игры
  { category: "Игры", word: "Шахматы" },
  { category: "Игры", word: "Тетрис" },
  { category: "Игры", word: "Мафия" },
  { category: "Игры", word: "Монополия" },
  { category: "Игры", word: "Minecraft" },
  { category: "Игры", word: "Pac-Man" },
  { category: "Игры", word: "Among Us" },
  { category: "Игры", word: "Покер" },
  { category: "Игры", word: "Домино" },
  { category: "Игры", word: "Крестики-нолики" },
  { category: "Игры", word: "Лабиринт" },
  { category: "Игры", word: "Судоку" },
  { category: "Игры", word: "Рулетка" },
  { category: "Игры", word: "Пазл" },
  { category: "Игры", word: "Dungeons & Dragons" },

  // Фрукты и овощи
  { category: "Фрукты и овощи", word: "Банан" },
  { category: "Фрукты и овощи", word: "Морковь" },
  { category: "Фрукты и овощи", word: "Капуста" },
  { category: "Фрукты и овощи", word: "Апельсин" },
  { category: "Фрукты и овощи", word: "Лимон" },
  { category: "Фрукты и овощи", word: "Груша" },
  { category: "Фрукты и овощи", word: "Киви" },
  { category: "Фрукты и овощи", word: "Помидор" },
  { category: "Фрукты и овощи", word: "Огурец" },
  { category: "Фрукты и овощи", word: "Ананас" },
  { category: "Фрукты и овощи", word: "Виноград" },
  { category: "Фрукты и овощи", word: "Клубника" },
  { category: "Фрукты и овощи", word: "Брокколи" },
  { category: "Фрукты и овощи", word: "Перец" },
  { category: "Фрукты и овощи", word: "Манго" }
];
export const FAKE_ARTIST_INSTRUCTIONS = [ { title: "Суть игры", content: "Все игроки знают Тему и Слово, кроме одного (Самозванца). Он знает только Тему." }, { title: "Рисование", content: "Игроки по очереди рисуют по ОДНОЙ непрерывной линии. Нельзя отрывать руку/стилус от экрана во время хода." }, { title: "Два круга", content: "Игра длится ровно два круга. Каждый должен внести свой вклад в рисунок, не выдавая слово слишком явно." }, { title: "Финал", content: "После второго круга все голосуют за Самозванца. Если его поймали, у него есть шанс угадать слово и победить!" } ];