import type {AttributeEntry} from "@/games/BunkerGame/types.ts";

export const HEALTH_CONDITIONS: AttributeEntry[] = [
    {name: 'Идеальное зрение', emoji: '👀', bonus: {energy: 4, morale: 4}, isPositive: true},
    {name: 'Спортивное сердце', emoji: '❤️', bonus: {energy: 8}, isPositive: true},
    {name: 'Марафонец', emoji: '🏃‍♂️', bonus: {energy: 12}, isPositive: true},
    {name: 'Мастер дыхательных практик', emoji: '🫁', bonus: {energy: 8, morale: 4}, isPositive: true},
    {name: 'Иммунитет выше среднего', emoji: '🛡️', bonus: {medicine: 8}, isPositive: true},
    {name: 'Редко болеет', emoji: '🌟', bonus: {medicine: 6, morale: 3}, isPositive: true},
    {name: 'Сильный иммунитет', emoji: '🛡️', bonus: {medicine: 12}, isPositive: true},
    {name: 'Быстрый метаболизм', emoji: '⚡', bonus: {energy: 6}, isPositive: true},
    {name: 'Спортивное телосложение', emoji: '🏋️', bonus: {energy: 10}, isPositive: true},
    {name: 'Чемпион по плаванию', emoji: '🏊', bonus: {energy: 8, water: 4}, isPositive: true},
    {name: 'Отличная реакция', emoji: '⚡', bonus: {energy: 8}, isPositive: true},
    {name: 'Хорошая генетика', emoji: '🧬', bonus: {energy: 6, medicine: 4}, isPositive: true},
    {name: 'Быстро заживляют раны', emoji: '✨', bonus: {medicine: 10}, isPositive: true},
    {name: 'Отличный вестибулярный аппарат', emoji: '🧭', bonus: {energy: 5}, isPositive: true},
    {name: 'Крепкие суставы', emoji: '🦴', bonus: {energy: 6}, isPositive: true},
    {name: 'Сильный организм', emoji: '💪', bonus: {energy: 10}, isPositive: true},
    {name: 'Крепкий сон', emoji: '🛏️', bonus: {energy: 6, morale: 4}, isPositive: true},
    {name: 'Высокая стрессоустойчивость', emoji: '🧘', bonus: {morale: 10}, isPositive: true},
    {name: 'Железное здоровье', emoji: '🏅', bonus: {energy: 12, morale: 6}, isPositive: true},
    {
        name: 'Абсолютно здоров',
        emoji: '💪',
        bonus: {food: 5, water: 5, medicine: 5, energy: 5, morale: 5},
        isPositive: true,
    },
    {
        name: 'Отличная физподготовка',
        emoji: '🏃',
        bonus: {energy: 15, morale: 5},
        isPositive: true,
    },
    {name: 'Крепкое здоровье', emoji: '🌟', bonus: {energy: 8, morale: 8}, isPositive: true},
    {name: 'Железная выносливость', emoji: '🦾', bonus: {energy: 14, food: 4}, isPositive: true},
    {
        name: 'Быстрое восстановление',
        emoji: '✨',
        bonus: {medicine: 8, energy: 6, morale: 4},
        isPositive: true,
    },
    {name: 'Высокий болевой порог', emoji: '🪨', bonus: {morale: 8, energy: 5}, isPositive: true},
    {name: 'Хорошая координация', emoji: '🎯', bonus: {energy: 8, morale: 4}, isPositive: true},

    // 33 новых положительных состояния здоровья для выравнивания баланса
    {name: 'Отличный слух', emoji: '🦻', bonus: {morale: 6, energy: 4}, isPositive: true},
    {name: 'Здоровые зубы', emoji: '🦷', bonus: {morale: 5, food: 5}, isPositive: true},
    {name: 'Гибкость суставов', emoji: '🤸', bonus: {energy: 8}, isPositive: true},
    {name: 'Устойчивость к простудам', emoji: '🌡️', bonus: {medicine: 6}, isPositive: true},
    {name: 'Выносливое сердце', emoji: '🫀', bonus: {energy: 10}, isPositive: true},
    {name: 'Превосходное ночное зрение', emoji: '🦉', bonus: {energy: 6, morale: 4}, isPositive: true},
    {name: 'Эффективное пищеварение', emoji: '🍎', bonus: {food: 8}, isPositive: true},
    {name: 'Устойчивость к токсинам', emoji: '🧪', bonus: {medicine: 10}, isPositive: true},
    {name: 'Быстрая регенерация мышц', emoji: '⚡', bonus: {energy: 8}, isPositive: true},
    {name: 'Идеальная осанка', emoji: '🧍', bonus: {energy: 6, morale: 2}, isPositive: true},
    {name: 'Низкая потребность в воде', emoji: '🌵', bonus: {water: 12}, isPositive: true},
    {name: 'Низкая потребность в пище', emoji: '🐪', bonus: {food: 12}, isPositive: true},
    {name: 'Природный мышечный тонус', emoji: '💪', bonus: {energy: 8}, isPositive: true},
    {name: 'Устойчивость к морской болезни', emoji: '🤢', bonus: {energy: 5, morale: 5}, isPositive: true},
    {name: 'Здоровые легкие', emoji: '🫁', bonus: {energy: 10}, isPositive: true},
    {name: 'Высокий уровень гемоглобина', emoji: '🩸', bonus: {energy: 12}, isPositive: true},
    {name: 'Стабильное кровяное давление', emoji: '📊', bonus: {energy: 8}, isPositive: true},
    {name: 'Крепкая нервная система', emoji: '🧠', bonus: {morale: 12}, isPositive: true},
    {name: 'Острый нюх и осязание', emoji: '👃', bonus: {food: 4, energy: 4}, isPositive: true},
    {name: 'Устойчивый гормональный фон', emoji: '⚖️', bonus: {morale: 8, energy: 4}, isPositive: true},
    {name: 'Здоровая кожа (без инфекций)', emoji: '🧼', bonus: {medicine: 6, morale: 2}, isPositive: true},
    {name: 'Высокий тонус сосудов', emoji: '📈', bonus: {energy: 8}, isPositive: true},
    {name: 'Отличная терморегуляция организма', emoji: '❄️', bonus: {energy: 8, water: 4}, isPositive: true},
    {name: 'Устойчивость к аллергенам', emoji: '🌿', bonus: {medicine: 8}, isPositive: true},
    {name: 'Здоровая микрофлора кишечника', emoji: '🥛', bonus: {food: 8, morale: 2}, isPositive: true},
    {name: 'Высокая скорость лимфотока', emoji: '💧', bonus: {medicine: 6, energy: 4}, isPositive: true},
    {name: 'Крепкие кости', emoji: '🦴', bonus: {energy: 7}, isPositive: true},
    {name: 'Отсутствие хронических болезней', emoji: '🛡️', bonus: {medicine: 10, morale: 4}, isPositive: true},
    {name: 'Быстрая акклиматизация', emoji: '🌍', bonus: {energy: 6, morale: 4}, isPositive: true},
    {name: 'Выносливость к дефициту сна', emoji: '🦉', bonus: {energy: 10}, isPositive: true},
    {name: 'Здоровые почки', emoji: '🧬', bonus: {water: 8}, isPositive: true},
    {name: 'Хорошее периферическое зрение', emoji: '🕶️', bonus: {energy: 5, morale: 3}, isPositive: true},
    {name: 'Общий высокий жизненный потенциал', emoji: '🔥', bonus: {energy: 10, morale: 5}, isPositive: true},

    // Отрицательные состояния здоровья (сглаженные штрафы, дубли удалены)
    {name: 'Бессонница', emoji: '🌙', bonus: {energy: -15}, isPositive: false},
    {name: 'Хроническая мигрень', emoji: '🤕', bonus: {morale: -12, energy: -10}, isPositive: false},
    {name: 'Плохое зрение', emoji: '👓', bonus: {energy: -12}, isPositive: false},
    {name: 'Глухота', emoji: '🦻', bonus: {morale: -15}, isPositive: false},
    {name: 'Частичная потеря зрения', emoji: '🩹', bonus: {energy: -15}, isPositive: false},
    {name: 'Проблемы со спиной', emoji: '🦴', bonus: {energy: -15}, isPositive: false},
    {name: 'Гастрит', emoji: '🍽️', bonus: {food: -10}, isPositive: false},
    {name: 'Хроническая усталость', emoji: '😪', bonus: {energy: -12}, isPositive: false},
    {name: 'Подагра', emoji: '🦶', bonus: {energy: -14}, isPositive: false},
    {name: 'Тахикардия', emoji: '💓', bonus: {energy: -12, medicine: -5}, isPositive: false},
    {name: 'Аритмия', emoji: '❤️‍🩹', bonus: {energy: -12, medicine: -5}, isPositive: false},
    {name: 'Плохие зубы', emoji: '🦷', bonus: {morale: -10, medicine: -5}, isPositive: false},
    {name: 'Протез ноги', emoji: '🦿', bonus: {energy: -15}, isPositive: false},
    {name: 'Протез руки', emoji: '🦾', bonus: {energy: -14}, isPositive: false},
    {name: 'Плохой слух', emoji: '👂', bonus: {morale: -10}, isPositive: false},
    {name: 'Проблемы со щитовидкой', emoji: '🩺', bonus: {energy: -14}, isPositive: false},
    {name: 'Плоскостопие', emoji: '🦶', bonus: {energy: -12}, isPositive: false},
    {name: 'Заикание', emoji: '🗣️', bonus: {morale: -14}, isPositive: false},
    {name: 'Хронический гайморит', emoji: '🤧', bonus: {medicine: -6}, isPositive: false},
    {name: 'Слабые лёгкие', emoji: '🫁', bonus: {energy: -15}, isPositive: false},
    {name: 'Катаракта', emoji: '👁', bonus: {energy: -14}, isPositive: false},
    {name: 'Синдром раздражённого кишечника', emoji: '🥴', bonus: {food: -10}, isPositive: false},
    {name: 'Повышенная тревожность', emoji: '😟', bonus: {morale: -14}, isPositive: false},
    {name: 'Нарколепсия', emoji: '😴', bonus: {energy: -12}, isPositive: false},
    {name: 'Проблемы с печенью', emoji: '🫀', bonus: {medicine: -10}, isPositive: false},
    {name: 'Хронический отит', emoji: '👂', bonus: {morale: -10}, isPositive: false},
    {name: 'Дальнозоркость', emoji: '🔍', bonus: {energy: -10}, isPositive: false},
    {name: 'Низкая выносливость', emoji: '😮‍💨', bonus: {energy: -15}, isPositive: false},
    {name: 'Гипермобильность суставов', emoji: '🤸', bonus: {energy: -12}, isPositive: false},
    {name: 'Обмороки при стрессе', emoji: '😵', bonus: {morale: -12, energy: -12}, isPositive: false},
    {name: 'Перелом позвоночника в прошлом', emoji: '🩻', bonus: {energy: -12}, isPositive: false},
    {name: 'Хроническая астма', emoji: '😤', bonus: {energy: -15, medicine: -5}, isPositive: false},
    {name: 'Сахарный диабет', emoji: '💉', bonus: {food: -12, medicine: -8}, isPositive: false},
    {
        name: 'Сердечная недостаточность',
        emoji: '❤️‍🩹',
        bonus: {medicine: -12, morale: -15},
        isPositive: false,
    },
    {name: 'Депрессия', emoji: '😔', bonus: {morale: -12, energy: -12}, isPositive: false},
    {
        name: 'Алкогольная зависимость',
        emoji: '🍶',
        bonus: {morale: -12, food: -6},
        isPositive: false,
    },
    {name: 'Ожирение 2 степени', emoji: '🍔', bonus: {food: -12, energy: -14}, isPositive: false},
    {name: 'Небольшая близорукость', emoji: '👓', bonus: {morale: -10}, isPositive: false},
    {
        name: 'Онкология в ремиссии',
        emoji: '🎗️',
        bonus: {medicine: -12, morale: -15},
        isPositive: false,
    },
    {
        name: 'Хронический бронхит',
        emoji: '🫁',
        bonus: {energy: -14, medicine: -5},
        isPositive: false,
    },
    {name: 'Аллергия на пыль', emoji: '🤧', bonus: {energy: -12, morale: -10}, isPositive: false},
    {name: 'ВИЧ-позитивный', emoji: '🩸', bonus: {medicine: -15, morale: -15}, isPositive: false},
    {
        name: 'Беременность', // Перенесена в негативные из-за преобладающих штрафов на ресурсы
        emoji: '🤱',
        bonus: {morale: 10, food: -12, medicine: -6},
        isPositive: false,
    },
    {name: 'Слабый иммунитет', emoji: '🦠', bonus: {medicine: -12, morale: -10}, isPositive: false},
    {name: 'Гипертония', emoji: '📈', bonus: {medicine: -8, energy: -14}, isPositive: false},
    {name: 'Анемия', emoji: '🩸', bonus: {energy: -15, morale: -10}, isPositive: false},
    {name: 'Артрит', emoji: '🦴', bonus: {energy: -14, food: -4}, isPositive: false},
    {name: 'Язва желудка', emoji: '🥴', bonus: {food: -12, morale: -10}, isPositive: false},
    {name: 'ПТСР', emoji: '🎇', bonus: {morale: -12, energy: -12}, isPositive: false},
    {name: 'Эпилепсия', emoji: '⚠️', bonus: {medicine: -12, energy: -12}, isPositive: false},
    {name: 'Тремор рук', emoji: '✋', bonus: {medicine: -8, energy: -12}, isPositive: false},
    {name: 'Сколиоз', emoji: '🧍', bonus: {energy: -14, morale: -10}, isPositive: false},
    {name: 'Дальтонизм', emoji: '🎨', bonus: {morale: -4}, isPositive: false},
    {name: 'Старые травмы колена', emoji: '🦵', bonus: {energy: -14}, isPositive: false},
    {name: 'Проблемы с почками', emoji: '💧', bonus: {water: -12, medicine: -6}, isPositive: false},
    {name: 'Лактозная непереносимость', emoji: '🥛', bonus: {food: -14, morale: -4}, isPositive: false},
    {name: 'Глухота на одно ухо', emoji: '👂', bonus: {morale: -10, energy: -10}, isPositive: false},
];