import type { AttributeEntry } from '@/games/BunkerGame/types.ts';

export const HOBBIES: AttributeEntry[] = [
  { name: 'Кузнечное дело', emoji: '⚒️', bonus: { energy: 18, morale: 5 }, isPositive: true },
  { name: 'Электроника', emoji: '🔌', bonus: { energy: 20 }, isPositive: true },
  { name: '3D-моделирование', emoji: '🖥️', bonus: { energy: 10, morale: 8 }, isPositive: true },
  { name: 'Программирование', emoji: '💻', bonus: { energy: 16 }, isPositive: true },
  { name: 'Робототехника', emoji: '🤖', bonus: { energy: 18 }, isPositive: true },
  { name: 'Археология', emoji: '🏺', bonus: { food: 8, morale: 10 }, isPositive: true },
  { name: 'Геокешинг', emoji: '📍', bonus: { food: 10, water: 10 }, isPositive: true },
  { name: 'Туризм', emoji: '🎒', bonus: { energy: 14, morale: 8 }, isPositive: true },
  { name: 'Спелеология', emoji: '🕳️', bonus: { water: 12, energy: 8 }, isPositive: true },
  { name: 'Парусный спорт', emoji: '⛵', bonus: { water: 18 }, isPositive: true },
  { name: 'Гребля', emoji: '🚣', bonus: { energy: 14, water: 6 }, isPositive: true },
  { name: 'Лыжный спорт', emoji: '🎿', bonus: { energy: 18 }, isPositive: true },
  { name: 'Паркур', emoji: '🏃', bonus: { energy: 14, morale: 4 }, isPositive: true },
  { name: 'Фехтование', emoji: '🤺', bonus: { energy: 14, morale: 6 }, isPositive: true },
  { name: 'Стрельба из лука', emoji: '🏹', bonus: { food: 10, energy: 8 }, isPositive: true },
  { name: 'Шахматы', emoji: '♟️', bonus: { morale: 14, energy: 4 }, isPositive: true },
  { name: 'Настольные игры', emoji: '🎲', bonus: { morale: 16 }, isPositive: true },
  { name: 'Решение головоломок', emoji: '🧩', bonus: { morale: 12, energy: 6 }, isPositive: true },
  { name: 'Каллиграфия', emoji: '✒️', bonus: { morale: 14 }, isPositive: true },
  { name: 'Поэзия', emoji: '📜', bonus: { morale: 15 }, isPositive: true },
  { name: 'Написание рассказов', emoji: '📚', bonus: { morale: 15 }, isPositive: true },
  { name: 'Ведение дневника', emoji: '📔', bonus: { morale: 14 }, isPositive: true },
  { name: 'Рисование', emoji: '🎨', bonus: { morale: 18 }, isPositive: true },
  { name: 'Скульптура', emoji: '🗿', bonus: { morale: 12, energy: 6 }, isPositive: true },
  { name: 'Гончарное дело', emoji: '🏺', bonus: { water: 8, morale: 10 }, isPositive: true },
  { name: 'Вязание', emoji: '🧶', bonus: { morale: 12, medicine: 6 }, isPositive: true },
  { name: 'Макраме', emoji: '🪢', bonus: { morale: 10, energy: 6 }, isPositive: true },
  { name: 'Изготовление свечей', emoji: '🕯️', bonus: { morale: 12, energy: 5 }, isPositive: true },
  { name: 'Мыловарение', emoji: '🧼', bonus: { medicine: 16 }, isPositive: true },
  { name: 'Кожевенное дело', emoji: '👜', bonus: { energy: 12, morale: 6 }, isPositive: true },
  { name: 'Таксидермия', emoji: '🦌', bonus: { food: 10, morale: 6 }, isPositive: true },
  { name: 'Собирательство грибов', emoji: '🍄', bonus: { food: 18 }, isPositive: true },
  { name: 'Собирательство ягод', emoji: '🫐', bonus: { food: 16 }, isPositive: true },
  { name: 'Выращивание специй', emoji: '🌶️', bonus: { food: 12, morale: 6 }, isPositive: true },
  { name: 'Аквариумистика', emoji: '🐠', bonus: { morale: 12, water: 5 }, isPositive: true },
  { name: 'Разведение птиц', emoji: '🐔', bonus: { food: 16 }, isPositive: true },
  { name: 'Дрессировка животных', emoji: '🐕', bonus: { morale: 12, food: 6 }, isPositive: true },
  { name: 'Коневодство', emoji: '🐎', bonus: { energy: 14, morale: 6 }, isPositive: true },
  { name: 'Следопытство', emoji: '👣', bonus: { food: 12, water: 6 }, isPositive: true },
  {
    name: 'Ориентирование на местности',
    emoji: '🧭',
    bonus: { energy: 12, water: 6 },
    isPositive: true,
  },
  { name: 'Радиоконструирование', emoji: '📻', bonus: { energy: 18 }, isPositive: true },
  { name: 'Сборка дронов', emoji: '🚁', bonus: { energy: 14, morale: 6 }, isPositive: true },
  { name: 'Авиамоделизм', emoji: '🛩️', bonus: { energy: 12, morale: 6 }, isPositive: true },
  { name: 'Судомоделизм', emoji: '🚢', bonus: { water: 8, morale: 8 }, isPositive: true },
  { name: 'Металлоискательство', emoji: '🔍', bonus: { food: 8, energy: 8 }, isPositive: true },
  { name: 'Реставрация вещей', emoji: '🛠️', bonus: { energy: 16 }, isPositive: true },
  { name: 'Замочное дело', emoji: '🔐', bonus: { energy: 12, morale: 6 }, isPositive: true },
  {
    name: 'Пирография (выжигание)',
    emoji: '🔥',
    bonus: { morale: 12, energy: 5 },
    isPositive: true,
  },
  { name: 'Фокусничество', emoji: '🎩', bonus: { morale: 18 }, isPositive: true },
  { name: 'Организация праздников', emoji: '🎊', bonus: { morale: 20 }, isPositive: true },
  { name: 'Огородничество', emoji: '🌱', bonus: { food: 18 }, isPositive: true },
  { name: 'Рыболовство', emoji: '🎣', bonus: { food: 18 }, isPositive: true },
  {
    name: 'Выживание в дикой природе',
    emoji: '🏕️',
    bonus: { food: 12, energy: 12 },
    isPositive: true,
  },
  { name: 'Оказание первой помощи', emoji: '🩹', bonus: { medicine: 20 }, isPositive: true },
  { name: 'Ремонт техники', emoji: '🔩', bonus: { energy: 16 }, isPositive: true },
  { name: 'Кулинария', emoji: '🍳', bonus: { food: 14, morale: 6 }, isPositive: true },
  { name: 'Фитнес и спорт', emoji: '🏋️', bonus: { energy: 14, morale: 8 }, isPositive: true },
  { name: 'Музыка и пение', emoji: '🎸', bonus: { morale: 18 }, isPositive: true },
  { name: 'Охота и стрельба', emoji: '🎯', bonus: { food: 12, energy: 8 }, isPositive: true },
  { name: 'Медитация и йога', emoji: '🧘', bonus: { morale: 18 }, isPositive: true },
  { name: 'Видеоигры', emoji: '🎮', bonus: { morale: 12, energy: 4 }, isPositive: true },
  { name: 'Чтение', emoji: '📖', bonus: { morale: 15 }, isPositive: true },
  { name: 'Изучение языков', emoji: '🗣️', bonus: { morale: 14 }, isPositive: true },
  { name: 'Пауэрлифтинг', emoji: '🏆', bonus: { energy: 18 }, isPositive: true },
  { name: 'Бойцовские искусства', emoji: '🥊', bonus: { energy: 12, morale: 8 }, isPositive: true },
  { name: 'Сапожное дело', emoji: '👞', bonus: { morale: 8, energy: 8 }, isPositive: true },
  { name: 'Шитьё', emoji: '🧵', bonus: { morale: 10, medicine: 6 }, isPositive: true },
  { name: 'Столярное дело', emoji: '🪚', bonus: { energy: 14, morale: 5 }, isPositive: true },
  { name: 'Резьба по дереву', emoji: '🪵', bonus: { morale: 12, energy: 5 }, isPositive: true },
  {
    name: 'Сбор лекарственных трав',
    emoji: '🌿',
    bonus: { medicine: 15, food: 5 },
    isPositive: true,
  },
  { name: 'Пчеловодство', emoji: '🍯', bonus: { food: 12, morale: 8 }, isPositive: true },
  { name: 'Выпечка', emoji: '🧁', bonus: { food: 12, morale: 10 }, isPositive: true },
  { name: 'Консервирование', emoji: '🥫', bonus: { food: 18 }, isPositive: true },
  { name: 'Самогоноварение', emoji: '🍾', bonus: { morale: 16, water: -2 }, isPositive: true },
  { name: 'Фотография', emoji: '📷', bonus: { morale: 14 }, isPositive: true },
  { name: 'Журналистика', emoji: '📰', bonus: { morale: 14 }, isPositive: true },
  { name: 'Актёрское мастерство', emoji: '🎭', bonus: { morale: 16 }, isPositive: true },
  { name: 'Ораторское искусство', emoji: '🎤', bonus: { morale: 16 }, isPositive: true },
  { name: 'Астрономия', emoji: '🔭', bonus: { morale: 10, energy: 6 }, isPositive: true },
  { name: 'Картография', emoji: '🗺️', bonus: { energy: 10, water: 6 }, isPositive: true },
  { name: 'Скалолазание', emoji: '🧗', bonus: { energy: 14, morale: 5 }, isPositive: true },
  { name: 'Плавание', emoji: '🏊', bonus: { energy: 12, water: 8 }, isPositive: true },
  { name: 'Велотуризм', emoji: '🚴', bonus: { energy: 12, morale: 6 }, isPositive: true },
  { name: 'Садоводство', emoji: '🪴', bonus: { food: 14, morale: 5 }, isPositive: true },
  { name: 'Радиосвязь', emoji: '📡', bonus: { energy: 12, morale: 5 }, isPositive: true },
];
