import type { AttributeEntry } from '@/games/BunkerGame/types.ts';

export const ITEMS: AttributeEntry[] = [
  { name: '3D-принтер', emoji: '🖨️', bonus: { energy: 10, morale: 4 }, isPositive: true },
  { name: 'Спутниковый телефон', emoji: '📞', bonus: { morale: 10 }, isPositive: true },
  { name: 'Теплица в контейнере', emoji: '🌱', bonus: { food: 20 }, isPositive: true },
  {
    name: 'Набор хирургических инструментов',
    emoji: '🩺',
    bonus: { medicine: 18 },
    isPositive: true,
  },
  { name: 'Портативный генератор', emoji: '⚡', bonus: { energy: 20 }, isPositive: true },
  { name: 'Коробка шоколада', emoji: '🍫', bonus: { morale: 8 }, isPositive: true },
  { name: 'Настольные игры', emoji: '🎲', bonus: { morale: 12 }, isPositive: true },
  { name: 'Запас кофе', emoji: '☕', bonus: { energy: 8, morale: 4 }, isPositive: true },
  { name: 'Медицинский справочник', emoji: '📘', bonus: { medicine: 10 }, isPositive: true },
  { name: 'Лук и стрелы', emoji: '🏹', bonus: { food: 10, energy: 4 }, isPositive: true },
  {
    name: 'Портативная солнечная электростанция',
    emoji: '☀️',
    bonus: { energy: 25 },
    isPositive: true,
  },
  { name: 'Ящик сухпайков', emoji: '🍱', bonus: { food: 18 }, isPositive: true },
  { name: 'Комплект фильтров', emoji: '💧', bonus: { water: 18 }, isPositive: true },
  {
    name: 'Ноутбук с офлайн-библиотекой',
    emoji: '💻',
    bonus: { morale: 8, energy: 4 },
    isPositive: true,
  },
  { name: 'Сейф с золотом', emoji: '💰', bonus: { morale: -2 }, isPositive: false },
  { name: 'Домашний кот', emoji: '🐈', bonus: { morale: 12 }, isPositive: true },
  { name: 'Домашняя собака', emoji: '🐕', bonus: { morale: 10 }, isPositive: true },
  { name: 'Инкубатор для птиц', emoji: '🥚', bonus: { food: 15 }, isPositive: true },
  { name: 'Мини-лаборатория', emoji: '🧪', bonus: { medicine: 15 }, isPositive: true },
  { name: 'Металлоискатель', emoji: '📡', bonus: { energy: 6 }, isPositive: true },
  { name: 'Арбалет', emoji: '🏹', bonus: { food: 8, morale: 4 }, isPositive: true },
  { name: 'Топор', emoji: '🪓', bonus: { energy: 8 }, isPositive: true },
  { name: 'Бензопила', emoji: '🪚', bonus: { energy: 12 }, isPositive: true },
  { name: 'Складной велосипед', emoji: '🚲', bonus: { energy: 8 }, isPositive: true },
  { name: 'Аквариум с рыбами', emoji: '🐟', bonus: { morale: 8 }, isPositive: true },
  { name: 'Книга рецептов', emoji: '📖', bonus: { food: 6, morale: 5 }, isPositive: true },
  { name: 'Термокостюм', emoji: '🥶', bonus: { energy: 10 }, isPositive: true },
  { name: 'Газовый баллон', emoji: '🛢️', bonus: { energy: 15 }, isPositive: true },
  { name: 'Мини-ветряк', emoji: '🌬️', bonus: { energy: 14 }, isPositive: true },
  { name: 'Запас соли', emoji: '🧂', bonus: { food: 8 }, isPositive: true },
  { name: 'Книга по психологии', emoji: '📚', bonus: { morale: 8 }, isPositive: true },
  { name: 'Гитара', emoji: '🎸', bonus: { morale: 12 }, isPositive: true },
  { name: 'Проектор', emoji: '📽️', bonus: { morale: 10 }, isPositive: true },
  { name: 'Шахматы', emoji: '♟️', bonus: { morale: 8 }, isPositive: true },
  { name: 'Комплект спецодежды', emoji: '🥾', bonus: { energy: 6 }, isPositive: true },
  { name: 'Надувная лодка', emoji: '🚣', bonus: { water: 10 }, isPositive: true },
  { name: 'Бочка мёда', emoji: '🍯', bonus: { food: 15, morale: 4 }, isPositive: true },
  { name: 'Мини-пивоварня', emoji: '🍺', bonus: { morale: 12 }, isPositive: true },
  { name: 'Коробка книг', emoji: '📚', bonus: { morale: 10 }, isPositive: true },
  {
    name: 'Набор для ремонта обуви',
    emoji: '👞',
    bonus: { energy: 5, morale: 3 },
    isPositive: true,
  },
  { name: 'Сломанный генератор', emoji: '⚡', bonus: { energy: -28 }, isPositive: false },
  { name: 'Пустая канистра', emoji: '🛢️', bonus: { morale: -13 }, isPositive: false },
  { name: 'Просроченные лекарства', emoji: '💊', bonus: { medicine: -8 }, isPositive: false },
  { name: 'Сломанная рация', emoji: '📻', bonus: { morale: -14 }, isPositive: false },
  { name: 'Коллекция мемов на флешке', emoji: '😂', bonus: { morale: 10 }, isPositive: true },
  { name: 'Робот-пылесос', emoji: '🤖', bonus: { morale: 5, medicine: 4 }, isPositive: true },
  { name: 'Комплект солнечных батарей', emoji: '🔋', bonus: { energy: 20 }, isPositive: true },
  {
    name: 'Библия выживальщика',
    emoji: '📕',
    bonus: { food: 4, water: 4, energy: 4, morale: 4 },
    isPositive: true,
  },
  { name: 'Тепловизор', emoji: '🌡️', bonus: { energy: 8 }, isPositive: true },
  { name: 'Контейнер с удобрениями', emoji: '🌾', bonus: { food: 12 }, isPositive: true },
  { name: 'Профессиональная аптечка', emoji: '🧰', bonus: { medicine: 20 }, isPositive: true },
  { name: 'Мультитул Leatherman', emoji: '🔧', bonus: { energy: 12 }, isPositive: true },
  { name: 'Пакет семян (10 культур)', emoji: '🌰', bonus: { food: 20 }, isPositive: true },
  { name: 'Запас антибиотиков', emoji: '💊', bonus: { medicine: 15 }, isPositive: true },
  { name: 'Запчасти к генератору', emoji: '⚙️', bonus: { energy: 15 }, isPositive: true },
  { name: 'Ящик консервов', emoji: '🥫', bonus: { food: 15 }, isPositive: true },
  { name: 'Охотничий нож', emoji: '🗡️', bonus: { food: 8, energy: 5 }, isPositive: true },
  { name: 'Портативная рация', emoji: '📡', bonus: { morale: 10 }, isPositive: true },
  { name: 'Переносной фильтр воды', emoji: '💧', bonus: { water: 18 }, isPositive: true },
  {
    name: 'Энциклопедия выживания',
    emoji: '📕',
    bonus: { food: 5, medicine: 5, energy: 5 },
    isPositive: true,
  },
  { name: 'Ничего', emoji: '✋', bonus: {}, isPositive: false },
  { name: 'Сломанный телефон', emoji: '📵', bonus: { morale: -13 }, isPositive: false },
  { name: 'Иконы и молитвенник', emoji: '🙏', bonus: { morale: 8 }, isPositive: true },
  { name: 'Семейный альбом', emoji: '📷', bonus: { morale: 5 }, isPositive: true },
  { name: 'Арсенал оружия', emoji: '🔫', bonus: { energy: 8, morale: 5 }, isPositive: true },
  { name: 'Канистра питьевой воды', emoji: '🚰', bonus: { water: 20 }, isPositive: true },
  { name: 'Солнечная панель', emoji: '🔋', bonus: { energy: 18 }, isPositive: true },
  { name: 'Тёплое одеяло', emoji: '🛏️', bonus: { morale: 8, energy: 4 }, isPositive: true },
  { name: 'Походная плитка', emoji: '🔥', bonus: { food: 8, energy: 6 }, isPositive: true },
  { name: 'Набор инструментов', emoji: '🧰', bonus: { energy: 14 }, isPositive: true },
  { name: 'Мешок крупы', emoji: '🌾', bonus: { food: 18 }, isPositive: true },
  { name: 'Запас батареек', emoji: '🔋', bonus: { energy: 12, morale: 3 }, isPositive: true },
  { name: 'Термос с чистой водой', emoji: '🥤', bonus: { water: 12, morale: 3 }, isPositive: true },
  {
    name: 'Рюкзак выживальщика',
    emoji: '🎒',
    bonus: { food: 5, water: 5, energy: 5 },
    isPositive: true,
  },
  {
    name: 'Таблетки для обеззараживания',
    emoji: '🫧',
    bonus: { water: 15, medicine: 5 },
    isPositive: true,
  },
  { name: 'Рыболовные снасти', emoji: '🪝', bonus: { food: 12 }, isPositive: true },
  { name: 'Спальный мешок', emoji: '🛌', bonus: { energy: 8, morale: 5 }, isPositive: true },
  { name: 'Фонарь с динамо-ручкой', emoji: '🔦', bonus: { energy: 10 }, isPositive: true },
  { name: 'Газовая горелка', emoji: '🫕', bonus: { food: 8, energy: 5 }, isPositive: true },
  { name: 'Набор витаминов', emoji: '💊', bonus: { medicine: 10, morale: 4 }, isPositive: true },
  { name: 'Колода карт', emoji: '🃏', bonus: { morale: 8 }, isPositive: true },
  {
    name: 'Полевой справочник растений',
    emoji: '📗',
    bonus: { food: 6, medicine: 6 },
    isPositive: true,
  },
  { name: 'Фляга спирта', emoji: '🧴', bonus: { medicine: 8, morale: 4 }, isPositive: true },
  { name: 'Пустая банка хлама', emoji: '🗑️', bonus: { morale: -5 }, isPositive: false },
  {
    name: 'Просроченные консервы',
    emoji: '🥫',
    bonus: { food: 4, medicine: -6 },
    isPositive: false,
  },
];
