import type {AttributeEntry} from "@/games/BunkerGame/types.ts";

export const PHOBIAS: AttributeEntry[] = [
    {name: 'Клаустрофобия', emoji: '😱', bonus: {morale: -15, energy: -12}, isPositive: false},
    {name: 'Боязнь темноты', emoji: '🌑', bonus: {morale: -12, energy: -12}, isPositive: false},
    {name: 'Мизофобия (страх микробов)', emoji: '🦠', bonus: {morale: -10, medicine: -5}, isPositive: false},
    {name: 'Трипанофобия (страх игл)', emoji: '💉', bonus: {medicine: -10, morale: -15}, isPositive: false},
    {name: 'Социофобия', emoji: '👥', bonus: {morale: -15}, isPositive: false},
    {name: 'Панические атаки', emoji: '💨', bonus: {morale: -12, energy: -15}, isPositive: false},
    {name: 'Пирофобия (страх огня)', emoji: '🔥', bonus: {morale: -14, energy: -12}, isPositive: false},
    {name: 'Боязнь крови', emoji: '🩸', bonus: {medicine: -8, morale: -15}, isPositive: false},
    {name: 'Паранойя', emoji: '🔍', bonus: {morale: -10, energy: -15}, isPositive: false},
    {name: 'Арахнофобия', emoji: '🕷️', bonus: {morale: -15}, isPositive: false},
    {name: 'Агорафобия', emoji: '🏙️', bonus: {morale: -12, energy: -14}, isPositive: false},
    {name: 'Аквафобия', emoji: '🌊', bonus: {water: -8, morale: -15}, isPositive: false},
    {name: 'Акрофобия (страх высоты)', emoji: '🏔️', bonus: {energy: -14, morale: -12}, isPositive: false},
    {name: 'Никтофобия (страх ночи)', emoji: '🌌', bonus: {morale: -10, energy: -14}, isPositive: false},
    {name: 'Танатофобия (страх смерти)', emoji: '⚰️', bonus: {morale: -12}, isPositive: false},
    {name: 'Гематофобия (страх ран и травм)', emoji: '🩹', bonus: {medicine: -8, morale: -14}, isPositive: false},
    {name: 'Аэрофобия (страх шума сирен и полёта)', emoji: '✈️', bonus: {morale: -14, energy: -12}, isPositive: false},
    {name: 'Зоофобия', emoji: '🐺', bonus: {food: -5, morale: -15}, isPositive: false},
    {name: 'Охлофобия (страх толпы)', emoji: '🧍', bonus: {morale: -10}, isPositive: false},
    {
        name: 'Тафофобия (страх быть погребённым заживо)',
        emoji: '🪦',
        bonus: {morale: -14, energy: -13},
        isPositive: false
    },
    {name: 'Гермофобия', emoji: '🧼', bonus: {morale: -14, medicine: -4}, isPositive: false},
    {name: 'Кинофобия (страх собак)', emoji: '🐕', bonus: {morale: -12, food: -10}, isPositive: false},
    {name: 'Офидиофобия (страх змей)', emoji: '🐍', bonus: {morale: -14}, isPositive: false},
    {name: 'Эметофобия (страх рвоты и тошноты)', emoji: '🤢', bonus: {medicine: -6, morale: -15}, isPositive: false},
    {name: 'Астрафобия (страх грома)', emoji: '⛈️', bonus: {morale: -14, energy: -13}, isPositive: false},
    {name: 'Технофобия', emoji: '📟', bonus: {energy: -15}, isPositive: false},
    {name: 'Глоссофобия (страх выступлений)', emoji: '🎤', bonus: {morale: -14}, isPositive: false},
    {name: 'Некрофобия', emoji: '☠️', bonus: {morale: -10, medicine: -3}, isPositive: false},
    {name: 'Катоптрофобия (страх зеркал и отражений)', emoji: '🪞', bonus: {morale: -15}, isPositive: false},
    {name: 'Бронтофобия (страх взрывов)', emoji: '💥', bonus: {morale: -10, energy: -14}, isPositive: false},
    {name: 'Гидрофобия (страх глубокой воды)', emoji: '🌊', bonus: {water: -10, morale: -14}, isPositive: false},
    {name: 'Дентофобия (страх стоматологов)', emoji: '🦷', bonus: {medicine: -8}, isPositive: false},
    {name: 'Коулрофобия (страх клоунов)', emoji: '🤡', bonus: {morale: -15}, isPositive: false},
    {name: 'Амаксофобия (страх транспорта)', emoji: '🚗', bonus: {energy: -14}, isPositive: false},
    {name: 'Киберфобия (страх компьютеров)', emoji: '💻', bonus: {energy: -15}, isPositive: false},
    {name: 'Гоплофобия (страх оружия)', emoji: '🔫', bonus: {morale: -14, energy: -12}, isPositive: false},
    {name: 'Хемофобия (страх химикатов)', emoji: '☣️', bonus: {medicine: -6, energy: -12}, isPositive: false},
    {name: 'Фонофобия (страх громких звуков)', emoji: '🔊', bonus: {morale: -10}, isPositive: false},
    {name: 'Скоптофобия (страх осуждения)', emoji: '👀', bonus: {morale: -12}, isPositive: false},
    {name: 'Ксенофобия (страх незнакомцев)', emoji: '🚷', bonus: {morale: -10}, isPositive: false},
    {name: 'Энтомофобия (страх насекомых)', emoji: '🪲', bonus: {morale: -14}, isPositive: false},
    {name: 'Мусофобия (страх мышей)', emoji: '🐭', bonus: {food: -10, morale: -15}, isPositive: false},
    {name: 'Орнитофобия (страх птиц)', emoji: '🦅', bonus: {morale: -12}, isPositive: false},
    {name: 'Батрахофобия (страх лягушек)', emoji: '🐸', bonus: {morale: -11}, isPositive: false},
    {name: 'Ихтиофобия (страх рыбы)', emoji: '🐟', bonus: {food: -6}, isPositive: false},
    {
        name: 'Кардиофобия (страх сердечного приступа)',
        emoji: '❤️',
        bonus: {morale: -14, energy: -12},
        isPositive: false
    },
    {name: 'Нозофобия (страх болезней)', emoji: '🤒', bonus: {medicine: -8, morale: -12}, isPositive: false},
    {name: 'Фармакофобия (страх лекарств)', emoji: '💊', bonus: {medicine: -12}, isPositive: false},
    {name: 'Токсикофобия (страх отравления)', emoji: '☠️', bonus: {food: -5, water: -5}, isPositive: false},
    {name: 'Электрофобия (страх электричества)', emoji: '⚡', bonus: {energy: -12}, isPositive: false},
    {name: 'Гелиофобия (страх солнечного света)', emoji: '☀️', bonus: {morale: -14}, isPositive: false},
    {name: 'Селенофобия (страх луны)', emoji: '🌕', bonus: {morale: -15}, isPositive: false},
    {name: 'Хронофобия (страх течения времени)', emoji: '⏳', bonus: {morale: -10}, isPositive: false},
    {name: 'Гефирофобия (страх мостов)', emoji: '🌉', bonus: {energy: -14}, isPositive: false},
    {name: 'Талассофобия (страх океана)', emoji: '🌊', bonus: {water: -6, morale: -15}, isPositive: false},
    {name: 'Лимнофобия (страх озёр)', emoji: '🏞️', bonus: {water: -8}, isPositive: false},
    {name: 'Дендрофобия (страх деревьев)', emoji: '🌳', bonus: {food: -10}, isPositive: false},
    {name: 'Антрофобия (страх людей)', emoji: '🧍', bonus: {morale: -12}, isPositive: false},
    {name: 'Гинофобия (страх женщин)', emoji: '👩', bonus: {morale: -10}, isPositive: false},
    {name: 'Андрофобия (страх мужчин)', emoji: '👨', bonus: {morale: -10}, isPositive: false},
    {name: 'Педиофобия (страх кукол)', emoji: '🪆', bonus: {morale: -12}, isPositive: false},
    {name: 'Автофобия (страх одиночества)', emoji: '🚪', bonus: {morale: -14}, isPositive: false},
    {name: 'Гипнофобия (страх сна)', emoji: '😴', bonus: {energy: -18}, isPositive: false},
    {name: 'Омброфобия (страх дождя)', emoji: '🌧️', bonus: {water: -6}, isPositive: false},
    {name: 'Криофобия (страх холода)', emoji: '❄️', bonus: {energy: -14}, isPositive: false},
    {name: 'Термофобия (страх жары)', emoji: '🥵', bonus: {water: -10}, isPositive: false},
    {name: 'Демонофобия (страх сверхъестественного)', emoji: '👻', bonus: {morale: -12}, isPositive: false},
    {name: 'Нумерофобия (страх цифр и расчётов)', emoji: '🔢', bonus: {energy: -12, morale: -8}, isPositive: false},
    {name: 'Логофобия (страх слов и разговоров)', emoji: '🗣️', bonus: {morale: -10}, isPositive: false},
    {name: 'Фотофобия (страх яркого света)', emoji: '💡', bonus: {energy: -12, morale: -10}, isPositive: false},
    {name: 'Ателофобия (страх совершить ошибку)', emoji: '❌', bonus: {morale: -10}, isPositive: false},
    {name: 'Какоррафиофобия (страх неудачи)', emoji: '📉', bonus: {morale: -12}, isPositive: false},
    {name: 'Фобофобия (страх собственных страхов)', emoji: '😨', bonus: {morale: -14}, isPositive: false},
    {name: 'Кенофобия (страх пустых помещений)', emoji: '🏚️', bonus: {morale: -8}, isPositive: false},
    {name: 'Сидерофобия (страх звёздного неба)', emoji: '✨', bonus: {morale: -15}, isPositive: false},
    {name: 'Топофобия (страх определённых мест)', emoji: '📍', bonus: {morale: -12}, isPositive: false},
    {name: 'Верминофобия (страх червей)', emoji: '🪱', bonus: {food: -10, morale: -10}, isPositive: false},
    {name: 'Трихофобия (страх волос)', emoji: '💇', bonus: {morale: -10}, isPositive: false},
    {name: 'Хирофобия (страх рук и прикосновений)', emoji: '🤝', bonus: {morale: -12}, isPositive: false},
    {name: 'Дисморфофобия (навязчивое недовольство собой)', emoji: '🪞', bonus: {morale: -12}, isPositive: false},
    {name: 'Погонофобия (страх перед бородами)', emoji: '🧔', bonus: {morale: -8}, isPositive: false},
    {name: 'Микофобия (страх перед грибами)', emoji: '🍄', bonus: {food: -8, morale: -6}, isPositive: false},
    {name: 'Кинетофобия (страх движения и транспорта)', emoji: '🏃', bonus: {energy: -12}, isPositive: false},
    {name: 'Барофобия (страх гравитации и давления)', emoji: '🏋️', bonus: {energy: -14}, isPositive: false},
    {name: 'Метеорофобия (страх изменений погоды)', emoji: '☁️', bonus: {morale: -10}, isPositive: false},
];