import type {AttributeEntry} from "@/games/BunkerGame/types.ts";

export const PROFESSIONS: AttributeEntry[] = [
    {name: 'Хирург', emoji: '🩺', tier: 'S', bonus: {medicine: 25, morale: 5}, isPositive: true},
    {name: 'Инженер-энергетик', emoji: '⚡', tier: 'S', bonus: {energy: 25, food: 5}, isPositive: true},
    {name: 'Агроном', emoji: '🌾', tier: 'S', bonus: {food: 25, water: 5}, isPositive: true},
    {name: 'Психолог', emoji: '🧠', tier: 'A', bonus: {morale: 20, energy: 5}, isPositive: true},
    {name: 'Военный офицер', emoji: '🎖️', tier: 'A', bonus: {morale: 10, energy: 10, food: 5}, isPositive: true},
    {name: 'Эпидемиолог', emoji: '🔬', tier: 'A', bonus: {medicine: 20, food: 5}, isPositive: true},
    {name: 'Медсестра', emoji: '💊', tier: 'A', bonus: {medicine: 15, morale: 10}, isPositive: true},
    {name: 'Повар-шеф', emoji: '👨‍🍳', tier: 'B', bonus: {food: 15, morale: 8}, isPositive: true},
    {name: 'Охранник', emoji: '🛡️', tier: 'B', bonus: {morale: 10, energy: 8}, isPositive: true},
    {name: 'Механик', emoji: '🔧', tier: 'B', bonus: {energy: 15, food: 5}, isPositive: true},
    {name: 'Учёный-биолог', emoji: '🧬', tier: 'B', bonus: {medicine: 12, food: 5}, isPositive: true},
    {name: 'Учитель', emoji: '📚', tier: 'C', bonus: {morale: 12}, isPositive: true},
    {name: 'Программист', emoji: '💻', tier: 'C', bonus: {energy: 10}, isPositive: true},
    {name: 'Юрист', emoji: '⚖️', tier: 'C', bonus: {morale: 8}, isPositive: true},
    {name: 'Блогер-инфлюенсер', emoji: '📱', tier: 'C', bonus: {morale: 5}, isPositive: true},
    {name: 'Священник', emoji: '✝️', tier: 'C', bonus: {morale: 10}, isPositive: true},
    {name: 'Полицейский', emoji: '👮', tier: 'B', bonus: {morale: 12, energy: 5}, isPositive: true},
    {name: 'Биохимик', emoji: '🧪', tier: 'A', bonus: {medicine: 18, water: 5}, isPositive: true},
    {name: 'Терапевт', emoji: '🩹', tier: 'A', bonus: {medicine: 16, morale: 6}, isPositive: true},
    {name: 'Анестезиолог', emoji: '😴', tier: 'A', bonus: {medicine: 18, energy: 4}, isPositive: true},
    {name: 'Лаборант', emoji: '🧫', tier: 'B', bonus: {medicine: 12, water: 4}, isPositive: true},
    {name: 'Стоматолог', emoji: '🦷', tier: 'B', bonus: {medicine: 10, morale: 4}, isPositive: true},
    {name: 'Фармацевт', emoji: '💊', tier: 'A', bonus: {medicine: 17, food: 3}, isPositive: true},
    {name: 'Генетик', emoji: '🧬', tier: 'A', bonus: {medicine: 16, morale: 4}, isPositive: true},
    {name: 'Микробиолог', emoji: '🦠', tier: 'A', bonus: {medicine: 18, water: 3}, isPositive: true},
    {name: 'Сварщик', emoji: '🔥', tier: 'B', bonus: {energy: 14, water: 4}, isPositive: true},
    {name: 'Шахтёр', emoji: '⛏️', tier: 'B', bonus: {energy: 12, food: 4}, isPositive: true},
    {name: 'Геолог', emoji: '🪨', tier: 'B', bonus: {water: 10, energy: 5}, isPositive: true},
    {name: 'Метеоролог', emoji: '🌦️', tier: 'C', bonus: {morale: 6, water: 6}, isPositive: true},
    {name: 'Лесник', emoji: '🌲', tier: 'B', bonus: {food: 12, energy: 4}, isPositive: true},
    {name: 'Пасечник', emoji: '🐝', tier: 'C', bonus: {food: 8, morale: 5}, isPositive: true},
    {name: 'Пекарь', emoji: '🥖', tier: 'B', bonus: {food: 12, morale: 5}, isPositive: true},
    {name: 'Диетолог', emoji: '🥗', tier: 'C', bonus: {food: 8, medicine: 5}, isPositive: true},
    {name: 'Социальный работник', emoji: '🤝', tier: 'B', bonus: {morale: 14}, isPositive: true},
    {name: 'Переводчик', emoji: '🌐', tier: 'C', bonus: {morale: 7, water: 3}, isPositive: true},
    {name: 'Тактик', emoji: '🗺️', tier: 'A', bonus: {morale: 10, energy: 8, water: 4}, isPositive: true},
    {name: 'Инженер по вентиляции', emoji: '🌀', tier: 'A', bonus: {energy: 16, medicine: 4}, isPositive: true},
    {name: 'Кладовщик', emoji: '📦', tier: 'B', bonus: {food: 8, water: 8, morale: 3}, isPositive: true},
    {name: 'Ветеринар', emoji: '🐕', tier: 'A', bonus: {medicine: 14, food: 4}, isPositive: true},
    {name: 'Пожарный', emoji: '🚒', tier: 'A', bonus: {energy: 15, morale: 5}, isPositive: true},
    {name: 'Спасатель МЧС', emoji: '🆘', tier: 'S', bonus: {energy: 18, morale: 8}, isPositive: true},
    {name: 'Архитектор', emoji: '🏛️', tier: 'B', bonus: {energy: 10, morale: 4}, isPositive: true},
    {name: 'Строитель', emoji: '🧱', tier: 'A', bonus: {energy: 15, water: 4}, isPositive: true},
    {name: 'Сантехник', emoji: '🚰', tier: 'A', bonus: {water: 18}, isPositive: true},
    {name: 'Фермер', emoji: '🚜', tier: 'S', bonus: {food: 20, water: 5}, isPositive: true},
    {name: 'Зоотехник', emoji: '🐄', tier: 'B', bonus: {food: 12, morale: 4}, isPositive: true},
    {name: 'Кинолог', emoji: '🐕‍🦺', tier: 'B', bonus: {morale: 8, food: 5}, isPositive: true},
    {name: 'Пилот гражданской авиации', emoji: '✈️', tier: 'B', bonus: {morale: 8, energy: 6}, isPositive: true},
    {name: 'Диспетчер авиасообщения', emoji: '🎧', tier: 'B', bonus: {morale: 8, energy: 6}, isPositive: true},
    {name: 'Капитан дальнего плавания', emoji: '🚢', tier: 'A', bonus: {water: 12, morale: 6}, isPositive: true},
    {name: 'Моряк', emoji: '⚓', tier: 'B', bonus: {water: 10, energy: 6}, isPositive: true},
    {name: 'Водолаз', emoji: '🤿', tier: 'A', bonus: {water: 14, energy: 5}, isPositive: true},
    {name: 'Океанолог', emoji: '🌊', tier: 'B', bonus: {water: 12, medicine: 4}, isPositive: true},
    {name: 'Химик', emoji: '⚗️', tier: 'A', bonus: {medicine: 16, water: 4}, isPositive: true},
    {name: 'Физик', emoji: '🔭', tier: 'B', bonus: {energy: 12, morale: 3}, isPositive: true},
    {name: 'Инженер-робототехник', emoji: '🤖', tier: 'A', bonus: {energy: 18}, isPositive: true},
    {name: 'Системный администратор', emoji: '🖥️', tier: 'C', bonus: {energy: 10, morale: 2}, isPositive: true},
    {name: 'Специалист по кибербезопасности', emoji: '🔐', tier: 'B', bonus: {energy: 12, morale: 4}, isPositive: true},
    {name: 'Токарь', emoji: '⚙️', tier: 'B', bonus: {energy: 13, food: 3}, isPositive: true},
    {name: 'Фрезеровщик', emoji: '🔩', tier: 'B', bonus: {energy: 13}, isPositive: true},
    {name: 'Слесарь', emoji: '🛠️', tier: 'B', bonus: {energy: 14}, isPositive: true},
    {name: 'Кузнец', emoji: '🔨', tier: 'A', bonus: {energy: 15, morale: 4}, isPositive: true},
    {name: 'Плотник', emoji: '🪚', tier: 'B', bonus: {energy: 12, food: 3}, isPositive: true},
    {name: 'Каменщик', emoji: '🧱', tier: 'B', bonus: {energy: 12, water: 3}, isPositive: true},
    {name: 'Электромонтёр', emoji: '⚡', tier: 'A', bonus: {energy: 18}, isPositive: true},
    {name: 'Монтажник связи', emoji: '📡', tier: 'B', bonus: {energy: 12, morale: 3}, isPositive: true},
    {name: 'Оператор дронов', emoji: '🚁', tier: 'B', bonus: {energy: 10, morale: 5}, isPositive: true},
    {name: 'Картограф', emoji: '🗺️', tier: 'B', bonus: {water: 8, morale: 5}, isPositive: true},
    {name: 'Археолог', emoji: '🏺', tier: 'C', bonus: {morale: 8, food: 3}, isPositive: true},
    {name: 'Антрополог', emoji: '🦴', tier: 'C', bonus: {morale: 8, medicine: 3}, isPositive: true},
    {name: 'Историк', emoji: '📜', tier: 'C', bonus: {morale: 10}, isPositive: true},
    {name: 'Библиотекарь', emoji: '📚', tier: 'C', bonus: {morale: 9}, isPositive: true},
    {name: 'Журналист', emoji: '📰', tier: 'C', bonus: {morale: 8, energy: 3}, isPositive: true},
    {name: 'Фотограф', emoji: '📷', tier: 'C', bonus: {morale: 8}, isPositive: true},
    {name: 'Режиссёр', emoji: '🎬', tier: 'C', bonus: {morale: 10}, isPositive: true},
    {name: 'Музыкант', emoji: '🎻', tier: 'C', bonus: {morale: 12}, isPositive: true},
    {name: 'Актёр', emoji: '🎭', tier: 'C', bonus: {morale: 11}, isPositive: true},
    {name: 'Стендап-комик', emoji: '🎤', tier: 'C', bonus: {morale: 14}, isPositive: true},
    {name: 'Бармен', emoji: '🍹', tier: 'C', bonus: {morale: 10, food: 3}, isPositive: true},
    {name: 'Ресторатор', emoji: '🍽️', tier: 'B', bonus: {food: 10, morale: 6}, isPositive: true},
    {name: 'Логист', emoji: '📦', tier: 'B', bonus: {food: 8, water: 8}, isPositive: true},
    {name: 'Менеджер проектов', emoji: '📋', tier: 'B', bonus: {morale: 10, energy: 4}, isPositive: true},
    {name: 'Предприниматель', emoji: '💼', tier: 'C', bonus: {morale: 8, food: 4}, isPositive: true},
    {name: 'Космонавт', emoji: '🚀', tier: 'S', bonus: {energy: 18, morale: 8, water: 4}, isPositive: true},
    {name: 'Астрофизик', emoji: '🌌', tier: 'B', bonus: {energy: 10, morale: 5}, isPositive: true},
    {name: 'Селекционер растений', emoji: '🌿', tier: 'A', bonus: {food: 18, water: 4}, isPositive: true},
    {name: 'Технолог пищевого производства', emoji: '🥫', tier: 'A', bonus: {food: 16, medicine: 4}, isPositive: true},

    // Отрицательные и мусорные профессии (Tier C, isPositive: false)
    {name: 'Безработный', emoji: '🪑', tier: 'C', bonus: {morale: -5, energy: -5}, isPositive: false},
    {name: 'Банкир', emoji: '🏦', tier: 'C', bonus: {morale: -10, food: -5}, isPositive: false}, // Изменен знак бонуса
    {name: 'Разнорабочий на свалке', emoji: '🗑️', tier: 'C', bonus: {medicine: -10, morale: -5}, isPositive: false},
    {
        name: 'Профессиональный дегустатор фастфуда',
        emoji: '🍔',
        tier: 'C',
        bonus: {food: -12, energy: -6},
        isPositive: false
    },
    {name: 'Ночной сторож', emoji: '🔦', tier: 'C', bonus: {energy: -14, morale: -4}, isPositive: false},
    {name: 'Продавец-консультант', emoji: '🏪', tier: 'C', bonus: {morale: -12}, isPositive: false},
    {name: 'Менеджер по холодным звонкам', emoji: '📞', tier: 'C', bonus: {morale: -15, energy: -4}, isPositive: false},
    {name: 'Фасовщик угля', emoji: '🪵', tier: 'C', bonus: {medicine: -8, energy: -6}, isPositive: false},
    {name: 'Уборщик химотходов', emoji: '☣️', tier: 'C', bonus: {medicine: -14}, isPositive: false},
    {name: 'Кинокритик', emoji: '🍿', tier: 'C', bonus: {energy: -10, food: -4}, isPositive: false},
    {name: 'Бухгалтер в период отчетов', emoji: '📊', tier: 'C', bonus: {morale: -14, energy: -8}, isPositive: false},
    {name: 'Дворник в метель', emoji: '🧹', tier: 'C', bonus: {energy: -15, water: -4}, isPositive: false},
    {name: 'Профессиональный геймер', emoji: '🎮', tier: 'C', bonus: {energy: -12, medicine: -6}, isPositive: false},
    {name: 'Копирайтер на бирже', emoji: '⌨️', tier: 'C', bonus: {morale: -10, energy: -5}, isPositive: false},
    {name: 'Курьер службы доставки', emoji: '🚴', tier: 'C', bonus: {energy: -14, food: -5}, isPositive: false},
    {name: 'Тестировщик матрасов', emoji: '🛌', tier: 'C', bonus: {energy: -18, morale: -4}, isPositive: false},
    {name: 'Сотрудник архива', emoji: '📁', tier: 'C', bonus: {morale: -8, energy: -4}, isPositive: false},
    {name: 'Оператор конвейера', emoji: '🏭', tier: 'C', bonus: {morale: -12, energy: -6}, isPositive: false},
    {name: 'Коридорный в отеле', emoji: '🛎️', tier: 'C', bonus: {energy: -10}, isPositive: false},
    {name: 'Модельер обуви', emoji: '👠', tier: 'C', bonus: {morale: -6, food: -4}, isPositive: false},
    {name: 'Уличный мим', emoji: '🤍', tier: 'C', bonus: {morale: -14}, isPositive: false},
    {name: 'Ассистент фокусника', emoji: '🐇', tier: 'C', bonus: {energy: -8, morale: -4}, isPositive: false},
    {name: 'Дегустатор дешевого алкоголя', emoji: '🍾', tier: 'C', bonus: {medicine: -12, water: -8}, isPositive: false},
];