import type { AttributeEntry } from '@/games/BunkerGame/types.ts';

export const SPECIAL_FACTS: AttributeEntry[] = [
  { name: 'Бывший спецназовец', emoji: '⚔️', bonus: { energy: 15, morale: 5 }, isPositive: true },
  {
    name: 'Знает рецепты народной медицины',
    emoji: '🌿',
    bonus: { medicine: 12 },
    isPositive: true,
  },
  {
    name: 'Снайпер с опытом боевых действий',
    emoji: '🎯',
    bonus: { energy: 15 },
    isPositive: true,
  },
  {
    name: 'Выжил при прошлой эпидемии',
    emoji: '🏅',
    bonus: { medicine: 10, morale: 10 },
    isPositive: true,
  },
  {
    name: 'Знает тайный запасной вход',
    emoji: '🔒',
    bonus: { energy: 10, food: 5 },
    isPositive: true,
  },
  {
    name: 'Работал на строительстве бункера',
    emoji: '🏗️',
    bonus: { energy: 12, water: 5 },
    isPositive: true,
  },
  {
    name: 'Имеет радиолюбительскую лицензию',
    emoji: '📻',
    bonus: { morale: 10, energy: 5 },
    isPositive: true,
  },
  {
    name: 'Был в экспедиции в Антарктиде',
    emoji: '🧊',
    bonus: { food: 8, morale: 8 },
    isPositive: true,
  },
  {
    name: 'Создавал системы жизнеобеспечения',
    emoji: '🏭',
    bonus: { energy: 15 },
    isPositive: true,
  },
  { name: 'Владеет 5 языками', emoji: '🌐', bonus: { morale: 8 }, isPositive: true },
  { name: 'Бывший заключённый', emoji: '⛓️', bonus: { morale: -18, energy: 5 }, isPositive: false },
  {
    name: 'Имеет хронический конфликт с коллегами',
    emoji: '😠',
    bonus: { morale: -10 },
    isPositive: false,
  },
  {
    name: 'Отличник и перфекционист',
    emoji: '🎓',
    bonus: { morale: 5, medicine: 5 },
    isPositive: true,
  },
  {
    name: 'Богатый инвестор (без полезных навыков)',
    emoji: '💰',
    bonus: { morale: -25 },
    isPositive: false,
  },
  {
    name: 'Прожил год в изоляции',
    emoji: '🏔️',
    bonus: { morale: 10, energy: 5 },
    isPositive: true,
  },
  {
    name: 'Прошёл курсы тактической медицины',
    emoji: '🩹',
    bonus: { medicine: 14, energy: 4 },
    isPositive: true,
  },
  { name: 'Жил в автономном доме', emoji: '🏡', bonus: { energy: 10, water: 8 }, isPositive: true },
  {
    name: 'Умеет чинить фильтры воды',
    emoji: '💧',
    bonus: { water: 14, energy: 4 },
    isPositive: true,
  },
  {
    name: 'Организовывал гуманитарные миссии',
    emoji: '📦',
    bonus: { morale: 12, food: 4 },
    isPositive: true,
  },
  {
    name: 'Работал в тепличном комплексе',
    emoji: '🌿',
    bonus: { food: 14, water: 4 },
    isPositive: true,
  },
  { name: 'Служил связистом', emoji: '📡', bonus: { energy: 10, morale: 5 }, isPositive: true },
  {
    name: 'Вырос в деревне без удобств',
    emoji: '🚜',
    bonus: { food: 8, water: 6, morale: 4 },
    isPositive: true,
  },
  {
    name: 'Участвовал в арктической зимовке',
    emoji: '🧊',
    bonus: { energy: 8, morale: 8 },
    isPositive: true,
  },
  {
    name: 'Был волонтёром Красного Креста',
    emoji: '⛑️',
    bonus: { medicine: 12, morale: 6 },
    isPositive: true,
  },
  {
    name: 'Собирал тревожные рюкзаки до катастрофы',
    emoji: '🎒',
    bonus: { food: 6, water: 6, energy: 6 },
    isPositive: true,
  },
  {
    name: 'Работал диспетчером кризисного центра',
    emoji: '☎️',
    bonus: { morale: 10, energy: 4 },
    isPositive: true,
  },
  {
    name: 'Имеет опыт жизни на подлодке',
    emoji: '🚢',
    bonus: { morale: 10, energy: 5 },
    isPositive: true,
  },
  {
    name: 'Проходил курсы химзащиты',
    emoji: '☣️',
    bonus: { medicine: 10, water: 5 },
    isPositive: true,
  },
  {
    name: 'Умеет добывать огонь без спичек',
    emoji: '🔥',
    bonus: { energy: 10, morale: 3 },
    isPositive: true,
  },
  {
    name: 'Был старостой спасательного лагеря',
    emoji: '🏕️',
    bonus: { morale: 12, food: 3 },
    isPositive: true,
  },
  {
    name: 'Долги и криминальные связи',
    emoji: '💸',
    bonus: { morale: -10, energy: 4 },
    isPositive: false,
  },
  {
    name: 'Склонен скрывать важную информацию',
    emoji: '🤐',
    bonus: { morale: -18 },
    isPositive: false,
  },
  {
    name: 'Сбежал из секты выживальщиков',
    emoji: '🕯️',
    bonus: { morale: -25, food: 5, energy: 5 },
    isPositive: false,
  },
  {
    name: 'Потерял семью в первые дни катастрофы',
    emoji: '🖤',
    bonus: { morale: -10, energy: 3 },
    isPositive: false,
  },
  {
    name: 'Имеет репутацию мародёра',
    emoji: '🪓',
    bonus: { food: 5, morale: -12 },
    isPositive: false,
  },
  {
    name: 'Пережил авиакатастрофу',
    emoji: '✈️',
    bonus: { morale: 10, energy: 8 },
    isPositive: true,
  },
  {
    name: 'Участвовал в кругосветной экспедиции',
    emoji: '🌍',
    bonus: { water: 8, morale: 8 },
    isPositive: true,
  },
  {
    name: 'Знает координаты заброшенного военного склада',
    emoji: '🪖',
    bonus: { food: 10, energy: 10 },
    isPositive: true,
  },
  {
    name: 'Имеет собственную библиотеку по выживанию',
    emoji: '📚',
    bonus: { morale: 8, medicine: 5 },
    isPositive: true,
  },
  {
    name: 'Сдал нормативы спецназа',
    emoji: '🎖️',
    bonus: { energy: 15 },
    isPositive: true,
  },
  {
    name: 'Чемпион по спортивному ориентированию',
    emoji: '🧭',
    bonus: { water: 8, energy: 8 },
    isPositive: true,
  },
  {
    name: 'Построил дом своими руками',
    emoji: '🏠',
    bonus: { energy: 12, morale: 4 },
    isPositive: true,
  },
  {
    name: 'Имеет лицензию пилота',
    emoji: '🛩️',
    bonus: { energy: 10, morale: 5 },
    isPositive: true,
  },
  {
    name: 'Работал инструктором по выживанию',
    emoji: '🏕️',
    bonus: { food: 10, water: 10 },
    isPositive: true,
  },
  {
    name: 'Собрал коллекцию редких семян',
    emoji: '🌱',
    bonus: { food: 15 },
    isPositive: true,
  },

  {
    name: 'Выиграл международную олимпиаду',
    emoji: '🥇',
    bonus: { morale: 10, medicine: 4 },
    isPositive: true,
  },
  {
    name: 'Профессионально занимается альпинизмом',
    emoji: '🧗',
    bonus: { energy: 12, morale: 4 },
    isPositive: true,
  },
  {
    name: 'Прошёл курс первой помощи НАТО',
    emoji: '🚑',
    bonus: { medicine: 15 },
    isPositive: true,
  },
  {
    name: 'Работал на полярной станции',
    emoji: '❄️',
    bonus: { energy: 10, morale: 6 },
    isPositive: true,
  },
  {
    name: 'Выжил после нападения акулы',
    emoji: '🦈',
    bonus: { morale: 12, energy: 4 },
    isPositive: true,
  },
  {
    name: 'Мастер по ремонту генераторов',
    emoji: '⚙️',
    bonus: { energy: 15 },
    isPositive: true,
  },
  {
    name: 'Участвовал в археологических экспедициях',
    emoji: '🏺',
    bonus: { food: 5, morale: 8 },
    isPositive: true,
  },
  {
    name: 'Служил миротворцем ООН',
    emoji: '🕊️',
    bonus: { morale: 12, energy: 4 },
    isPositive: true,
  },
  {
    name: 'Был инструктором по дайвингу',
    emoji: '🤿',
    bonus: { water: 14 },
    isPositive: true,
  },
  {
    name: 'Победитель соревнований по стрельбе',
    emoji: '🎯',
    bonus: { energy: 12 },
    isPositive: true,
  },

  {
    name: 'Панически боится принимать решения',
    emoji: '😰',
    bonus: { morale: -12 },
    isPositive: false,
  },
  {
    name: 'Был уволен за халатность',
    emoji: '📄',
    bonus: { morale: -18 },
    isPositive: false,
  },
  {
    name: 'Постоянно провоцирует конфликты',
    emoji: '💢',
    bonus: { morale: -14 },
    isPositive: false,
  },
  {
    name: 'Имеет зависимость от азартных игр',
    emoji: '🎰',
    bonus: { morale: -10 },
    isPositive: false,
  },
  {
    name: 'Никогда не жил самостоятельно',
    emoji: '🍼',
    bonus: { morale: -16, energy: -24 },
    isPositive: false,
  },
  {
    name: 'Скрывает тяжёлое преступление',
    emoji: '🚔',
    bonus: { morale: -15 },
    isPositive: false,
  },
  {
    name: 'Был исключён из армии',
    emoji: '🎖️',
    bonus: { morale: -18, energy: -12 },
    isPositive: false,
  },
  {
    name: 'Регулярно саботирует работу команды',
    emoji: '🪓',
    bonus: { morale: -15 },
    isPositive: false,
  },
  {
    name: 'Не умеет плавать',
    emoji: '🌊',
    bonus: { water: -8 },
    isPositive: false,
  },
  {
    name: 'Катастрофически невезучий',
    emoji: '🐈‍⬛',
    bonus: { morale: -10 },
    isPositive: false,
  },

  {
    name: 'Умеет выращивать грибы',
    emoji: '🍄',
    bonus: { food: 12 },
    isPositive: true,
  },
  {
    name: 'Знает устройство солнечных панелей',
    emoji: '☀️',
    bonus: { energy: 14 },
    isPositive: true,
  },
  {
    name: 'Содержал большую ферму',
    emoji: '🐄',
    bonus: { food: 15 },
    isPositive: true,
  },
  {
    name: 'Пережил месяц в дикой природе',
    emoji: '🌲',
    bonus: { food: 8, water: 8 },
    isPositive: true,
  },
  {
    name: 'Был капитаном спортивной команды',
    emoji: '🏆',
    bonus: { morale: 12 },
    isPositive: true,
  },
  {
    name: 'Умеет собирать солнечные опреснители',
    emoji: '💧',
    bonus: { water: 15 },
    isPositive: true,
  },
  {
    name: 'Знает рецепты длительного хранения продуктов',
    emoji: '🥫',
    bonus: { food: 14 },
    isPositive: true,
  },
  {
    name: 'Имеет доступ к закрытому убежищу',
    emoji: '🚪',
    bonus: { food: 8, water: 8, morale: 5 },
    isPositive: true,
  },
  {
    name: 'Пережил три серьёзные операции',
    emoji: '🏥',
    bonus: { morale: 10, medicine: 5 },
    isPositive: true,
  },
  {
    name: 'Был координатором поисково-спасательных работ',
    emoji: '🚁',
    bonus: { energy: 10, morale: 8 },
    isPositive: true,
  },

  {
    name: 'Верит в теории заговора и навязывает их всем',
    emoji: '🛸',
    bonus: { morale: -10 },
    isPositive: false,
  },
  {
    name: 'Постоянно нарушает дисциплину',
    emoji: '🚫',
    bonus: { morale: -12 },
    isPositive: false,
  },
  {
    name: 'Не переносит замкнутые пространства',
    emoji: '📦',
    bonus: { morale: -10 },
    isPositive: false,
  },
  {
    name: 'Считает себя лидером независимо от мнения группы',
    emoji: '👑',
    bonus: { morale: -18 },
    isPositive: false,
  },
  {
    name: 'Склонен к панике во время кризиса',
    emoji: '😱',
    bonus: { morale: -12 },
    isPositive: false,
  },
  {
    name: 'Ненавидит физический труд',
    emoji: '🛋️',
    bonus: { energy: -28 },
    isPositive: false,
  },
  {
    name: 'Участвовал в реалити-шоу про выживание',
    emoji: '📺',
    bonus: { food: 5, water: 5, morale: 5 },
    isPositive: true,
  },
  {
    name: 'Имеет фотографическую память',
    emoji: '🧠',
    bonus: { medicine: 6, morale: 8 },
    isPositive: true,
  },
  {
    name: 'Знает карту местности наизусть',
    emoji: '🗺️',
    bonus: { water: 10, energy: 5 },
    isPositive: true,
  },
  {
    name: 'Выиграл чемпионат по шахматам',
    emoji: '♟️',
    bonus: { morale: 10, energy: 4 },
    isPositive: true,
  },
  {
    name: 'Крайне эгоистичен в распределении еды',
    emoji: '🍏',
    bonus: { food: -12 },
    isPositive: false,
  },
  {
    name: 'Страдает бессонницей и будит остальных',
    emoji: '🦉',
    bonus: { energy: -15, morale: -5 },
    isPositive: false,
  },
  {
    name: 'Гипохондрик, тратит лекарства впустую',
    emoji: '🧪',
    bonus: { medicine: -14 },
    isPositive: false,
  },
  {
    name: 'Не умеет экономно расходовать воду',
    emoji: '🚰',
    bonus: { water: -12 },
    isPositive: false,
  },
  {
    name: 'Часто впадает в глубокую апатию',
    emoji: '🌧️',
    bonus: { morale: -20, energy: -10 },
    isPositive: false,
  },
  {
    name: 'Абсолютно не умеет обращаться с техникой',
    emoji: '🔨',
    bonus: { energy: -18 },
    isPositive: false,
  },
  {
    name: 'Постоянно теряет выданные инструменты',
    emoji: '🔧',
    bonus: { energy: -12, morale: -4 },
    isPositive: false,
  },
  {
    name: 'Тяжело переносит любые изменения рациона',
    emoji: '🤢',
    bonus: { food: -10, morale: -10 },
    isPositive: false,
  },
  {
    name: 'Патологический лжец и манипулятор',
    emoji: '🎭',
    bonus: { morale: -22 },
    isPositive: false,
  },
  {
    name: 'Имеет слабую дыхательную систему',
    emoji: '🫁',
    bonus: { medicine: -10, energy: -8 },
    isPositive: false,
  },
  {
    name: 'Привык к роскоши, деморализует команду жалобами',
    emoji: '💅',
    bonus: { morale: -18 },
    isPositive: false,
  },
  {
    name: 'Неосторожен, постоянно получает мелкие травмы',
    emoji: '🩹',
    bonus: { medicine: -12, energy: -6 },
    isPositive: false,
  },
  {
    name: 'Бросает начатые дела при малейших трудностях',
    emoji: '🏳️',
    bonus: { energy: -15 },
    isPositive: false,
  },
  {
    name: 'Панически боится темноты и замкнутых пространств',
    emoji: '👁️‍🗨️',
    bonus: { morale: -15, energy: -10 },
    isPositive: false,
  },
  {
    name: 'Склонен портить чужие вещи в порыве злости',
    emoji: '🗯️',
    bonus: { morale: -14 },
    isPositive: false,
  },
];
