import type {SurvivalEvent} from "@/games/BunkerGame/types.ts";

export const SURVIVAL_EVENTS: SurvivalEvent[] = [
    {
        title: 'Разгерметизация сектора',
        description: 'В одном из жилых отсеков произошла утечка воздуха.',
        emoji: '🧯',
        effect: {energy: -20, morale: -15},
        positive: false,
    },
    {
        title: 'Пожар на складе медикаментов',
        description: 'Огонь уничтожил значительную часть медицинских запасов.',
        emoji: '🔥',
        effect: {medicine: -30, morale: -10},
        positive: false,
    },
    {
        title: 'Загрязнение теплицы',
        description: 'Неизвестная болезнь уничтожила большую часть урожая.',
        emoji: '🦠',
        effect: {food: -35},
        positive: false,
    },
    {
        title: 'Отказ реактора',
        description: 'Основной источник энергии остановлен до завершения ремонта.',
        emoji: '⚛️',
        effect: {energy: -40, morale: -10},
        positive: false,
    },
    {
        title: 'Массовое пищевое отравление',
        description: 'Испорченные продукты привели к вспышке болезни.',
        emoji: '🤢',
        effect: {food: -15, medicine: -25, morale: -15},
        positive: false,
    },
    {
        title: 'Серия краж',
        description: 'Кто-то систематически похищал припасы со складов.',
        emoji: '🕵️',
        effect: {food: -20, water: -20, morale: -20},
        positive: false,
    },
    {
        title: 'Бунт рабочих',
        description: 'Часть жителей отказалась выполнять свои обязанности.',
        emoji: '⚒️',
        effect: {morale: -35, energy: -15},
        positive: false,
    },
    {
        title: 'Разрушение водохранилища',
        description: 'Трещина в резервуаре привела к потере запасов воды.',
        emoji: '💧',
        effect: {water: -40},
        positive: false,
    },
    {
        title: 'Эпидемия неизвестной инфекции',
        description: 'Болезнь быстро распространяется среди жителей.',
        emoji: '☣️',
        effect: {medicine: -30, morale: -20},
        positive: false,
    },
    {
        title: 'Критический износ фильтров',
        description: 'Система очистки воздуха почти вышла из строя.',
        emoji: '🌫️',
        effect: {energy: -20, medicine: -15, morale: -15},
        positive: false,
    },
    {
        title: 'Провал экспедиции',
        description: 'Разведчики не вернулись, а ресурсы были потрачены впустую.',
        emoji: '🗺️',
        effect: {food: -15, energy: -20, morale: -20},
        positive: false,
    },
    {
        title: 'Радиационная утечка',
        description: 'Повреждённый контейнер вызвал заражение части комплекса.',
        emoji: '☢️',
        effect: {medicine: -20, energy: -20, morale: -20},
        positive: false,
    },
    {
        title: 'Падение морального духа',
        description: 'Жители начинают сомневаться, что спасение вообще возможно.',
        emoji: '😔',
        effect: {morale: -40},
        positive: false,
    },
    {
        title: 'Обрушение фермы',
        description: 'Конструкция гидропонной фермы не выдержала нагрузки.',
        emoji: '🌱',
        effect: {food: -30, energy: -10},
        positive: false,
    },
    {
        title: 'Поломка насосной станции',
        description: 'Вода перестала поступать в жилые отсеки.',
        emoji: '🚰',
        effect: {water: -30, energy: -10},
        positive: false,
    },
    {
        title: 'Смертельная плесень',
        description: 'Опасный грибок распространился по жилым помещениям.',
        emoji: '🍄',
        effect: {medicine: -20, food: -20, morale: -15},
        positive: false,
    },
    {
        title: 'Диверсия в энергосети',
        description: 'Неизвестный вывел из строя несколько ключевых систем.',
        emoji: '💣',
        effect: {energy: -35, morale: -15},
        positive: false,
    },
    {
        title: 'Черный рынок',
        description: 'Подпольная торговля привела к исчезновению запасов.',
        emoji: '💰',
        effect: {food: -15, medicine: -15, morale: -20},
        positive: false,
    },
    {
        title: 'Отказ системы очистки воды',
        description: 'Большая часть запасов оказалась заражена.',
        emoji: '🚱',
        effect: {water: -35, medicine: -15},
        positive: false,
    },
    {
        title: 'Катастрофическая авария',
        description: 'Сразу несколько систем жизнеобеспечения вышли из строя.',
        emoji: '💥',
        effect: {
            food: -15,
            water: -15,
            energy: -25,
            medicine: -15,
            morale: -25,
        },
        positive: false,
    },
    {
        title: 'Неисправный датчик радиации',
        description: 'Несколько недель система показывала ложную тревогу.',
        emoji: '📟',
        effect: {morale: 10},
        positive: true,
    },
    {
        title: 'Тайный запас шоколада',
        description: 'Кто-то обнаружил спрятанные сладости прошлых владельцев.',
        emoji: '🍫',
        effect: {morale: 15},
        positive: true,
    },
    {
        title: 'Засор фильтров',
        description: 'Воздух стал тяжелее, пришлось срочно менять фильтры.',
        emoji: '😷',
        effect: {energy: -10, morale: -10},
        positive: false,
    },
    {
        title: 'Успешная рыбалка',
        description: 'Подземное озеро оказалось богато рыбой.',
        emoji: '🎣',
        effect: {food: 20},
        positive: true,
    },
    {
        title: 'Поломка холодильников',
        description: 'Часть продуктов испортилась.',
        emoji: '🧊',
        effect: {food: -18},
        positive: false,
    },
    {
        title: 'Найден технический архив',
        description: 'В старых документах обнаружены полезные инструкции.',
        emoji: '📚',
        effect: {energy: 10, morale: 15},
        positive: true,
    },
    {
        title: 'Драка в столовой',
        description: 'Очередной спор за пайки закончился потасовкой.',
        emoji: '🥊',
        effect: {morale: -18},
        positive: false,
    },
    {
        title: 'Старый склад батарей',
        description: 'Удалось восстановить часть энергосистемы.',
        emoji: '🔋',
        effect: {energy: 20},
        positive: true,
    },
    {
        title: 'Неудачная охота',
        description: 'Разведчики вернулись ни с чем.',
        emoji: '🏹',
        effect: {energy: -20, morale: -20},
        positive: false,
    },
    {
        title: 'День талантов',
        description: 'Жители устроили концерт и подняли настроение.',
        emoji: '🎭',
        effect: {morale: 18},
        positive: true,
    },
    {
        title: 'Короткое замыкание',
        description: 'Несколько отсеков временно остались без света.',
        emoji: '💡',
        effect: {energy: -35},
        positive: false,
    },
    {
        title: 'Новый сорт растений',
        description: 'Учёным удалось вывести урожайную культуру.',
        emoji: '🪴',
        effect: {food: 15},
        positive: true,
    },
    {
        title: 'Саботаж оборудования',
        description: 'Кто-то намеренно повредил системы жизнеобеспечения.',
        emoji: '🔧',
        effect: {energy: -15, morale: -15},
        positive: false,
    },
    {
        title: 'Радиопередача надежды',
        description: 'Получен сигнал от других выживших.',
        emoji: '📻',
        effect: {morale: 20},
        positive: true,
    },
    {
        title: 'Мышиная эпидемия',
        description: 'Грызуны размножились быстрее, чем ожидалось.',
        emoji: '🐁',
        effect: {food: -32, morale: -28},
        positive: false,
    },
    {
        title: 'Самодельный очиститель',
        description: 'Инженеры улучшили систему очистки воды.',
        emoji: '🚿',
        effect: {water: 30},
        positive: true,
    },
    {
        title: 'Сломанный лифт',
        description: 'Доставка грузов между уровнями усложнилась.',
        emoji: '🛗',
        effect: {energy: -10},
        positive: false,
    },
    {
        title: 'Тренировка добровольцев',
        description: 'Жители стали организованнее и увереннее.',
        emoji: '🏋️',
        effect: {morale: 12},
        positive: true,
    },
    {
        title: 'Потеря медикаментов',
        description: 'Часть препаратов испортилась из-за неправильного хранения.',
        emoji: '💊',
        effect: {medicine: -15},
        positive: false,
    },
    {
        title: 'Открытие грибной фермы',
        description: 'Появился новый стабильный источник пищи.',
        emoji: '🍄',
        effect: {food: 18},
        positive: true,
    },
    {
        title: 'Протечка потолка',
        description: 'Вода повредила оборудование.',
        emoji: '💦',
        effect: {water: -20, energy: -20},
        positive: false,
    },
    {
        title: 'Неожиданное наследство',
        description: 'В личном шкафчике найдены забытые припасы.',
        emoji: '🎒',
        effect: {food: 10, medicine: 10},
        positive: true,
    },
    {
        title: 'Ложная тревога',
        description: 'Паника возникла из-за сбоя системы оповещения.',
        emoji: '🚨',
        effect: {morale: -15},
        positive: false,
    },
    {
        title: 'Успешный ремонт реактора',
        description: 'Основной источник энергии стабилизирован.',
        emoji: '⚛️',
        effect: {energy: 25},
        positive: true,
    },
    {
        title: 'Сломан инкубатор',
        description: 'Часть сельскохозяйственного проекта потеряна.',
        emoji: '🥚',
        effect: {food: -10},
        positive: false,
    },
    {
        title: 'Курс первой помощи',
        description: 'Многие жители освоили медицинские навыки.',
        emoji: '⛑️',
        effect: {medicine: 10, morale: 15},
        positive: true,
    },
    {
        title: 'Подозрение на шпиона',
        description: 'Никто никому не доверяет.',
        emoji: '🕶️',
        effect: {morale: -20},
        positive: false,
    },
    {
        title: 'Теплица расширена',
        description: 'Площадь выращивания культур увеличена.',
        emoji: '🏡',
        effect: {food: 20},
        positive: true,
    },
    {
        title: 'Перегрев оборудования',
        description: 'Системы работали на пределе возможностей.',
        emoji: '🌡️',
        effect: {energy: -20},
        positive: false,
    },
    {
        title: 'Обнаружена артезианская скважина',
        description: 'Запасы воды значительно выросли.',
        emoji: '🚰',
        effect: {water: 30},
        positive: true,
    },
    {
        title: 'Ссора соседей',
        description: 'Мелкий конфликт расколол коллектив.',
        emoji: '😡',
        effect: {morale: -10},
        positive: false,
    },
    {
        title: 'Письмо из прошлого',
        description: 'Найдены дневники прежних жителей бункера.',
        emoji: '📜',
        effect: {morale: 10},
        positive: true,
    },
    {
        title: 'Голодные дни',
        description: 'Пришлось сократить пайки.',
        emoji: '🍽️',
        effect: {food: -15, morale: -15},
        positive: false,
    },
    {
        title: 'Система рециркуляции улучшена',
        description: 'Расход воды удалось снизить.',
        emoji: '♻️',
        effect: {water: 15},
        positive: true,
    },
    {
        title: 'Сломался бур',
        description: 'Разведка подземных тоннелей остановлена.',
        emoji: '⛏️',
        effect: {energy: -10},
        positive: false,
    },
    {
        title: 'Детский праздник',
        description: 'Смех и радость напомнили людям о нормальной жизни.',
        emoji: '🎈',
        effect: {morale: 20},
        positive: true,
    },
    {
        title: 'Плесень в жилом секторе',
        description: 'Пришлось проводить санитарную обработку.',
        emoji: '🦠',
        effect: {medicine: -10, morale: -10},
        positive: false,
    },
    {
        title: 'Найден склад инструментов',
        description: 'Ремонтные работы стали проще.',
        emoji: '🧰',
        effect: {energy: 10},
        positive: true,
    },
    {
        title: 'Нехватка сна',
        description: 'Постоянный шум мешает людям отдыхать.',
        emoji: '😴',
        effect: {morale: -15},
        positive: false,
    },
    {
        title: 'Урожай картофеля',
        description: 'Теплица порадовала неожиданно хорошим результатом.',
        emoji: '🥔',
        effect: {food: 22},
        positive: true,
    },
    {
        title: 'Старая травма напомнила о себе',
        description: 'Одному из жителей понадобилось лечение.',
        emoji: '🩼',
        effect: {medicine: -10},
        positive: false,
    },
    {
        title: 'Удачная находка аккумуляторов',
        description: 'Восстановлены резервные системы.',
        emoji: '🔋',
        effect: {energy: 15},
        positive: true,
    },
    {
        title: 'Поломка насоса',
        description: 'Подача воды временно ограничена.',
        emoji: '🚿',
        effect: {water: -28},
        positive: false,
    },
    {
        title: 'Фестиваль кино',
        description: 'Старые фильмы помогли отвлечься от проблем.',
        emoji: '🎬',
        effect: {morale: 15},
        positive: true,
    },
    {
        title: 'Загрязнение резервуара',
        description: 'Часть воды оказалась непригодна для использования.',
        emoji: '🛢️',
        effect: {water: -15},
        positive: false,
    },
    {
        title: 'Удачный обмен по радио',
        description: 'Удалось договориться о поставке медикаментов.',
        emoji: '📡',
        effect: {medicine: 15},
        positive: true,
    },
    {
        title: 'Мятеж недовольных',
        description: 'Группа жителей отказалась подчиняться правилам.',
        emoji: '⚔️',
        effect: {morale: -45},
        positive: false,
    },
    {
        title: 'Открытие подземного сада',
        description: 'Заброшенный сектор оказался пригоден для выращивания еды.',
        emoji: '🌳',
        effect: {food: 25, morale: 10},
        positive: true,
    },
    {
        title: 'Повреждение кабелей',
        description: 'Часть энергосети вышла из строя.',
        emoji: '🔌',
        effect: {energy: -28},
        positive: false,
    },
    {
        title: 'День единства',
        description: 'Жители вместе отпраздновали очередной год выживания.',
        emoji: '🎊',
        effect: {morale: 25},
        positive: true,
    },
    {
        title: 'Прорыв трубы',
        description:
            'Водопроводная труба лопнула из-за перепада давления. Часть запасов воды потеряна.',
        emoji: '🚰',
        effect: {water: -20},
        positive: false,
    },
    {
        title: 'Пожар в генераторной',
        description: 'Короткое замыкание вызвало возгорание. Команда едва успела потушить.',
        emoji: '🔥',
        effect: {energy: -44},
        positive: false,
    },
    {
        title: 'Заражение продовольствия',
        description: 'Плесень поразила часть продовольственных запасов. Их пришлось уничтожить.',
        emoji: '🍄',
        effect: {food: -20},
        positive: false,
    },
    {
        title: 'Паника в бункере',
        description: 'Кто-то нашёл скрытые факты о запасах. Напряжение переросло в конфликт.',
        emoji: '😰',
        effect: {morale: -20},
        positive: false,
    },
    {
        title: 'Вирус распространяется',
        description: 'Один из выживших заболел. Команда вынуждена потратить медикаменты.',
        emoji: '🤒',
        effect: {medicine: -20, morale: -25},
        positive: false,
    },
    {
        title: 'Сбой вентиляции',
        description: 'Система воздухообмена дала сбой. Техники трудятся круглосуточно.',
        emoji: '💨',
        effect: {energy: -15, morale: -25},
        positive: false,
    },
    {
        title: 'Найдены дополнительные запасы',
        description: 'В техническом отсеке обнаружен забытый склад с консервами и водой.',
        emoji: '🎁',
        effect: {food: 15, water: 10},
        positive: true,
    },
    {
        title: 'Самодельный генератор',
        description: 'Умельцы из команды собрали запасной генератор из подручных материалов.',
        emoji: '⚡',
        effect: {energy: 15},
        positive: true,
    },
    {
        title: 'Медицинское открытие',
        description: 'Один из специалистов разработал средство против местного заражения.',
        emoji: '💉',
        effect: {medicine: 15, morale: 5},
        positive: true,
    },
    {
        title: 'Психологический кризис',
        description: 'Несколько людей впали в депрессию от замкнутого пространства.',
        emoji: '😢',
        effect: {morale: -15},
        positive: false,
    },
    {
        title: 'Успешная вылазка',
        description: 'Разведчики вернулись с добычей. Опасность того стоила.',
        emoji: '🎒',
        effect: {food: 12, medicine: 8},
        positive: true,
    },
    {
        title: 'Внешнее нападение отражено',
        description: 'Группа пытавшихся проникнуть в бункер отброшена. Но это дало нам o себе знать.',
        emoji: '🛡️',
        effect: {energy: -29, morale: -10},
        positive: false,
    },
    {
        title: 'Обнаружен подземный источник',
        description: 'После нескольких дней бурения найден чистый источник воды.',
        emoji: '💧',
        effect: {water: 25},
        positive: true,
    },
    {
        title: 'Нашли заброшенный склад',
        description: 'Разведчики обнаружили старый склад с уцелевшими припасами.',
        emoji: '📦',
        effect: {food: 20, medicine: 10},
        positive: true,
    },
    {
        title: 'Урожай в гидропонной ферме',
        description: 'Первый полноценный урожай превзошёл ожидания.',
        emoji: '🌱',
        effect: {food: 18, morale: 5},
        positive: true,
    },
    {
        title: 'Неожиданный союзник',
        description: 'По радио вышла на связь дружественная группа выживших.',
        emoji: '🤝',
        effect: {morale: 15, food: 5},
        positive: true,
    },
    {
        title: 'Успешный ремонт вентиляции',
        description: 'Инженеры модернизировали систему воздухообмена.',
        emoji: '🌀',
        effect: {energy: 10, morale: 10},
        positive: true,
    },
    {
        title: 'Найдена аптечка военного образца',
        description: 'Во время вылазки обнаружен медицинский контейнер.',
        emoji: '🩹',
        effect: {medicine: 20},
        positive: true,
    },
    {
        title: 'Удачная охота',
        description: 'Разведчики принесли крупную добычу.',
        emoji: '🦌',
        effect: {food: 20},
        positive: true,
    },
    {
        title: 'Праздник в бункере',
        description: 'Команда устроила вечер отдыха и игр.',
        emoji: '🎉',
        effect: {morale: 20},
        positive: true,
    },
    {
        title: 'Солнечные батареи заработали',
        description: 'Удалось подключить найденные панели.',
        emoji: '☀️',
        effect: {energy: 20},
        positive: true,
    },
    {
        title: 'Собран дождевой коллектор',
        description: 'Система сбора воды работает эффективно.',
        emoji: '🌧️',
        effect: {water: 18},
        positive: true,
    },

    {
        title: 'Крысы добрались до склада',
        description: 'Часть продовольствия уничтожена грызунами.',
        emoji: '🐀',
        effect: {food: -35},
        positive: false,
    },
    {
        title: 'Эпидемия гриппа',
        description: 'Несколько человек заболели одновременно.',
        emoji: '🤧',
        effect: {medicine: -35, morale: -30},
        positive: false,
    },
    {
        title: 'Утечка топлива',
        description: 'Повреждена система хранения топлива.',
        emoji: '⛽',
        effect: {energy: -44},
        positive: false,
    },
    {
        title: 'Потоп в техническом отсеке',
        description: 'Вода затопила часть оборудования.',
        emoji: '🌊',
        effect: {energy: -15, water: -20},
        positive: false,
    },
    {
        title: 'Массовая бессонница',
        description: 'Несколько недель люди не могут нормально отдыхать.',
        emoji: '😵‍💫',
        effect: {morale: -15},
        positive: false,
    },
    {
        title: 'Отравление водой',
        description: 'Система фильтрации дала сбой.',
        emoji: '☠️',
        effect: {water: -15, medicine: -10},
        positive: false,
    },
    {
        title: 'Обвал тоннеля',
        description: 'Один из запасных выходов полностью завален.',
        emoji: '🪨',
        effect: {energy: -15},
        positive: false,
    },
    {
        title: 'Кража припасов',
        description: 'Кто-то из жителей тайно присваивал ресурсы.',
        emoji: '🕵️',
        effect: {food: -30, morale: -45},
        positive: false,
    },
    {
        title: 'Смерть домашнего питомца',
        description: 'Любимец бункера погиб во время аварии.',
        emoji: '🐕',
        effect: {morale: -20},
        positive: false,
    },
    {
        title: 'Поломка очистителей',
        description: 'Система очистки воды временно вышла из строя.',
        emoji: '🚱',
        effect: {water: -20},
        positive: false,
    },

    {
        title: 'Рискованная вылазка',
        description: 'Команда принесла ресурсы, но понесла потери сил.',
        emoji: '🎒',
        effect: {food: 15, energy: -29},
        positive: true,
    },
    {
        title: 'Обмен с выжившими',
        description: 'Удалось выгодно обменять медикаменты на продукты.',
        emoji: '🔄',
        effect: {food: 35, medicine: -20},
        positive: true,
    },
    {
        title: 'Экономия ресурсов',
        description: 'Жёсткие ограничения подняли запасы, но испортили настроение.',
        emoji: '📉',
        effect: {food: 10, water: 10, morale: -35},
        positive: false,
    },
    {
        title: 'Новый жилец',
        description: 'В бункер проник выживший с полезными знаниями.',
        emoji: '🚪',
        effect: {morale: 10, food: -10},
        positive: true,
    },
    {
        title: 'Военный тайник',
        description: 'Обнаружены полезные запасы, но часть команды пострадала при поиске.',
        emoji: '🪖',
        effect: {medicine: 15, energy: -28},
        positive: true,
    },
    {
        title: 'Секретный склад алкоголя',
        description: 'Настроение улучшилось, дисциплина ухудшилась.',
        emoji: '🍾',
        effect: {morale: 25, energy: -38},
        positive: true,
    },
    {
        title: 'Ускоренное выращивание культур',
        description: 'Для урожая пришлось потратить дополнительные ресурсы.',
        emoji: '🌾',
        effect: {food: 30, water: -20},
        positive: true,
    },
    {
        title: 'Генератор на пределе',
        description: 'Удалось получить больше энергии ценой износа системы.',
        emoji: '⚡',
        effect: {energy: 20, morale: -25},
        positive: true,
    },
    {
        title: 'Спор о лидерстве',
        description: 'После голосования группа раскололась на два лагеря.',
        emoji: '👑',
        effect: {morale: -18},
        positive: false,
    },
    {
        title: 'Радиационный шторм снаружи',
        description: 'Пришлось срочно герметизировать часть бункера.',
        emoji: '☢️',
        effect: {
            energy: -45,
            water: -25,
            morale: -20,
        },
        positive: false,
    },
    {
        title: 'Удачная фильтрация',
        description: 'Инженеры смогли очистить заблокированные резервуары, вернув воду в систему.',
        emoji: '🧪',
        effect: {water: 25},
        positive: true,
    },
    {
        title: 'Оптимизация энергосети',
        description: 'Новый алгоритм распределения питания снизил нагрузку на генераторы.',
        emoji: '📈',
        effect: {energy: 20},
        positive: true,
    },
    {
        title: 'День отдыха',
        description: 'Руководство объявило внеочередной выходной. Люди смогли выспаться.',
        emoji: '🛋️',
        effect: {morale: 25},
        positive: true,
    },
    {
        title: 'Подземная грибница',
        description: 'В вентиляционных шахтах обнаружен съедобный и питательный мох.',
        emoji: '🍄',
        effect: {food: 15},
        positive: true,
    },
    {
        title: 'Старый армейский стимулятор',
        description: 'В забытом ящике медика нашли партию эффективных витаминов.',
        emoji: '🧪',
        effect: {medicine: 20},
        positive: true,
    },
    {
        title: 'Чистая случайность',
        description: 'Обнаружен скрытый кабель от соседнего заброшенного узла связи.',
        emoji: '🔌',
        effect: {energy: 15, morale: 10},
        positive: true,
    },
    {
        title: 'Конкурс поваров',
        description: 'Из стандартных пайков удалось приготовить потрясающий праздничный ужин.',
        emoji: '👨‍🍳',
        effect: {food: 15, morale: 15},
        positive: true,
    },
    {
        title: 'Естественный дренаж',
        description: 'Стены бункера пропустили чистую грунтовую воду прямо в очистительную систему.',
        emoji: '⛲',
        effect: {water: 20},
        positive: true,
    },
    {
        title: 'Тайник инженера',
        description: 'Найден ящик с деталями, которые давно считались дефицитными.',
        emoji: '🛠️',
        effect: {energy: 25},
        positive: true,
    },
    {
        title: 'Примирение фракций',
        description: 'Лидеры спорящих групп смогли договориться. Напряжение в бункере спало.',
        emoji: '🤝',
        effect: {morale: 30},
        positive: true,
    },
    {
        title: 'Сверхэффективный антибиотик',
        description: 'Лаборатория синтезировала сильное лекарство из местной плесени.',
        emoji: '🧪',
        effect: {medicine: 25},
        positive: true,
    },
    {
        title: 'Аномальный приток энергии',
        description: 'Внешняя буря создала наводку на внешние контуры, зарядив батареи.',
        emoji: '⚡',
        effect: {energy: 30},
        positive: true,
    },
    {
        title: 'Психологическая разгрузка',
        description: 'Старый игровой автомат снова заработал в зоне отдыха.',
        emoji: '🕹️',
        effect: {morale: 20},
        positive: true,
    },
    {
        title: 'Склад гидропоники',
        description: 'В запечатанном ящике найдены концентрированные питательные растворы.',
        emoji: '🧪',
        effect: {food: 25},
        positive: true,
    },
    {
        title: 'Конденсаторный сборщик',
        description: 'Техники собрали установку, улавливающую влагу из горячего воздуха турбин.',
        emoji: '💧',
        effect: {water: 15},
        positive: true,
    },
    {
        title: 'Хорошие новости по радио',
        description: 'Сквозь помехи пробился отчет о стабилизации ситуации на поверхности.',
        emoji: '📻',
        effect: {morale: 35},
        positive: true,
    },
    {
        title: 'Армейские сухпайки',
        description: 'Разведчики нашли заваленный люк с нетронутыми рационами высокой калорийности.',
        emoji: '🥫',
        effect: {food: 30},
        positive: true,
    },
    {
        title: 'Резервные предохранители',
        description: 'Замена сгоревших узлов предотвратила регулярные перебои со светом.',
        emoji: '🎛️',
        effect: {energy: 20},
        positive: true,
    },
    {
        title: 'Иммунитет укреплен',
        description: 'Успешная профилактика снизила общую заболеваемость в жилом секторе.',
        emoji: '🏥',
        effect: {medicine: 15, morale: 10},
        positive: true,
    },
    {
        title: 'Новый источник света',
        description: 'Замена старых ламп на энергосберегающие диоды сделала отсеки уютнее.',
        emoji: '💡',
        effect: {energy: 15, morale: 15},
        positive: true,
    },
    {
        title: 'Качественная изоляция',
        description: 'Герметизация стыков снизила потери тепла и очищенного воздуха.',
        emoji: '🏗️',
        effect: {energy: 15, water: 10},
        positive: true,
    },
    {
        title: 'Музыкальная трансляция',
        description: 'Радист настроился на старую автоматическую станцию, крутящую джаз.',
        emoji: '🎶',
        effect: {morale: 20},
        positive: true,
    },
];