import type {AttributeEntry} from "@/games/BunkerGame/types.ts";

export const TRAITS: AttributeEntry[] = [
    {name: 'Прирождённый лидер', emoji: '🦁', bonus: {morale: 15}, isPositive: true},
    {name: 'Хладнокровие', emoji: '🧊', bonus: {morale: 10, energy: 5}, isPositive: true},
    {name: 'Изобретательность', emoji: '💡', bonus: {energy: 8, food: 5}, isPositive: true},
    {name: 'Сильная эмпатия', emoji: '🤝', bonus: {morale: 12}, isPositive: true},
    {name: 'Стальная воля', emoji: '⚙️', bonus: {morale: 10, energy: 5}, isPositive: true},
    {name: 'Вспыльчивость', emoji: '😤', bonus: {morale: -12}, isPositive: false},
    {name: 'Эгоцентризм', emoji: '🙄', bonus: {morale: -10, food: -5}, isPositive: false},
    {name: 'Хроническая тревожность', emoji: '😟', bonus: {morale: -10}, isPositive: false},
    {name: 'Манипулятор', emoji: '🎭', bonus: {morale: -18}, isPositive: false},
    {name: 'Безграничный оптимизм', emoji: '😊', bonus: {morale: 10}, isPositive: true},
    {name: 'Дисциплинированность', emoji: '📏', bonus: {energy: 8, morale: 5}, isPositive: true},
    {name: 'Самопожертвование', emoji: '🕊️', bonus: {morale: 12, medicine: 4}, isPositive: true},
    {name: 'Терпеливость', emoji: '⏳', bonus: {morale: 8, food: 4}, isPositive: true},
    {name: 'Практичность', emoji: '🧰', bonus: {energy: 7, water: 4}, isPositive: true},
    {name: 'Командность', emoji: '👥', bonus: {morale: 10}, isPositive: true},
    {name: 'Наблюдательность', emoji: '👁️', bonus: {food: 5, energy: 5}, isPositive: true},
    {name: 'Бережливость', emoji: '💼', bonus: {food: 6, water: 6}, isPositive: true},
    {name: 'Харизма', emoji: '✨', bonus: {morale: 14}, isPositive: true},
    {name: 'Ответственность', emoji: '🧾', bonus: {morale: 8, medicine: 4}, isPositive: true},
    {name: 'Упорство', emoji: '🪨', bonus: {energy: 10, morale: 4}, isPositive: true},
    {name: 'Жадность', emoji: '🪙', bonus: {food: -8, morale: -18}, isPositive: false},
    {name: 'Лень', emoji: '🛋️', bonus: {energy: -29, morale: -14}, isPositive: false},
    {name: 'Трусость', emoji: '🐇', bonus: {morale: -10, energy: -25}, isPositive: false},
    {name: 'Подозрительность', emoji: '🕵️', bonus: {morale: -18}, isPositive: false},
    {name: 'Упрямство', emoji: '🫏', bonus: {morale: -7, energy: -13}, isPositive: false},
    {name: 'Неряшливость', emoji: '🧹', bonus: {medicine: -8, morale: -14}, isPositive: false},
    {name: 'Истеричность', emoji: '🎭', bonus: {morale: -12}, isPositive: false},
    {name: 'Злопамятность', emoji: '🧠', bonus: {morale: -7}, isPositive: false},
    {name: 'Безответственность', emoji: '📉', bonus: {energy: -26, morale: -16}, isPositive: false},
    {name: 'Самовлюблённость', emoji: '🪞', bonus: {morale: -18, food: -14}, isPositive: false},
    {name: 'Стратегическое мышление', emoji: '♟️', bonus: {morale: 8, energy: 5}, isPositive: true},
    {name: 'Самообладание', emoji: '🧘', bonus: {morale: 12}, isPositive: true},
    {name: 'Любознательность', emoji: '🔍', bonus: {medicine: 4, energy: 4}, isPositive: true},
    {name: 'Находчивость', emoji: '🎯', bonus: {food: 5, energy: 5}, isPositive: true},
    {name: 'Чувство юмора', emoji: '😂', bonus: {morale: 15}, isPositive: true},
    {name: 'Добродушие', emoji: '😊', bonus: {morale: 10}, isPositive: true},
    {name: 'Верность слову', emoji: '🤝', bonus: {morale: 10}, isPositive: true},
    {name: 'Справедливость', emoji: '⚖️', bonus: {morale: 12}, isPositive: true},
    {name: 'Осторожность', emoji: '🚧', bonus: {food: 4, water: 4, morale: 4}, isPositive: true},
    {name: 'Трудолюбие', emoji: '🔨', bonus: {energy: 12}, isPositive: true},
    {name: 'Стрессоустойчивость', emoji: '🛡️', bonus: {morale: 10, energy: 4}, isPositive: true},
    {name: 'Настойчивость', emoji: '🐂', bonus: {energy: 10}, isPositive: true},
    {name: 'Аккуратность', emoji: '📐', bonus: {medicine: 5, morale: 5}, isPositive: true},
    {name: 'Дальновидность', emoji: '🔭', bonus: {food: 4, water: 4, morale: 4}, isPositive: true},
    {name: 'Смелость', emoji: '🦅', bonus: {energy: 10, morale: 5}, isPositive: true},
    {name: 'Адаптивность', emoji: '🦎', bonus: {energy: 6, food: 4, water: 4}, isPositive: true},
    {name: 'Пунктуальность', emoji: '⏰', bonus: {energy: 6, morale: 4}, isPositive: true},
    {name: 'Миролюбие', emoji: '☮️', bonus: {morale: 14}, isPositive: true},
    {name: 'Скромность', emoji: '🙂', bonus: {morale: 8, food: 4}, isPositive: true},
    {name: 'Жизнерадостность', emoji: '🌞', bonus: {morale: 14}, isPositive: true},
    {name: 'Перфекционизм', emoji: '📏', bonus: {energy: -4, morale: -6}, isPositive: false},
    {name: 'Импульсивность', emoji: '⚡', bonus: {energy: -10, morale: -8}, isPositive: false},
    {name: 'Пессимизм', emoji: '🌧️', bonus: {morale: -15}, isPositive: false},
    {name: 'Высокомерие', emoji: '👑', bonus: {morale: -12}, isPositive: false},
    {name: 'Завистливость', emoji: '🐍', bonus: {morale: -10}, isPositive: false},
    {name: 'Саркастичность', emoji: '😏', bonus: {morale: -8}, isPositive: false},
    {name: 'Мстительность', emoji: '🗡️', bonus: {morale: -12}, isPositive: false},
    {name: 'Конфликтность', emoji: '🥊', bonus: {morale: -15}, isPositive: false},
    {name: 'Бестактность', emoji: '📢', bonus: {morale: -10}, isPositive: false},
    {name: 'Безынициативность', emoji: '🪫', bonus: {energy: -12}, isPositive: false},
    {name: 'Прокрастинация', emoji: '⌛', bonus: {energy: -14}, isPositive: false},
    {name: 'Рассеянность', emoji: '🌀', bonus: {medicine: -5, energy: -8}, isPositive: false},
    {name: 'Наивность', emoji: '🐣', bonus: {morale: -6, food: -4}, isPositive: false},
    {name: 'Зависимость от чужого мнения', emoji: '👥', bonus: {morale: -12}, isPositive: false},
    {name: 'Нетерпеливость', emoji: '🏃', bonus: {morale: -6, energy: -8}, isPositive: false},
    {name: 'Ревнивость', emoji: '💚', bonus: {morale: -10}, isPositive: false},
    {name: 'Уныние', emoji: '😞', bonus: {morale: -14}, isPositive: false},
    {name: 'Циничность', emoji: '🗿', bonus: {morale: -8}, isPositive: false},
    {name: 'Грубость', emoji: '🤬', bonus: {morale: -12}, isPositive: false},
    {name: 'Нытьё по любому поводу', emoji: '😭', bonus: {morale: -15}, isPositive: false},
    {name: 'Авантюризм', emoji: '🎲', bonus: {energy: 8, morale: -4}, isPositive: true},
    {name: 'Убедительность', emoji: '🗣️', bonus: {morale: 10}, isPositive: true},
    {name: 'Самостоятельность', emoji: '🧭', bonus: {energy: 8, morale: 4}, isPositive: true},
    {name: 'Способность к обучению', emoji: '📖', bonus: {medicine: 4, morale: 4}, isPositive: true},
    {name: 'Решительность', emoji: '⚔️', bonus: {energy: 10, morale: 4}, isPositive: true},
    {name: 'Внимательность к деталям', emoji: '🔬', bonus: {medicine: 6, energy: 4}, isPositive: true},
    {name: 'Надёжность', emoji: '🏗️', bonus: {morale: 10, energy: 4}, isPositive: true},
    {name: 'Организованность', emoji: '📋', bonus: {food: 4, water: 4, morale: 4}, isPositive: true},
    {name: 'Умение вдохновлять', emoji: '🔥', bonus: {morale: 15}, isPositive: true},
    {name: 'Железная дисциплина', emoji: '🪖', bonus: {energy: 10, morale: 5}, isPositive: true},
    {name: 'Черствость', emoji: '🪵', bonus: {morale: -10}, isPositive: false},
    {name: 'Фанатичность', emoji: '🧎', bonus: {morale: -14, energy: -6}, isPositive: false},
    {name: 'Расточительность', emoji: '💸', bonus: {food: -10, water: -10}, isPositive: false},
    {name: 'Брезгливость', emoji: '🤢', bonus: {medicine: -8, food: -5}, isPositive: false},
    {name: 'Апатичность', emoji: '💤', bonus: {energy: -20, morale: -10}, isPositive: false},
    {name: 'Мнительность', emoji: '💊', bonus: {medicine: -12, morale: -6}, isPositive: false},
    {name: 'Эгоизм', emoji: '🍏', bonus: {food: -12, morale: -4}, isPositive: false},
    {name: 'Паникёрство', emoji: '📢', bonus: {morale: -18}, isPositive: false},
    {name: 'Черный пессимизм', emoji: '🕶️', bonus: {morale: -20}, isPositive: false},
    {name: 'Слабохарактерность', emoji: '🎈', bonus: {energy: -15, morale: -8}, isPositive: false},
];